<?php 

    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->statusId.'_'.$this->zoneconfig['conf']['id'];
    }       
 
?>
<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="nav-item active">
                            <a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons <?php echo ($this->attributeValueId) ? 'pencil' : 'plus'?>" data-bs-toggle="tab" aria-expanded="true"><i></i> 
                		    <?= $this->translate($this->modalName) ?></a>
                        </li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" id="<?php echo $id ?>">
                            <div class="row">
                            	<div class="col-md-12">
                            	<p><?= $this->translate('tr_meliscommerce_order_status_modal_text')?></p>
                                    <?php
                                        echo $this->form()->openTag($this->statusForm);
                                    ?>
                                    <div class="float-right">
                                        <div id="<?= $this->statusId.'_status' ?>" data-melisKey="<?= $this->melisKey; ?>" class="make-switch main_variant_switch" data-on-label="<?php echo $this->translate('tr_meliscommerce_coupon_page_status_online')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_coupon_page_status_offline')?>" data-text-label="<?php echo $this->translate('tr_meliscommerce_coupon_page_status')?>">
                                            <input type="checkbox" name="osta_status" id="var_status"  <?= $this->status ?>>
                                        </div>
                                    </div>
                                    <script type="text/javascript">
                                    	$("#<?= $this->statusId.'_status' ?>").bootstrapSwitch();
                                    </script>	
                                    <div class="clearfix"></div>
                                    <?php 
                                        echo $this->melisFieldCollection($this->statusForm);
                                        echo $this->form()->closeTag();
                                    ?>
                                    <script>
                                        $(function() {
                                            $(".osta_color_code").colorpicker({color : "<?=$this->color ?>", format: "hex"});
                                            $("body").find(".form-group label[for='osta_color_code']").addClass("d-flex flex-row justify-content-between");
                                        });
                                    </script>
                                    <br>
                                    <?php 
                                        echo '<h4>'.$this->translate('tr_meliscommerce_attribute_label_all').'</h4>';
                                        echo $this->form()->openTag($this->fillAllForm);
                                        echo $this->melisFieldCollection($this->fillAllForm);
                                        echo $this->form()->closeTag();
                                    ?>
                                    <br>
                                    <div class="card default-card commerce-toggle product-create-text">
                                    	<div class="card-header">
                                    		<h4 class="card-title">
                                    			<a class="accordion-toggle collapsed" id="" data-bs-toggle="collapse" href="#fill_<?= $this->zoneconfig['conf']['id']?>"><?= $this->translate('tr_meliscommerce_attribute_value_modal_each_language')?></a>
                                			</h4>
                                        </div>
                                    	<div class="card-collapse collapse" id="fill_<?= $this->zoneconfig['conf']['id']?>">                                		
                                    		<div class="card-body">
                                          		<div class="innerAll spacing-x2">
                                		     		<?php
                                            		$forms = $this->forms;                                		
                                            		for($c = 0; $c< count($this->langs); $c++):
														$imageData = $this->langs[$c]->elang_flag;
														$image = !empty($imageData) ? '<img src="data:image/jpeg;base64,'. ($imageData) .'" class="imgDisplay"/>' : '<i class="fa fa-globe"></i>';
                                            		echo '<h4>'.$image.' ' .$this->langs[$c]->elang_name.'</h4>';
                                            		echo $this->form()->openTag($forms[$c]);
                                            		echo $this->melisFieldCollection($forms[$c]);
                                            		echo $this->form()->closeTag();
                                            		
                                            		endfor;
                                            		?>
                                          		</div>
                                          	</div>                                		
                                    	</div>
                                	</div>
                                    <div class="footer-modal d-flex flex-row justify-content-between">
                                 		<button data-bs-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                                 		<button class="btn btn-success" id="saveOrderStatusForm" data-statusid="<?= $this->statusId ?>"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscommerce_orders_common_btn_save') ?></button>
                                 	</div>                                 	
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
