<?php 

    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->attributeId.'_'.$this->zoneconfig['conf']['id'];
    }       
 
?>
<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="nav-item active">
							<a data-bs-target="#<?php echo $this->zoneconfig['conf']['id'] ?>" href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons <?php echo ($this->attributeValueId) ? 'pencil' : 'plus'?>" data-bs-toggle="tab" aria-expanded="true"><i></i> 
                			<?= $this->zoneconfig['conf']['name'] ?>
							</a>
						</li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" id="<?php echo $id ?>">
                            <div class="row">
                            	<div class="col-md-12">
                                    <?php
                                        echo '<h4>'.$this->translate('tr_meliscommerce_attribute_label_all').'</h4>';
                                        echo '<p>'.$this->translate('tr_meliscommerce_attribute_value_modal_description').'</p>';
                                        echo $this->form()->openTag($this->fillAllForm);
                                        echo $this->melisFieldCollection($this->fillAllForm);
                                        echo $this->form()->closeTag();
                                    ?>
                                    <br>
                                    <div class="card default-card commerce-toggle product-create-text">
                                    	<div class="card-header" >
                                    		<h4 class="card-title">
                                    			<a class="accordion-toggle collapsed" id="" data-bs-toggle="collapse" href="#fill_<?= $this->zoneconfig['conf']['id']?>"><?= $this->translate('tr_meliscommerce_attribute_value_modal_each_language')?></a>
                                			</h4>
										</div>
										<div class="card-collapse collapse" id="fill_<?= $this->zoneconfig['conf']['id']?>">   
                                    		<div class="card-body">
                                          		<div class="innerAll spacing-x2">
                                		     		<?php
                                            		$forms = $this->forms;                                		
                                            		for($c = 0; $c< count($this->langs); $c++):
														$imageData = $this->langs[$c]->elang_flag;
														$image = !empty($imageData) ? '<img src="data:image/jpeg;base64,'. ($imageData) .'" class="imgDisplay"/>' : '<i class="fa fa-globe"></i>';
                                            		echo '<h4>'.$image.' ' .$this->langs[$c]->elang_name.'</h4>';
                                            		echo $this->form()->openTag($forms[$c]);
                                            		echo $this->melisFieldCollection($forms[$c]);
                                            		echo $this->form()->closeTag();
                                            		
                                            		endfor;
                                            		?>
                                          		</div>
                                          	</div>                                		
                                    	</div>
                                	</div>
                                    <?= $this->datePickerInit;?>
                                 	<style>
                                    .datepicker{z-index:1151 !important;}
                                    </style>
                                    <br>
									<div class="footer-modal d-flex flex-row justify-content-between">
                                 		<button data-bs-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                                 		<button class="btn btn-success" id="saveAttributeValue"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscommerce_orders_common_btn_save') ?></button>
                                 	</div>                                 	
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
