<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->attributeId.'_'.$this->zoneconfig['conf']['id'];
    }
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="row">
		<div class="col-xs-12 col-md-4">
    		<div class="product-text-tab-container">
            	<ul class="nav-tabs product-text-tab">
            		<?php 
            		$active = 'active';
            		foreach($this->langs as $lang):
            		?>
                		<li class="<?= $active ?>">
                			<a class="clearfix" data-toggle="tab" href="#<?= $lang->elang_locale.$id ?>" aria-expanded="true">
								<?php
								$imageData = $lang->elang_flag;
								$image = !empty($imageData) ? '<img src="data:image/jpeg;base64,'. ($imageData) .'" class="imgDisplay pull-right"/>' : '<i class="fa fa-globe"></i>';

								?>
								<span class="pull-right"><?php echo $image; ?></span>
                				<span><?= $lang->elang_name ?></span>
                			</a>
                		</li>                		
            		<?php 
            		$active = '';
            		endforeach;
            		?>
            	</ul>
            </div>
		</div>
		<div class="col-xs-12 col-md-8">
			<div class="tab-content">
				<?php
				$active = 'active';
				for($i = 0; $i < count($this->langs); $i++):
				?>
				<div id="<?= $this->langs[$i]->elang_locale.$id?>" class="tab-pane product-text-tab-content <?= $active ?>">
					<div class="me-heading bg-white border-bottom">
            			<h3 class=""><i class="fa fa-language" aria-hidden="true"></i> <?= $this->langs[$i]->elang_name?></h3>
            		</div>
            		<div class="product-text-tab-form-content">
            			<?php             			
            			echo $this->form()->openTag($this->forms[$i]);
            			echo $this->melisFieldCollection($this->forms[$i]);
            			echo $this->form()->closeTag();
            			?>
            		</div>
                </div>
            	<?php 
            	$active = '';
            	endfor;
            	?>				
			</div>
		</div>
	</div>