import { mergeDict } from '../../shared/i18n'

/** Dictionnaire spécifique à l'outil Comptes (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Comptes clients', subtitle: 'Comptes clients MelisCommerce',
    new: 'Nouveau compte', search: 'Rechercher un compte…', empty: 'Aucun compte trouvé', filter_group: 'Tous les groupes',
    count: '{n} comptes — fin de la liste',
    col_id: 'ID', col_name: 'Nom', col_status: 'Statut', col_group: 'Groupe', col_country: 'Pays', col_created: 'Créé le',
    exp_title: 'Exporter les comptes', exp_subtitle: '{n} comptes seront exportés', exp_filename: 'comptes',
    del_title: 'Supprimer le compte', del_confirm: 'Supprimer « {u} » ? Cette action est irréversible.',
    new_title: 'Nouveau compte', edit_title: 'Modifier le compte',
    f_identity: 'Identité', f_options: 'Options',
    f_name: 'Nom', f_name_ph: 'Nom du compte', f_tags: 'Tags', f_tags_ph: 'Tags séparés par des virgules',
    f_country: 'Pays', f_country_ph: '— Choisir un pays —', f_group: 'Groupe', f_group_none: '— Aucun groupe —',
    f_active: 'Actif', f_active_hint: 'Le compte est actif et utilisable.',
    err_name: 'Le nom est obligatoire.', err_country: 'Le pays est obligatoire.', err_save: 'Erreur lors de la sauvegarde',
    err_required_fields: 'Veuillez vérifier les champs obligatoires.',
    tab_properties: 'Propriétés', tab_contacts: 'Contacts', tab_company: 'Société', tab_addresses: 'Adresses', tab_orders: 'Commandes', tab_files: 'Fichiers',
    save_first: 'Enregistrez le compte pour accéder à cet onglet.',
    co_name: 'Raison sociale', co_number: 'N° d’identification', co_vat: 'N° TVA', co_group: 'Groupe', co_employees: 'Effectif',
    co_address: 'Adresse', co_street: 'Rue', co_zip: 'Code postal', co_city: 'Ville', co_state: 'État/Région', co_country: 'Pays',
    co_phone: 'Téléphone', co_website: 'Site web', co_section_id: 'Identité société', co_section_addr: 'Adresse société',
    c_firstname: 'Prénom', c_name: 'Nom', c_email: 'Email', c_civility: 'Civilité', c_empty: 'Aucun contact associé',
    c_def_contact: 'Contact par défaut', c_def_account: 'Compte par défaut',
    c_link_ph: 'Nom du contact', c_link: 'Lier le contact', c_add: 'Ajouter un contact',
    c_unlink_title: 'Délier le contact', c_unlink_confirm: 'Délier « {u} » de ce compte ?',
    a_label: 'Libellé', a_type: 'Type', a_name: 'Nom', a_address: 'Adresse', a_phone: 'Téléphone', a_empty: 'Aucune adresse',
    ad_add: 'Ajouter une adresse', ad_new_title: 'Nouvelle adresse', ad_empty: 'Aucune adresse',
    ad_name: "Nom de l'adresse", ad_type: "Type d'adresse", ad_civility: 'Civilité', ad_civ_ph: '— Civilité —',
    ad_firstname: 'Prénom', ad_lastname: 'Nom', ad_middlename: 'Deuxième prénom',
    ad_num: 'N° de rue', ad_street: 'Rue', ad_building: 'Bâtiment', ad_zip: 'Code postal', ad_city: 'Ville',
    ad_state: 'État/Région', ad_country: 'Pays', ad_phone: 'Mobile',
    ad_err_name: "Le nom de l'adresse est obligatoire.",
    ad_del_title: "Supprimer l'adresse", ad_del_confirm: 'Supprimer « {u} » ?',
    o_ref: 'Référence', o_status: 'Statut', o_date: 'Date', o_empty: 'Aucune commande',
    o_status_label: 'Statut', o_status_all: 'Non sélectionné', o_date_label: 'Date',
    fi_name: 'Fichier', fi_type: 'Type', fi_empty: 'Aucun fichier joint', yes: 'Oui',
    fi_section: 'Pièces jointes', fi_add: 'Ajouter un fichier', fi_uploading: 'Envoi…',
    fi_del_title: 'Supprimer le fichier', fi_del_confirm: 'Supprimer « {u} » ?',
    fi_modal_title: 'Fichier', fi_modal_desc: 'Joindre un fichier à ce compte.', fi_select: 'Choisir un fichier',
    fi_modal_name: 'Nom', fi_country: 'Pays', fi_choose: '— Choisir —',
    fi_err_file: 'Veuillez choisir un fichier.', fi_err_type: 'Le type est obligatoire.', fi_err_country: 'Le pays est obligatoire.',
    fi_all_country: 'Tous les pays', fi_add_type: 'Ajouter un type de fichier', fi_type_code: 'Code du type', fi_type_name: 'Nom du type',
    fi_type_add: 'Ajouter', fi_err_type_fields: 'Code et nom du type obligatoires.',
    ph_search_contact: 'Rechercher un contact…', ph_search_address: 'Rechercher une adresse…',
    ph_search_order: 'Rechercher une commande…', ph_search_file: 'Rechercher un fichier…',
    imp_btn: 'Importer', imp_title: 'Importer',
    imp_desc1: 'Vous pouvez importer ici une liste de comptes.',
    imp_desc2: "Ci-dessous est un extrait complet de fichier CSV correspondant au format requis que vous pouvez utiliser pour préparer votre import.",
    imp_desc3: "Le fichier CSV regroupe chaque section d'un compte dans cet ordre :",
    imp_sections: 'Propriétés, Adresse, Société, Contact',
    imp_required: 'Les champs obligatoires sont les suivants : Nom du compte, pays du compte et le contact à lier au compte.',
    imp_download: 'Télécharger le fichier CSV modèle', imp_choose_file: 'Choisir le fichier',
    imp_err_file: 'Veuillez choisir un fichier CSV.', imp_err_not_csv: 'Le fichier doit être au format CSV.',
    imp_test: 'Tester le fichier', imp_import: 'Importer', imp_close: 'Annuler',
    imp_test_ok: 'Le fichier est valide, vous pouvez lancer l’import.', imp_test_ko: 'Le fichier contient des erreurs.',
    imp_import_ok: 'Import réussi.', imp_import_ko: "L'import a échoué.",
  },
  en: {
    title: 'Accounts', subtitle: 'MelisCommerce customer accounts',
    new: 'New account', search: 'Search an account…', empty: 'No account found', filter_group: 'All groups',
    count: '{n} accounts — end of list',
    col_id: 'ID', col_name: 'Name', col_status: 'Status', col_group: 'Group', col_country: 'Country', col_created: 'Created',
    exp_title: 'Export accounts', exp_subtitle: '{n} accounts will be exported', exp_filename: 'accounts',
    del_title: 'Delete account', del_confirm: 'Delete “{u}”? This action is irreversible.',
    new_title: 'New account', edit_title: 'Edit account',
    f_identity: 'Identity', f_options: 'Options',
    f_name: 'Name', f_name_ph: 'Account name', f_tags: 'Tags', f_tags_ph: 'Comma-separated tags',
    f_country: 'Country', f_country_ph: '— Choose a country —', f_group: 'Group', f_group_none: '— No group —',
    f_active: 'Active', f_active_hint: 'The account is active and usable.',
    err_name: 'Name is required.', err_country: 'Country is required.', err_save: 'Error while saving',
    err_required_fields: 'Please check the required fields.',
    tab_properties: 'Properties', tab_contacts: 'Contacts', tab_company: 'Company', tab_addresses: 'Addresses', tab_orders: 'Orders', tab_files: 'Files',
    save_first: 'Save the account to access this tab.',
    co_name: 'Company name', co_number: 'Registration no.', co_vat: 'VAT number', co_group: 'Group', co_employees: 'Employees',
    co_address: 'Address', co_street: 'Street', co_zip: 'Zip code', co_city: 'City', co_state: 'State/Region', co_country: 'Country',
    co_phone: 'Phone', co_website: 'Website', co_section_id: 'Company identity', co_section_addr: 'Company address',
    c_firstname: 'First name', c_name: 'Name', c_email: 'Email', c_civility: 'Civility', c_empty: 'No linked contact',
    c_def_contact: 'Default contact', c_def_account: 'Default account',
    c_link_ph: 'Contact name', c_link: 'Link contact', c_add: 'Add contact',
    c_unlink_title: 'Unlink contact', c_unlink_confirm: 'Unlink “{u}” from this account?',
    a_label: 'Label', a_type: 'Type', a_name: 'Name', a_address: 'Address', a_phone: 'Phone', a_empty: 'No address',
    ad_add: 'Add address', ad_new_title: 'New address', ad_empty: 'No address',
    ad_name: 'Address name', ad_type: 'Address type', ad_civility: 'Civility', ad_civ_ph: '— Civility —',
    ad_firstname: 'First name', ad_lastname: 'Last name', ad_middlename: 'Middle name',
    ad_num: 'Street number', ad_street: 'Street name', ad_building: 'Building', ad_zip: 'Zip code', ad_city: 'City',
    ad_state: 'State/Region', ad_country: 'Country', ad_phone: 'Mobile',
    ad_err_name: 'Address name is required.',
    ad_del_title: 'Delete address', ad_del_confirm: 'Delete “{u}”?',
    o_ref: 'Reference', o_status: 'Status', o_date: 'Date', o_empty: 'No order',
    o_status_label: 'Status', o_status_all: 'Not selected', o_date_label: 'Date',
    fi_name: 'File', fi_type: 'Type', fi_empty: 'No attached file', yes: 'Yes',
    fi_section: 'File Attachments', fi_add: 'Add file', fi_uploading: 'Uploading…',
    fi_del_title: 'Delete file', fi_del_confirm: 'Delete “{u}”?',
    fi_modal_title: 'File', fi_modal_desc: 'Attach a file to this account.', fi_select: 'Select file',
    fi_modal_name: 'Name', fi_country: 'Country', fi_choose: '— Choose —',
    fi_err_file: 'Please select a file.', fi_err_type: 'Type is required.', fi_err_country: 'Country is required.',
    fi_all_country: 'All countries', fi_add_type: 'Add a file type', fi_type_code: 'Type code', fi_type_name: 'Type name',
    fi_type_add: 'Add', fi_err_type_fields: 'Type code and name are required.',
    ph_search_contact: 'Search a contact…', ph_search_address: 'Search an address…',
    ph_search_order: 'Search an order…', ph_search_file: 'Search a file…',
    imp_btn: 'Import', imp_title: 'Import',
    imp_desc1: 'You can import a list of accounts here.',
    imp_desc2: 'Below is a full sample CSV file matching the required format, which you can use to prepare your import.',
    imp_desc3: 'The CSV file groups each section of an account in this order:',
    imp_sections: 'Properties, Address, Company, Contact',
    imp_required: 'The required fields are: account name, account country, and the contact to link to the account.',
    imp_download: 'Download the sample CSV file', imp_choose_file: 'Choose file',
    imp_err_file: 'Please select a CSV file.', imp_err_not_csv: 'The file must be a CSV file.',
    imp_test: 'Test the file', imp_import: 'Import', imp_close: 'Cancel',
    imp_test_ok: 'The file is valid, you can start the import.', imp_test_ko: 'The file contains errors.',
    imp_import_ok: 'Import successful.', imp_import_ko: 'The import failed.',
  },
})
