import { mergeDict } from '../../shared/i18n'

/** Dictionnaire de l'outil Produits (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Produits', subtitle: 'Produits du catalogue MelisCommerce',
    new: 'Nouveau produit', search: 'Rechercher un produit…', empty: 'Aucun produit trouvé',
    count: '{n} produits — fin de la liste',
    col_id: 'ID', col_status: 'Statut', col_image: 'Image', col_reference: 'Référence', col_name: 'Nom', col_categories: 'Catégories', col_created: 'Créé le',
    exp_title: 'Exporter les produits', exp_subtitle: '{n} produits seront exportés', exp_filename: 'produits',
    del_title: 'Supprimer le produit', del_confirm: 'Supprimer « {u} » ? Cette action est irréversible.',
    new_title: 'Nouveau produit', edit_title: 'Modifier le produit',
    filter_category: 'Toutes les catégories',
    tt_country: 'Pays', tt_price: 'Prix', tt_stocks: 'Stocks',
    status_label: 'Statut', online: 'Actif', offline: 'Inactif',
    tab_main: 'Propriétés', tab_text: 'Textes', tab_variants: 'Variantes', tab_seo: 'SEO', tab_prices: 'Prix',
    sec_general: 'Référence', sec_categories: 'Catégories',
    var_add: 'Ajouter une variante', var_edit: 'Modifier la variante', var_new: 'Nouvelle variante', var_duplicate: 'Dupliquer',
    dup_var_title: 'Dupliquer la variante', dup_prd_title: 'Dupliquer le produit',
    dup_var_intro: 'Renseignez les informations suivantes pour dupliquer la variante sélectionnée.',
    dup_prd_intro: 'Renseignez les informations suivantes pour dupliquer le produit sélectionné.',
    dup_images: 'Dupliquer les images', dup_documents: 'Dupliquer les documents', dup_online: 'Mettre en ligne',
    dup_sku: 'SKU', dup_sku_ph: 'SKU de la nouvelle variante (optionnel)', dup_ref: 'Référence', dup_ref_ph: 'Référence du nouveau produit (optionnel)',
    var_sku: 'SKU', var_sku_ph: 'SKU de la variante', var_main_label: 'Variante principale', var_active: 'Active',
    var_err_sku: 'Le SKU est obligatoire.', var_del_confirm: 'Supprimer la variante « {u} » ?',
    price_add: 'Ajouter un prix', price_edit: 'Modifier le prix', price_empty: 'Aucun prix.',
    price_country: 'Pays', price_currency: 'Devise', price_net: 'Prix HT', price_gross: 'Prix TTC', price_vat: 'TVA %',
    price_country_ph: '— Tous les pays —', price_currency_ph: '— Devise —', price_del_confirm: 'Supprimer ce prix ?',
    save_first_prices: 'Enregistrez d’abord le produit pour gérer les prix.',
    f_reference: 'Référence', f_reference_ph: 'Référence produit (SKU)',
    f_stock: 'Seuil de stock bas', f_stock_ph: 'Ex. 5',
    f_no_category: 'Aucune catégorie disponible.', f_categories_hint: 'Sélectionnez une ou plusieurs catégories.',
    cat_see_all: 'Voir toutes les catégories', cat_none_selected: 'Aucune catégorie sélectionnée.',
    cat_modal_title: 'Liste des catégories', cat_modal_subtitle: 'Sélectionnez les catégories à associer à ce produit',
    clear: 'Effacer', collapse_all: 'Tout réduire', expand_all: 'Tout déplier',
    sec_files: 'Fichiers joints', sec_attributes: 'Attributs', sec_images: 'Images',
    files_empty: 'Aucun fichier joint', attr_empty: 'Aucun attribut', img_empty: 'Aucune image',
    attr_add_ph: '— Ajouter un attribut —', attr_add: 'Ajouter', file_add: '+ Ajouter un fichier', img_add: '+ Ajouter une image',
    modal_add_image: 'Image', modal_add_file: 'Fichier',
    modal_text_prod_image: 'Joindre une image à ce produit.', modal_text_prod_file: 'Joindre un fichier à ce produit (ex : manuel utilisateur).',
    modal_select_image: 'Sélectionner une image', modal_select_file: 'Sélectionner un fichier',
    modal_doc_name: 'Nom', modal_doc_type: 'Type *', modal_doc_country: 'Pays *',
    modal_choose: 'Choisir', modal_all_countries: 'Tous les pays',
    modal_add_img_type: 'Ajouter un type d\'image', modal_add_file_type: 'Ajouter un type de fichier',
    modal_type_code: 'Code du type *', modal_type_name: 'Nom du type *',
    modal_type_add_btn: '+ Ajouter', modal_saving: '…', modal_save: 'Enregistrer', modal_close: 'Fermer',
    img_view: 'Voir', img_edit: 'Modifier', img_del: 'Supprimer', img_del_confirm: 'Supprimer cette image ?',
    file_edit: 'Modifier',
    media_upload_old: 'L’ajout de fichiers/images se fait dans la vue « Old » (gestionnaire de médias).',
    attr_del_confirm: 'Retirer l’attribut « {u} » ?',
    cat_search: 'Rechercher un catalogue / une catégorie…',
    sec_alert: 'Alerte', f_stock_alert: 'Alerte de stock', sec_recipients: 'Destinataires',
    recip_add_ph: '— Destinataires —', recip_add: 'Ajouter un destinataire', recip_empty: 'Aucun destinataire sélectionné',
    recip_del_confirm: 'Retirer « {u} » des destinataires ?',
    recip_email_ph: 'Adresse email…', recip_email_add: 'Ajouter cette adresse', err_invalid_email: 'Adresse email invalide.',
    sec_page_assoc: 'Association de page', f_assoc_page: 'Page associée {n}', f_assoc_page_ph: 'ID de la page',
    sitetree_title: 'Arbre du site', sitetree_insert: 'Insérer', sitetree_pick: 'Choisir une page', sitetree_search: 'Rechercher…',
    tip_reference: "Référence du produit. Celle-ci fait office de nom si aucun titre n’est saisi dans l’onglet « Texte ».",
    tip_stock_alert: "Sélectionnez un ou plusieurs destinataire(s) et définissez le stock pour chaque variant de ce produit à partir duquel un email d’alerte est envoyé.",
    tip_sku: "Code unique d’identification.",
    tip_price_net: "Prix toutes taxes comprises (Le prix TTC sera appliqué à tous les variants de ce produit à condition qu’ils n’aient pas de prix TTC défini depuis leurs paramètres individuels).",
    tip_price_gross: "Prix hors taxes (Le prix HT sera appliqué à tous les variants de ce produit à condition qu’ils n’aient pas de prix HT défini depuis leurs paramètres individuels).",
    tip_price_vat: "Taux de la taxe sur la valeur ajoutée, ne pas saisir le signe « % » (Le taux de TVA sera appliqué à tous les variants de ce produit à condition qu’ils n’aient pas de taux de TVA défini depuis leurs paramètres individuels).",
    tip_price_vat_amount: "Montant en valeur de la taxe sur la valeur ajoutée (Le montant de TVA sera appliqué à tous les variants de ce produit à condition qu’ils n’aient pas de prix TTC défini depuis leurs paramètres individuels).",
    tip_price_other_tax: "Montant de toute taxe additionnelle (Le montant autre taxe sera appliqué à tous les variants de ce produit à condition qu’ils n’aient pas de montant autre taxe défini depuis leurs paramètres individuels).",
    tip_stock_qty: "Quantité de ce variant disponible.",
    tip_stock_next: "Date à laquelle sera réapprovisionné le stock.",
    tip_prd_seo_page_id: "Identifiant de la page correspondant à ce produit.",
    tip_prd_seo_meta_title: "Titre meta de la page correspondant à ce produit.",
    tip_prd_seo_meta_desc: "Description meta de la page correspondant à ce produit.",
    tip_prd_seo_url: "URL de la page correspondant à ce produit.",
    tip_prd_seo_url_redirect: "Redirection URL de la page si ce produit est actif. Pour une page interne, entrez son URL avec son ID (ex : /nompage/id/1), pour une page externe, entrez son URL complète avec http://",
    tip_prd_seo_url_301: "Redirection URL de la page si ce produit est inactif. Pour une page interne, entrez son URL avec son ID (ex : /nompage/id/1), pour une page externe, entrez son URL complète avec http://",
    tip_var_seo_page_id: "Identifiant de la page correspondant à ce variant.",
    tip_var_seo_meta_title: "Titre meta de la page correspondant à ce variant.",
    tip_var_seo_meta_desc: "Description meta de la page correspondant à ce variant.",
    tip_var_seo_url: "URL de la page correspondant à ce variant.",
    tip_var_seo_url_redirect: "Redirection URL de la page si ce variant est actif. Pour une page interne, entrez son URL avec son ID (ex : /nompage/id/1), pour une page externe, entrez son URL complète avec http://",
    tip_var_seo_url_301: "Redirection URL de la page si ce variant est inactif. Pour une page interne, entrez son URL avec son ID (ex : /nompage/id/1), pour une page externe, entrez son URL complète avec http://",
    f_name: 'Nom', f_name_ph: 'Nom du produit', f_description: 'Description', f_description_ph: 'Description du produit',
    seo_url: 'URL', seo_meta_title: 'Titre meta', seo_meta_desc: 'Description meta',
    seo_url_ph: 'url-du-produit', seo_meta_title_ph: 'Titre pour les moteurs', seo_meta_desc_ph: 'Description pour les moteurs',
    var_title: 'Variantes', var_empty: 'Aucune variante.', var_col_id: 'ID', var_col_sku: 'SKU', var_col_main: 'Principale', var_col_status: 'Statut', var_col_attrs: 'Attribut(s)', var_toggle_status: 'Changer le statut',
    var_legacy_hint: 'L’édition des variantes se fait dans la vue « Old » (legacy).',
    var_tab_stocks: 'Stocks', var_tab_assoc: 'Association', yes: 'Oui', no: 'Non',
    var_seo_save_hint: 'Le SEO est enregistré avec le bouton « Enregistrer » en haut.',
    var_assoc_old: 'La gestion des variantes associées se fait dans la vue « Old ».',
    stock_add: 'Ajouter un stock', stock_qty: 'Quantité', stock_low: 'Stock bas', stock_empty: 'Aucun stock.',
    var_information: 'Information', var_attr_old: 'Les attributs de variante se gèrent dans la vue « Old ».',
    seo_page_id: 'ID de page', seo_url_redirect: 'Redirection d’URL', seo_url_301: 'URL 301',
    price_general: 'Général', price_general_pricing: 'Tarification générale', price_vat_amount: 'Montant TVA', price_other_tax: 'Autre taxe', price_pending_hint: '{n} tarif(s) en attente — seront sauvegardés à la validation.',
    stock_general: 'Stocks généraux', stock_next: 'Date de réapprovisionnement',
    assoc_product: 'Nom du produit', assoc_empty: 'Aucune variante associée.', assoc_variants: 'Variantes', assoc_add: 'Associer',
    err_reference: 'La référence est obligatoire.', err_name: 'Un nom de produit est obligatoire (au moins une langue).', err_save: 'Erreur lors de la sauvegarde',
    field_required: 'Ce champ est obligatoire.',
    save_first_tab: 'Enregistrez d’abord pour gérer cet onglet.',
  },
  en: {
    title: 'Products', subtitle: 'MelisCommerce catalog products',
    new: 'New product', search: 'Search a product…', empty: 'No product found',
    count: '{n} products — end of list',
    col_id: 'ID', col_status: 'Status', col_image: 'Image', col_reference: 'Reference', col_name: 'Name', col_categories: 'Categories', col_created: 'Created',
    exp_title: 'Export products', exp_subtitle: '{n} products will be exported', exp_filename: 'products',
    del_title: 'Delete product', del_confirm: 'Delete “{u}”? This action is irreversible.',
    new_title: 'New product', edit_title: 'Edit product',
    filter_category: 'All categories',
    tt_country: 'Country', tt_price: 'Price', tt_stocks: 'Stocks',
    status_label: 'Status', online: 'Active', offline: 'Inactive',
    tab_main: 'Properties', tab_text: 'Text', tab_variants: 'Variants', tab_seo: 'SEO', tab_prices: 'Prices',
    sec_general: 'Reference', sec_categories: 'Categories',
    var_add: 'Add variant', var_edit: 'Edit variant', var_new: 'New variant', var_duplicate: 'Duplicate',
    dup_var_title: 'Duplicate variant', dup_prd_title: 'Duplicate product',
    dup_var_intro: 'Fill the following information in order to duplicate the selected variant.',
    dup_prd_intro: 'Fill the following information in order to duplicate the selected product.',
    dup_images: 'Duplicate images', dup_documents: 'Duplicate documents', dup_online: 'Put online',
    dup_sku: 'SKU', dup_sku_ph: 'New variant SKU (optional)', dup_ref: 'Reference', dup_ref_ph: 'New product reference (optional)',
    var_sku: 'SKU', var_sku_ph: 'Variant SKU', var_main_label: 'Main variant', var_active: 'Active',
    var_err_sku: 'SKU is required.', var_del_confirm: 'Delete variant “{u}”?',
    price_add: 'Add price', price_edit: 'Edit price', price_empty: 'No price.',
    price_country: 'Country', price_currency: 'Currency', price_net: 'Net price', price_gross: 'Gross price', price_vat: 'VAT %',
    price_country_ph: '— All countries —', price_currency_ph: '— Currency —', price_del_confirm: 'Delete this price?',
    save_first_prices: 'Save the product first to manage prices.',
    f_reference: 'Reference', f_reference_ph: 'Product reference (SKU)',
    f_stock: 'Low stock threshold', f_stock_ph: 'e.g. 5',
    f_no_category: 'No category available.', f_categories_hint: 'Select one or more categories.',
    cat_see_all: 'See all categories', cat_none_selected: 'No category selected.',
    cat_modal_title: 'List of categories', cat_modal_subtitle: 'Select the categories to be associated to this product',
    clear: 'Clear', collapse_all: 'Collapse all', expand_all: 'Expand all',
    sec_files: 'File Attachments', sec_attributes: 'Attributes', sec_images: 'Images',
    files_empty: 'No attached file', attr_empty: 'No attribute', img_empty: 'No image',
    attr_add_ph: '— Add attribute —', attr_add: 'Add', file_add: '+ Add file', img_add: '+ Add image',
    modal_add_image: 'Image', modal_add_file: 'File',
    modal_text_prod_image: 'Attach an image to this product.', modal_text_prod_file: 'Attach a file to this product (ex: user manual).',
    modal_select_image: 'Select image', modal_select_file: 'Select file',
    modal_doc_name: 'Name', modal_doc_type: 'Type *', modal_doc_country: 'Country *',
    modal_choose: 'Choose', modal_all_countries: 'All countries',
    modal_add_img_type: 'Add an image type', modal_add_file_type: 'Add a file type',
    modal_type_code: 'Type code *', modal_type_name: 'Type name *',
    modal_type_add_btn: '+ Add', modal_saving: '…', modal_save: 'Save', modal_close: 'Close',
    img_view: 'View', img_edit: 'Edit', img_del: 'Delete', img_del_confirm: 'Delete this image?',
    file_edit: 'Edit',
    media_upload_old: 'Adding files/images is done in the “Old” view (media manager).',
    attr_del_confirm: 'Remove attribute “{u}”?',
    cat_search: 'Search a catalog / category…',
    sec_alert: 'Alert', f_stock_alert: 'Stock alert', sec_recipients: 'Recipients',
    recip_add_ph: '— Recipients —', recip_add: 'Add recipient', recip_empty: 'No recipients selected',
    recip_del_confirm: 'Remove “{u}” from recipients?',
    recip_email_ph: 'Email address…', recip_email_add: 'Add this address', err_invalid_email: 'Invalid email address.',
    sec_page_assoc: 'Page association', f_assoc_page: 'Associated page {n}', f_assoc_page_ph: 'Page ID',
    sitetree_title: 'Site tree view', sitetree_insert: 'Insert', sitetree_pick: 'Pick a page', sitetree_search: 'Search…',
    tip_reference: 'Product reference. It becomes the name if no title is entered in the "Text" tab.',
    tip_stock_alert: 'Select one or more recipient(s) and define the stock for each variant of this product from which an alert email is sent.',
    tip_assoc_page: 'Either type in the ID of the page to associate or select the page in the treeview. For an external page just type in the URL of the page.',
    tip_sku: 'Unique code of identification.',
    tip_price_net: 'Price including all taxes (The net price will be applied to all the variants of this product provided that they don\'t have a net price already defined in their individual parameters).',
    tip_price_gross: 'Price without taxes (The gross price will be applied to all the variants of this product provided that they don\'t have a gross price already defined in their individual parameters).',
    tip_price_vat: 'Rate of the value added tax, do not enter the sign "%" (The VAT rate will be applied to all the variants of this product provided that they don\'t have a VAT rate already defined in their individual parameters).',
    tip_price_vat_amount: 'Value amount of the value added tax (The VAT amount will be applied to all the variants of this product provided that they don\'t have a VAT rate already defined in their individual parameters).',
    tip_price_other_tax: 'Amount of any additional tax (The other tax amount will be applied to all the variants of this product provided that they don\'t have an other tax amount already defined in their individual parameters).',
    tip_stock_qty: 'Available quantity of this variant.',
    tip_stock_next: 'Replenishment date of the stock.',
    tip_prd_seo_page_id: "Identifier of the page corresponding to this product.",
    tip_prd_seo_meta_title: "Meta title of the page corresponding to this product.",
    tip_prd_seo_meta_desc: "Meta description of the page corresponding to this product.",
    tip_prd_seo_url: "URL of the page corresponding to this product.",
    tip_prd_seo_url_redirect: "URL redirection of the page if this product is active. For an internal page enter its URL with its ID (ex: /mypagename/id/1), for an external page enter its complete URL with the http://",
    tip_prd_seo_url_301: "URL redirection of the page if this product is inactive. For an internal page enter its URL with its ID (ex: /mypagename/id/1), for an external page enter its complete URL with the http://",
    tip_var_seo_page_id: "Identifier of the page corresponding to this variant.",
    tip_var_seo_meta_title: "Meta title of the page corresponding to this variant.",
    tip_var_seo_meta_desc: "Meta description of the page corresponding to this variant.",
    tip_var_seo_url: "URL of the page corresponding to this variant.",
    tip_var_seo_url_redirect: "URL redirection of the page if this variant is active. For an internal page enter its URL with its ID (ex: /mypagename/id/1), for an external page enter its complete URL with the http://",
    tip_var_seo_url_301: "URL redirection of the page if this variant is inactive. For an internal page enter its URL with its ID (ex: /mypagename/id/1), for an external page enter its complete URL with the http://",
    f_name: 'Name', f_name_ph: 'Product name', f_description: 'Description', f_description_ph: 'Product description',
    seo_url: 'URL', seo_meta_title: 'Meta title', seo_meta_desc: 'Meta description',
    seo_url_ph: 'product-url', seo_meta_title_ph: 'Title for search engines', seo_meta_desc_ph: 'Description for search engines',
    var_title: 'Variants', var_empty: 'No variant.', var_col_id: 'ID', var_col_sku: 'SKU', var_col_main: 'Main', var_col_status: 'Status', var_col_attrs: 'Attribute(s)', var_toggle_status: 'Toggle status',
    var_legacy_hint: 'Variant editing is done in the “Old” (legacy) view.',
    var_tab_stocks: 'Stocks', var_tab_assoc: 'Association', yes: 'Yes', no: 'No',
    var_seo_save_hint: 'SEO is saved with the “Save” button at the top.',
    var_assoc_old: 'Associated-variants management is done in the “Old” view.',
    stock_add: 'Add stock', stock_qty: 'Quantity', stock_low: 'Low stock', stock_empty: 'No stock.',
    var_information: 'Information', var_attr_old: 'Variant attributes are managed in the “Old” view.',
    seo_page_id: 'Page ID', seo_url_redirect: 'URL redirection', seo_url_301: 'URL 301',
    price_general: 'General', price_general_pricing: 'General Pricing', price_vat_amount: 'VAT amount', price_other_tax: 'Other tax amount', price_pending_hint: '{n} price(s) pending — will be saved on main Save.',
    stock_general: 'General Stocks', stock_next: 'Replenishment date',
    assoc_product: 'Product name', assoc_empty: 'No associated variant.', assoc_variants: 'Variants', assoc_add: 'Associate',
    err_reference: 'Reference is required.', err_name: 'A product name is required (at least one language).', err_save: 'Error while saving',
    field_required: 'This field is required.',
    save_first_tab: 'Save first to manage this tab.',
  },
})
