<?php if($this->isAccessable) { ?>
    <?php
        $activeFilter = $this->pluginConfig['datas']['activeFilter'];    
    ?>
    <div class="row row-merge">
        <div class="col-sm-12 bg-white">
            <div class="innerAll">
                <div class="tab-content">
                    <div id="chart-simple-lines-<?php echo $this->pluginConfig['plugin_id']?>" class="tab-pane active commerce-dashboard-plugin-sales-revenue-button-header">
                        <div class="btn-group float-right" data-bs-toggle="buttons" role="group">
                            <input type="radio" class="commerce-dashboard-plugin-sales-revenue btn-check" id="commerce-dashboard-plugin-sales-revenue-hourly" name="commerce-dashboard-plugin-sales-revenue" value="hourly" autocomplete="off" checked>
                            <!-- active = focus to remove css on active -->
                            <label class="btn btn-default btn-sm <?= ($activeFilter == 'hourly') ? 'focus' : '' ?>" for="commerce-dashboard-plugin-sales-revenue-hourly"><?php echo $this->translate('tr_melis_commerce_orders_dashboard_statistics_hourly')?></label>
                            
                            <input type="radio" class="commerce-dashboard-plugin-sales-revenue btn-check" id="commerce-dashboard-plugin-sales-revenue-daily" name="commerce-dashboard-plugin-sales-revenue" value="daily" autocomplete="off">
                            <label class="btn btn-default btn-sm <?= ($activeFilter == 'daily') ? 'focus' : '' ?>" for="commerce-dashboard-plugin-sales-revenue-daily"><?php echo $this->translate('tr_melis_commerce_orders_dashboard_statistics_daily')?></label>

                            <input type="radio" class="commerce-dashboard-plugin-sales-revenue btn-check" id="commerce-dashboard-plugin-sales-revenue-weekly" name="commerce-dashboard-plugin-sales-revenue" value="weekly" autocomplete="off">
                            <label class="btn btn-default btn-sm <?= ($activeFilter == 'weekly') ? 'focus' : '' ?>" for="commerce-dashboard-plugin-sales-revenue-weekly"><?php echo $this->translate('tr_melis_commerce_orders_dashboard_statistics_weekly')?></label>

                            <input type="radio" class="commerce-dashboard-plugin-sales-revenue btn-check" id="commerce-dashboard-plugin-sales-revenue-monthly" name="commerce-dashboard-plugin-sales-revenue" value="monthly" autocomplete="off">
                            <label class="btn btn-default btn-sm <?= ($activeFilter == 'monthly') ? 'focus' : '' ?>" for="commerce-dashboard-plugin-sales-revenue-monthly"><?php echo $this->translate('tr_melis_commerce_orders_dashboard_statistics_monthly')?></label>
                        </div>
                        <div class="separator bottom"></div>
                        <div class="flotchart-holder commerce-dashboard-plugin-sales-revenue-placeholder" id="commerce-dashboard-plugin-sales-revenue-placeholder-<?php echo $this->pluginConfig['plugin_id']?>" data-activefilter="<?= $activeFilter ?>"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } else { ?>
    <div class="no-rights-container">
        <span><?= $this->translate('tr_melisdashboardplugin_plugin_no_rights'); ?></span>
    </div>
<?php } ?>
