<?php if($this->isAccessable) { ?>
    <div class="melis-commerce-dashboard-plugin-order-messages-parent">
        <!-- <div class="row"> -->
            <div class="innerAll border-bottom commerce-dashboard-plugin-messages-head clearfix">
                <div id="melis-commerce-dashboard-plugin-order-messages-placeholder-" class="btn-group" data-bs-toggle="buttons" class="pull-left" role="group">
                    <!-- active -->
                    <input type="radio" class="commerce-dashboard-plugin-order-messages btn-check" id="commerce-dashboard-plugin-order-messages-all" name="commerce-dashboard-plugin-order-messages" value="all" autocomplete="off" checked>
                    <label class="btn btn-default btn-sm" for="commerce-dashboard-plugin-order-messages-all"><?php echo $this->translate('tr_melis_commerce_dashboard_plugin_order_messages_all')?></label>
                    
                    <input type="radio" class="commerce-dashboard-plugin-order-messages btn-check" id="commerce-dashboard-plugin-order-messages-unseen" name="commerce-dashboard-plugin-order-messages" value="unseen" autocomplete="off">
                    <label class="btn btn-default btn-sm" for="commerce-dashboard-plugin-order-messages-unseen"><?php echo $this->translate('tr_melis_commerce_dashboard_plugin_order_messages_unanswered')?></label>
                </div>
                <div class="message-count float-right" id="message-count-<?php echo $this->pluginConfig['plugin_id']?>"></div>
            </div>
        <!-- </div> -->

        <div class="col-table-row">
            <div class="col-app col-unscrollable">
                <div class="col-app">
                    <div id="melis-commerce-dashboard-plugin-order-messages-placeholder-<?php echo $this->pluginConfig['plugin_id']?>" class="list-group email-item-list commerce-dashboard-plugin-order-messages-list" style="margin-bottom: 0px;">

                    </div>
                    <!-- // END list-group -->
                </div>
                <!-- // END col-app -->
            </div>
            <!-- // END col-app -->
        </div>
    </div>
<?php } else { ?>
    <div class="no-rights-container">
        <span><?= $this->translate('tr_melisdashboardplugin_plugin_no_rights'); ?></span>
    </div>
<?php } ?>