<?php
	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = $this->zoneconfig['conf']['id'];
	$data_melisKey = $this->melisKey;

?>
<div class="modal-content" id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons comments" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->title ?></a></li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" id="<?php echo $id ?>">
                        <?php 
                            $form = $this->form;
                            $form->prepare();
                            $form->setData($this->data);
                            echo $this->form()->openTag($form);
                            echo $this->melisFieldCollection($form);
                            echo $this->form()->closeTag();
                        ?>
                        <button class="btn btn-success pull-right" id="btnComSaveLang"><i class="fa fa-save"></i> <?= $this->translate('tr_meliscommerce_general_common_save'); ?></button>
                        <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
