<?php
	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = $this->zoneconfig['conf']['id'];
	$data_melisKey = $this->melisKey;
$imageData = '';
?>
<div class="modal-content" id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="nav-item active">
							<a data-bs-target="#<?php echo $this->zoneconfig['conf']['id'] ?>" href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons <?php echo ($this->id) ? 'pencil' : 'plus'?>" data-bs-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->title ?></a>
						</li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" id="<?php echo $id ?>">
        				<p><?= $this->translate('tr_meliscommerce_language_modal_description')?></p>
                        <?php 
                            $form = $this->form;
                            $form->setAttribute('data-savetype', $this->saveType);
                            $form->prepare();
                            $form->setData($this->data);
							$langStatus = '';
							if(isset($this->data['elang_status'])) {
								$langStatus = (int) $this->data['elang_status'] ? 'checked="checked"' : '';
							}
                            if($this->data) {
                                $form->get('tmp_elang_name')->setValue($this->data['elang_name']);
                                $form->get('tmp_elang_locale')->setValue($this->data['elang_locale']);
                            }
                            echo $this->form()->openTag($form);
						?>
						<div class="float-left">
							<?php
							if(isset($this->data['elang_flag'])) {
								$imageData = 'data:image/jpeg;base64,'.$this->data['elang_flag'];
							}
							?>

							<img src="<?php echo $imageData; ?>" class="imgFlag" id="imgLangFlag" style="border:none"/>
						</div>
						<div class="float-right">
							<div <?= $id; ?> class="make-switch" data-on-label="<?php echo $this->translate('tr_meliscommerce_products_page_content_tab_main_header_switch_online')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_products_page_content_tab_main_header_switch_offline')?>" data-text-label="<?php echo $this->translate('tr_meliscommerce_categories_common_label_status')?>">
								<input type="checkbox" name="elang_status" id="elang_status" <?php echo $langStatus; ?>>
							</div>
						</div><div class="clearfix"></div>
						<?php
                            echo $this->melisFieldCollection($form);
                        ?>
                        <div class="footer-modal d-flex flex-row justify-content-between">
                     		<button data-bs-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                     		<button type="submit" class="btn btn-success" id="btnComSaveLang"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscommerce_orders_common_btn_save') ?></button>
                     	</div>
						<?php echo $this->form()->closeTag(); ?>
                        <div class="clearfix"></div>
                        </div>
						<script type="text/javascript">
							$(function() {
								$(":file").filestyle({buttonBefore: true, input: true, buttonText: ' <?php echo $this->translate('tr_meliscommerce_country_ctry_flag_choose')?>'});
							});
						</script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
