<?php 

    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->couponId.'_'.$this->zoneconfig['conf']['id'];
    }       
 
   
?>
<?php 
    $form = $this->couponForm;
    echo $this->form()->openTag($form);
    echo $this->melisFieldCollection($form);
    echo $this->form()->closeTag();
    echo $this->datePickerInit;
?>
<div class="form-group">
	<label class="label-block" for="" style="padding-top: 12px;">Given to</label>
	<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="make-switch main_variant_switch" data-on-label="<?php echo $this->translate('tr_meliscommerce_coupon_page_tabs_yes')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_coupon_page_tabs_no')?>" data-text-label="<i class='fa fa-arrows-h'>">
        <input type="checkbox" name="coup_type" id="coup_type"  <?= $this->type ?>>
    </div>
    <script type="text/javascript">
    	$("#<?= $id ?>").bootstrapSwitch();
    </script>	
</div>