<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->couponId.'_'.$this->zoneconfig['conf']['id'];
    } 
?>
<h1 id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="content-heading"> <?= $this->translate('tr_meliscommerce_coupon_page').' '.$this->escapeHtml($this->couponCode); ?></h1>
<p><?= $this->translate('tr_meliscommerce_coupon_list_page_coupon_description')?></p>