<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])){
    $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
}
$tmp = '';
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="innerAll layout-timeline">
    <div class="row">
        <div class="col-12 col-md-2 layout-timeline-spacer"></div>
        <div class="col-12 col-md-10">
            <ul class="timeline">
                <?php foreach($this->messages as $message):?>
                    <li class="active">
                        <div class="separator bottom">
                            <?php
                            if($message['day'] != $tmp):
                                $tmp = $message['day'];
                                ?>
                                <span class="date box-generic"><strong><?= $message['day'] ?></strong><?= $message['month'] ?></span>
                            <?php endif;?>
                            <div class="separator">
                                <span class="type glyphicons comments"><?= $message['urole_name'] ?> <i></i></span>
                            </div>
                            <span class="type glyphicons comments"><?= $message['urole_name'] ?> <i></i></span>
                        </div>
                        <div class="widget widget-heading-simple widget-body-white margin-none pagecomment">
                            <div class="widget-body">
                                <div class="media">
                                    <div class="media-object float-left"><img width="50" height="50" src="<?= $message['usr_image'] ?>" alt="Image" class="img-circle"></div>
                                    <div class="media-body">
                                        <span class="text-danger"><i class="fa fa-user"></i> <?= $message['name'] ?></span><br>
                                        <span class="muted"><i class="fa fa-envelope"></i> <?= $message['email'] ?></span>
                                        <span class="muted text-small clearfix"><i class="fa fa-clock-o"></i> <?= $message['time'] ?></span>
                                    </div>
                                </div>
                                <div class="alert alert-gray">
                                    <div class="message">
                                        <p><?= $message['omsg_message'] ?></p>
                                    </div>
                                    <div class="msg_details">
                                        <h6>Details:</h6>
                                        <?php foreach($message['details'] as $detail) { ?>
                                        <span><?= $detail['product_name'] .' / '.$detail['product_id'].' / '.$detail['pretd_sku'].': '.$detail['pretd_quantity']; ?></span><br>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
</div>