<div class="me-heading bg-white border-bottom">
    <div class="row">
        <div class="me-hl col-xs-12 col-md-9">
            <h1 class="content-heading"><?= $this->translate('tr_meliscommerce_orders_content_tabs_content_messages_left_header_title');?></h1>
        </div>
        <div class="me-hl col-xs-12 col-md-3">
            <a class="btn btn-success addReturnMessage float-right" title="<?= $this->translate('tr_meliscommerce_orders_content_tabs_content_messages_right_header_add'); ?>">
                <i class="fa fa-plus" style="padding-right:10px;"></i>
                <?= $this->translate('tr_meliscommerce_orders_content_tabs_content_messages_right_header_add'); ?>
            </a>
        </div>
    </div>
</div>