<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])){
    $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
}
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" style="margin-top:50px">
    <?php
    if(!empty($this->zoneconfig['interface'])) {
        foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
            echo $this->$keyConfig;
        }
    }
    ?>
</div>