<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    print '<pre>';
    print_r($this->zoneconfig['interface']);
    print '</pre>';
?>
 
 <div class="tab-pane container-level-a" <?php echo $id.' '.$data_melisKey; ?>> 
	<?php 
	    if(!empty($this->zoneconfig['interface'])) {
	        foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
	            echo $this->$keyConfig;
	        }
	    }
	?>
</div>