<?php
	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = $this->zoneconfig['conf']['id'];
	$data_melisKey = $this->melisKey;

?>
<div class="modal-content" id="<?= $id; ?>" data-melisKey="<?= $data_melisKey; ?>">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons <?php echo ($this->id) ? 'pencil' : 'plus'?>" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->title ?></a></li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" id="<?php echo $id ?>">
        				<p><?= $this->translate('tr_meliscommerce_currency_modal_description')?></p>
                        <?php 
                            $form = $this->form;
                            $form->setAttribute('data-savetype', $this->saveType);
                            $form->prepare();
                            $form->setData($this->data);
                            if($this->data) {
                                $form->get('tmp_cur_code')->setValue($this->data['cur_code']);
                            }
                            echo $this->form()->openTag($form);
							$curStatus = '';
							if(isset($this->data['cur_status'])) {
								$curStatus = (int) $this->data['cur_status'] ? 'checked="checked"' : '';
							}
						?>
						<div class="pull-right">
						<div <?= $id; ?> class="make-switch" data-on-label="<?php echo $this->translate('tr_meliscommerce_products_page_content_tab_main_header_switch_online')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_products_page_content_tab_main_header_switch_offline')?>" data-text-label="<?php echo $this->translate('tr_meliscommerce_categories_common_label_status')?>">
							<input type="checkbox" name="cur_status" id="cur_status" <?php echo $curStatus; ?>>
						</div>
						</div><div class="clearfix"></div>
						<?php
                            echo $this->melisFieldCollection($form);
                            echo $this->form()->closeTag();
                        ?>
                        <div align="right">
                     		<button data-dismiss="modal" class="btn btn-danger pull-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                     		<button class="btn btn-success" id="btnComSaveCurrency"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscommerce_orders_common_btn_save') ?></button>
                     	</div>
                        <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
