<?php if (!$this->success){ ?>
	
	<h3><?=$this->translate('tr_meliscommerce_general_error_occured'); ?>. <small><?= $this->translate('tr_meliscommerce_plugin_checkout_confirm_summary_err_msg'); ?></small></h3>
	
	<?php foreach ($this->errors As $key => $val){ ?>
		<?php if (!empty($val)) {?>
    		<p><strong><?php echo strtoupper($key)?></strong></p>
    		<ul>
    			<?php foreach ($val As $sKey => $sval){ ?>
    				<li><?php echo $sval?></li>
    			<?php } ?>
    		</ul>
    		<br>
		<?php } ?>
	<?php } ?>
	
	<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>"><?= $this->translate('tr_meliscommerce_order_checkout_common_prev'); ?></a>
	
<?php } ?>