<?php if (!$this->success && !empty($this->message)){?>
	<div class="alert alert-danger">
		<p><?php echo $this->message;?></p>
	</div>
<?php }elseif($this->success){?>
	<div class="alert alert-success">
		<p><?php echo $this->message?></p>
	</div>
<?php }?>

<style>
.default-form-err-msg-plugin li{
    display: inherit;
}
</style>
<?php
    $form = $this->couponForm;
	$form->prepare();
	echo $this->form()->openTag($form); 
	
	foreach ($form->getElements() As $key => $val)
	{
	    echo '<div class="form-group">';
	    if ($val->getLabel())
	    {
	        echo $this->formLabel($val);
	    }
	    echo $this->formElement($val);
	    echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
	    echo '</div>';
	}
    
    echo '<button type="submit" class="btn btn-default">'.$this->translate('tr_meliscommerce_general_common_submit').'</button>';
	echo $this->form()->closeTag(); 
?>