<?php if (!$this->checkoutErrorMsg){?>
    <h1>Checkout Summary</h1>
    
    <?php if ($this->checkoutHasErr){?>
    	<div class="alert alert-danger">
    		<h3>Product error(s) occured. <small>Error message appeared under the name of the Product.</small></h3>
    	</div>
    <?php }?>
    
    <table class="table table-bordered">
    	<thead>
    		
    		<tr>
    			<th>Product</th>
    			<th>Quantity</th>
    			<th>Unit Price</th>
    			<th>Discount</th>
    			<th>Sub Total</th>
    		</tr>
    	</thead>
    	<tbody>	
    		<?php 
    		    $totalQty = 0;
    		    foreach ($this->checkoutCart As $val){
    	    ?>
        		<tr>
        			<td>
        				<?php 
        				    echo $val['var_product_name'].' ('.$val['var_sku'].')';
        				    if (!empty($val['var_err']))
        				    {
        				        echo '<div class="text-danger">'.$val['var_err'].'</div>';
        				    }
    				    ?>
    				</td>
        			<td align="right"><?php echo $val['var_quantity']?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].$val['var_price'] ?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].$val['var_discount'] ?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].$val['var_total'] ?></td>
        		</tr>
    		<?php 
    		    $totalQty += $val['var_quantity']; 
    		    }
    	    ?>
    	</tbody>
    	<tfoot>
    		<tr>
    			<th></th>
    			<th style="text-align: right" colspan="2"><?php echo $totalQty?></th>
    			<th style="text-align: right">Sub Total</th>
    			<th style="text-align: right"><?php echo $this->checkoutCartSubTotal?></th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="4">Discount</th>
    			<th style="text-align: right">
    				<?php 
                	    echo $this->checkoutCartDiscount;
                	   
                	    if (!empty($this->checkoutCartDiscountInfo))
                	    {
                	       echo '<div>Coupon Code: '.$this->checkoutCartCouponCode.'</div>';
                	       echo '<div>Coupon Value: '.$this->checkoutCartDiscountInfo.'</div>';
                	    }
                	    
                	    if (!empty($this->checkoutCartCouponErrMsg))
                	    {
                	        echo '<div>'.$this->checkoutCartCouponErrMsg.'</div>';
                	    }
            	    ?>
    			</th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="4">Shipping cost</th>
    			<th style="text-align: right"><?php echo $this->checkoutShipping?></th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="4">Total</th>
    			<th style="text-align: right"><?php echo $this->checkoutCartTotal?></th>
    		</tr>
    		
    	</tfoot>
    </table>

	<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>">Previous</a>
	
    <?php if (!$this->checkoutHasErr){ ?>
    	<a class="btn btn-primary pull-right" href="<?php echo $this->nextStep_link?>">Proceed to Payment</a>
    <?php } ?>

<?php }else{ ?>

	<h1><?php echo $this->checkoutErrorMsg?></h1>
	
	<?php if ($this->prevStep_link) {?>
		<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>">Previous</a>
	<?php } ?>
	
<?php } ?>