<?php if (!$this->checkoutErrorMsg){?>
    <h2><?= $this->translate('tr_meliscommerce_checkout_summary_label'); ?></h2>
    
    <?php if ($this->checkoutHasErr){?>
    	<div class="alert alert-danger">
    		<h3><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_error'); ?> <small><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_error_msg');?></small></h3>
    	</div>
    <?php }?>
    
    <table class="table table-bordered">
    	<thead>
    		
    		<tr>
    			<th><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_product');?></th>
    			<th><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_qty');?></th>
    			<th><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_unit_price');?></th>
    			<th><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_discount');?></th>
    			<th><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_sub_total');?></th>
    		</tr>
    	</thead>
    	<tbody>	
    		<?php 
    		    $totalQty = 0;
    		    foreach ($this->checkoutCart As $val){
    	    ?>
        		<tr>
        			<td>
        				<?php 
        				    echo $val['var_product_name'].' ('.$val['var_sku'].')';
        				    if (!empty($val['var_err']))
        				    {
        				        echo '<div class="text-danger">'.$val['var_err'].'</div>';
        				    }
    				    ?>
    				</td>
        			<td align="right"><?php echo $val['var_quantity']?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].$val['var_price'] ?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].$val['var_discount'] ?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].$val['var_total'] ?></td>
        		</tr>
    		<?php 
    		    $totalQty += $val['var_quantity']; 
    		    }
    	    ?>
    	</tbody>
    	<tfoot>
    		<tr>
    			<th></th>
    			<th style="text-align: right" colspan="2"><?php echo $totalQty?></th>
    			<th style="text-align: right"><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_sub_total');?></th>
    			<th style="text-align: right"><?php echo $this->checkoutCurrency.$this->checkoutCartSubTotal?></th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="4"><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_discount');?></th>
    			<th style="text-align: right">
    				<?php 
                	    echo $this->checkoutCartDiscount;
                	   
                	    if (!empty($this->checkoutCartDiscountInfo))
                	    {
                	       echo '<div>'.$this->translage("tr_meliscommerce_plugin_checkout_coupon_code").': '.$this->checkoutCartCouponCode.'</div>';
                	       echo '<div>'.$this->translage("tr_meliscommerce_plugin_checkout_coupon_value").': '.$this->checkoutCartDiscountInfo.'</div>';
                	    }
                	    
                	    if (!empty($this->checkoutCartCouponErrMsg))
                	    {
                	        echo '<div>'.$this->checkoutCartCouponErrMsg.'</div>';
                	    }
            	    ?>
    			</th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="4"><?= $this->translate('tr_meliscommerce_plugin_checkout_summary_shipping_cost'); ?></th>
    			<th style="text-align: right"><?php echo $this->checkoutCurrency.$this->checkoutShipping?></th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="4"><?= $this->translate('tr_meliscommerce_plugin_checkout_cart_total'); ?></th>
    			<th style="text-align: right"><?php echo $this->checkoutCurrency.$this->checkoutCartTotal?></th>
    		</tr>
    		
    	</tfoot>
    </table>

	<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>"><?= $this->translate('tr_meliscommerce_order_checkout_common_prev'); ?></a>
	
    <?php if (!$this->checkoutHasErr){ ?>
    	<a class="btn btn-primary pull-right" href="<?php echo $this->nextStep_link?>"><?= $this->translate('tr_meliscommerce_order_checkout_summary_next_btn'); ?></a>
    <?php } ?>

<?php }else{ ?>

	<label class="alert alert-danger"><?php echo $this->checkoutErrorMsg?></label>
	
	<?php if ($this->prevStep_link) {?>
		<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>"><?= $this->translate('tr_meliscommerce_order_checkout_common_prev'); ?></a>
	<?php } ?>
	
<?php } ?>