<h1 align="center">Checkout Cart</h1>
<?php if ($this->checkoutHasErr){ ?>
	<h3>Product error(s) occured. <small>Error message appeared under the name of the Product.</small></h3>
<?php } ?>

<form>
	<div class="form-group">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>SKU</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                    foreach($this->checkOutCart as $item)
                    {
                        echo '<tr>';
                        echo    '<td>'.$item['var_sku'];
                        if (!empty($item['var_err']))
                        {
                            echo '<div class="text-danger">'.$item['var_err'].'</div>';
                        }
                        echo    '</td>';
                        echo    '<td class="text-right">'.$item['var_currency_symbol'].' '.$item['var_price'].'</td>';
                        echo    '<td><input type="text" name="m_v_quantity['.$item['var_id'].']" value="'.$item['var_quantity'].'" class="form-control">';
                        echo    (!empty($this->checkoutErrors[$item['var_id']])) ? '<p class="text-danger">'.$this->checkoutErrors[$item['var_id']].'</p>' : '';
                        echo    '</td>';
                        echo    '<td class="text-right">'.$item['var_currency_symbol'].' '.$item['var_total'].'</td>';
                        echo    '<td class="text-right"><a class="btn btn-danger" href="'.$this->MelisLink($this->idPage, true).'?m_v_id_remove='.$item['var_id'].'"><i class="fa fa-trash-o"></i></a></td>';
                        echo '</tr>';
                    }
                ?>                
            </tbody>
        </table>
	</div>
    <?php if (!empty($this->checkOutCart)){?>
        <div align="center">
        	<button class="btn btn-primary">Update Cart</button>
        </div>
    <?php } ?>
</form>
<br>
<form>
	<table class="table table-bordered">
        <tfoot>
        	<tr>
                <th rowspan="4" colspan="3">
                	<?php if (!empty($this->checkOutCart)){ ?>
                		<?php echo $this->checkoutCoupon?>
                	<?php } ?>
                </th>
            </tr>
            <tr>
                <th colspan="1" class="text-right">Sub Total</th>
                <th class="text-right"><?php echo $this->checkOutCartSubTotal ?></th>
            </tr>
            <?php if ($this->checkoutHasCoupon){?>
                <tr>
                    <th colspan="1" class="text-right">Discount</th>
                    <th class="text-right">
                    	<?php 
                            if (!empty($this->checkOutCartDiscountInfo))
                         	{
                         	    echo '<p>Order discount </p>';
                         	    foreach($this->checkOutCartDiscountInfo as $discInfo){
                         	        echo '<p>';
                         	        echo '(-'.$discInfo['details'].')';
                         	        echo '<span>';
                         	        echo $discInfo['amount'];
                                    echo '</span>';
                                    echo '</p>';
                         	    }
                         	}
                     	?>
                	</th>
                </tr>
            <?php }?>
            <tr>
                <th colspan="1" class="text-right">Total</th>
                <th class="text-right"><?php echo $this->checkOutCartTotal ?></th>
            </tr>
        </tfoot>
    </table>
</form>

<?php if ($this->nextStep_link){ ?>
	<div align="right">
		<a class="btn btn-primary" href="<?php echo $this->nextStep_link?>">Next</a>
	</div>
<?php } ?>