<h1 align="center">Checkout Cart</h1>
<?php if ($this->checkoutHasErr):?>
	<h3>Product error(s) occured. <small>Error message appeared under the name of the Product.</small></h3>
<?php endif;?>

<form>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product Name</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
        <?php 
            foreach($this->checkOutCart as $item)
            {
                $productImg = ($item['product_img']) ? '<img src="'.$item['product_img'].'" alt="" style="width: 100px;">' : '';
                echo '<tr>';
                echo    '<td class="text-center">'.$productImg.'</td>';
                echo    '<td>'.$item['product_name'].' ('.$item['var_sku'].')';
                if (!empty($item['var_err']))
                {
                    echo '<div class="text-danger">'.$item['var_err'].'</div>';
                }
                echo    '</td>';
                echo    '<td class="text-right">'.$item['var_currency_symbol'].' '.$item['var_price'].'</td>';
                echo    '<td><input type="text" name="m_v_quantity['.$item['var_id'].']" value="'.$item['var_quantity'].'">';
                echo    (!empty($this->checkoutErrors[$item['var_id']])) ? '<p class="text-danger">'.$this->checkoutErrors[$item['var_id']].'</p>' : '';
                echo    '</td>';
                echo    '<td class="text-right">'.$item['var_currency_symbol'].' '.$item['var_total'].'</td>';
                echo    '<td class="text-right"><a class="btn btn-danger" href="'.$item['var_remove_link'].'">Remove</a></td>';
                echo '</tr>';
            }
        ?>                
        </tbody>
        </table>
    <?php if (!empty($this->checkOutCart)):?>
        <div align="center">
        	<button class="btn btn-primary">Update Cart</button>
        </div>
    <?php endif;?>
</form>
<br>
<form>
	<table class="table table-bordered">
        <tfoot>
        	<tr>
                <th rowspan="4" colspan="3">
                	<?php if (!empty($this->checkOutCart)):?>
                		<?php echo $this->checkoutCoupon?>
                	<?php endif;?>
                </th>
            </tr>
            <tr>
                <th colspan="1" class="text-right">Sub Total</th>
                <th class="text-right"><?php echo $this->checkOutCartSubTotal ?></th>
            </tr>
            <tr>
                <th colspan="1" class="text-right">Discount</th>
                <th class="text-right">
                	<?php 
                	    echo $this->checkOutCartDiscount;
                	   
                	    if (!empty($this->checkOutCartDiscountInfo))
                	    {
                	       echo '<p>Coupon Value '.$this->checkOutCartDiscountInfo.'</p>';
                	    }
            	    ?>
            	</th>
            </tr>
            <tr>
                <th colspan="1" class="text-right">Total</th>
                <th class="text-right"><?php echo $this->checkOutCartTotal ?></th>
            </tr>
        </tfoot>
    </table>
</form>

<?php if ($this->nextStep_link):?>
	<div align="right">
		<a class="btn btn-primary" href="<?php echo $this->nextStep_link?>">Next</a>
	</div>
<?php endif;?>