	<div>
        <?php 
        $total = 0;
         foreach($this->basket as $item):
         $total += $item['price'] * $item['quantity'];
         $currency = $item['cur_symbol'];
        ?>
            <div>
                <img src="<?= $item['image']; ?>" alt="" height="100" width="100">
                <div>
                    <div><?= $item['name']; ?> (<?= $item['var_sku']; ?>)</div>
                    <div><?= $item['cur_symbol'].$item['price']; ?> </div>
                    <div> Qty: <span><?= $item['quantity']; ?></span></div>
                </div>
            </div>
        <?php 
        endforeach;
        echo 'TOTAL:'.$total;
        ?>
	</div>