<?php
    if($this->basket) {
?>
<div class="cart-main-container">
    <div class="cart-data-container">
        <?php
         $total = 0;
         foreach($this->basket as $item) {
             $total += $item['price'] * $item['quantity'];
             $currency = $item['cur_symbol'];
             ?>
             <div class="row">
                 <div class="col-md-5">
                    <img src="<?= $item['image']; ?>" alt="" height="100" width="100">
                 </div>
                 <div class="col-md-5">
                     <div><?= $item['name']; ?> (<?= $item['var_sku']; ?>)</div>
                     <div><?= $item['cur_symbol'] . $item['price']; ?> </div>
                     <div> Qty: <span><?= $item['quantity']; ?></span></div>
                 </div>
                 <div class="col-md-2">
                     <div class="remove-btn-container">
                         <form action="<?= $this->MelisLink($this->idPage, true);?>" method="post" id="tempForm">
                             <input type="hidden" name="cart_variant_id" value="<?= $item['var_id']?>" />
                             <button type="submit"><i class="zmdi zmdi-close"></i></button>
                         </form>
                     </div>
                 </div>
             </div>
         <?php } ?>
    </div>
    <div class="cart-subtotal"> Subtotal: <span><?= $this->currency.number_format($this->basketTotal, 2); ?></span> </div>
    <div class="check-btn"> <a class="btn-def" href="<?php echo $this->MelisLink($this->layout()->siteDatas['checkout_page_id'], true)?>"><?= $this->translate('tr_meliscommerce_plugin_cart_view');?></a> </div>
</div>
<?php } else { ?>
        <span for=""><?= $this->translate('tr_meliscommerce_plugin_cart_no_item');?></span>
<?php } ?>
<style>
    .remove-btn-container{
        position: absolute;
        left: 0;
    }
    #tempForm button{
        color:#0c0c0c;
        border:none;
        background: transparent;
    }
    #tempForm button:hover{
        color:#8b0000;
    }
    .cart-main-container{
        width: 250px;
    }
    .cart-data-container{
        overflow-y: auto;
        max-height: 370px;
        overflow-x: hidden;
    }
</style>
