<?php if ($this->checkootErrorMsg):?>
    <h1>Checkout Summary</h1>
    <?php if ($this->checkOutHasErr):?>
    	<h3>Product error(s) occured. <small>Error message appeared under the name of the Product.</small></h3>
    <?php endif;?>
    <table class="table table-bordered">
    	<thead>
    		
    		<tr>
    			<th>Product</th>
    			<th>Quantity</th>
    			<th>Unit Price</th>
    			<th>Sub Total</th>
    		</tr>
    	</thead>
    	<tbody>	
    		<?php 
    		    $totalQty = 0;
    		    foreach ($this->checkOutCart As $val):
    	    ?>
        		<tr>
        			<td>
        				<?php 
        				    echo $val['product_name'].' ('.$val['var_sku'].')';
        				    if (!empty($val['var_err']))
        				    {
        				        echo '<div class="text-danger">'.$val['var_err'].'</div>';
        				    }
    				    ?>
    				</td>
        			<td align="right"><?php echo $val['var_quantity']?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].' '.$val['var_price']?></td>
        			<td align="right"><?php echo $val['var_currency_symbol'].' '.$val['var_total']?></td>
        		</tr>
    		<?php 
    		    $totalQty += $val['var_quantity']; 
    		    endforeach;
    	    ?>
    	</tbody>
    	<tfoot>
    		<tr>
    			<th></th>
    			<th style="text-align: right"><?php echo $totalQty?></th>
    			<th style="text-align: right">Sub Total</th>
    			<th style="text-align: right"><?php echo $this->checkOutCartSubTotal?></th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="3">Discount</th>
    			<th style="text-align: right">
    				<?php 
                	    echo $this->checkOutCartDiscount;
                	   
                	    if (!empty($this->checkOutCartDiscountInfo))
                	    {
                	       echo '<div>Coupon Code: '.$this->checkOutCartCouponCode.'</div>';
                	       echo '<div>Coupon Value: '.$this->checkOutCartDiscountInfo.'</div>';
                	    }
                	    
                	    if (!empty($this->checkOutCartCouponErrMsg))
                	    {
                	        echo '<div>'.$this->checkOutCartCouponErrMsg.'</div>';
                	    }
            	    ?>
    			</th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="3">Shipping cost</th>
    			<th style="text-align: right"><?php echo $this->checkOutShipping?></th>
    		</tr>
    		<tr>
    			<th style="text-align: right" colspan="3">Total</th>
    			<th style="text-align: right"><?php echo $this->checkOutCartTotal?></th>
    		</tr>
    		
    	</tfoot>
    </table>

	<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>">Previous</a>
    <?php if (!$this->checkOutHasErr):?>
    	<a class="btn btn-primary pull-right" href="<?php echo $this->nextStep_link?>">Proceed to Payment</a>
    <?php endif;?>

<?php else:?>
	<h1><?php echo $this->checkootErrorMsg?></h1>
	<?php if ($this->prevStep_link):?>
		<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>">Previous</a>
	<?php endif;?>
<?php endif;?>