<?php if ($this->messageErr):?>
	<p><?php echo $this->messageErr?></p>
<?php endif;?>
<?php 
    $form = $this->couponForm;
    $form->add(array(
        'name' => 'submit',
        'attributes' => array(
            'type' => 'submit',
            'value' => 'Validate',
        ),
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
?>