<?php if ($this->hasCartItems):?>
    <form id="checkout-addresses-default">
    	<div style="overflow: hidden;">
    		<div id="checkout-delivery-address-default" style="width: 50%; float: left; padding: 5px">
    			<h1>Delivery Address</h1>
                <?php
                	$form = $this->checkOutDeliveryAddress;
                	$form->prepare();
                    echo $this->formCollection($form);
                ?>
            </div>
    		<div id="checkout-billing-address-default"  style="width: 50%; float: left; padding: 5px">
    			<h1>Billing Address</h1>
                <?php
                	$form = $this->checkOutBillingAddress;
                	$form->prepare();
                	echo $this->formCollection($form);
                ?>
            </div>
        </div>
        <div>
    		<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>">Previous</a>
    		<button class="btn btn-primary pull-right">Next</button>
		</div>
    </form>
<?php else:?>
	<h1>Cart is empty</h1>
	<a class="btn btn-primary" href="<?php echo $this->prevStep_link?>">Previous</a>
<?php endif;?>