<?php 
$priceFilter = $this->filterMenuPriceValue;
?>
<div>
    <div>
        <h5>price</h5> 
    </div>
    <div>
        <div class="price_slider_amount">
            Min price<input type="text" name="min" placeholder="Min" value="<?= $priceFilter['defaultMin']?>"/>
        </div>
        <div class="price_slider_amount">
            Max price<input type="text" name="max" placeholder="Max" value="<?= $priceFilter['defaultMax']?>" />
        </div>
    </div>
</div>