<?php
    function recursiveCategoryListDisplay($categories, $firstLoop = true){    
        $temp = '';
        if($categories){
            if (!$firstLoop){
                $temp .= '<ul>';
            }
            
            foreach($categories as $category){
                
                $temp_1 = array(); 
                if(!empty($category['children'])){
                    $temp_1 = recursiveCategoryListDisplay($category['children'], false);
                }
                
                $opened = '';
                if ($category['state']['opened']){
                    $opened = 'opened';
                }
                
                $selected = '';
                if ($category['state']['selected']){
                    $selected = 'selected';
                }
                
                $temp .= '<li class="'.$opened.'"><span class="'.$selected.'" title="'.$category['text'].'">'.$category['cat_id'].' - '.$category['text'].'</span>';
                $temp .= (!empty($temp_1['html'])) ? $temp_1['html'] : '';
                $temp .= '</li>';
            }
            
            if (!$firstLoop){
                $temp .= '</ul>';
            }
        }
        
        return array('html' => $temp);
    }
?>

<div class="row">
    <div class="col-md-12">
    	<ul id="<?= $this->pluginId; ?>" class="default-category-tree">
    		<?php echo recursiveCategoryListDisplay($this->categoryList)['html'];?>
        </ul>
    </div>
</div>



