<?php 

foreach($this->categoryListProducts as $product){
    $categoryName = !empty($product->getCategories())? $product->getCategories()[0]->catt_name : '' ;
    $productname = '';
    $price = !empty($product->display_price)? $product->display_price : '';
    $mainImage = '';
    
    if(!empty($product->getTexts())){
        foreach($product->getTexts() as $text){
            if($text->ptt_code == 'TITLE'){
                $productName = $text->ptxt_field_short;
                break;
            }
        }
    }
    // if no texts or translations use the reference name
    if(empty($productName)){
        $productName = $product->getProduct()->prd_reference;
    }
    
    foreach($product->getDocuments() as $document){
        if($document->doc_type_id){
            $mainImage = $document->doc_path;
            break;
        }
    }

?>
<div>
    <div>
        <div>
            <?php $categoryName = !empty($product->getCategories())? $product->getCategories()[0]->catt_name : '' ; 
            echo $categoryName;
            ?>
            <div>
                <img alt="" src="<?= $mainImage ?>" height="300" width="300">
            </div>
        </div>
        <div>
            <div><?= $productName?></div>
            <div>
                <div>
                    <div> <?= $price ?> </div>
                </div>
            </div>
        </div>
    </div>
    <br>
</div>
<?php 
}

?>