<div>
    <!-- Nav tabs -->
  	<ul class="nav nav-tabs" role="tablist">
  		<?php foreach ($this->categoryProducts As $key => $val){?>
  			<?php 
  			    foreach ($val->getTranslations() As $tVal)
  			    {
  			        $catName = $tVal->catt_name;
  			    }
  			?>
  			<li role="presentation" class="nav-item <?php echo (!$key) ? 'active' : ''?>">
				<a class="nav-link" data-bs-target="#<?php echo $val->getId().'-cat-prd-lst-plugin'?>" href="#<?php echo $val->getId().'-cat-prd-lst-plugin'?>" aria-controls="<?php echo $val->getId().'-cat-prd-lst-plugin'?>" role="tab" data-bs-toggle="tab"><?php echo $catName ?></a>
			</li>
  		<?php }?>
  	</ul>
    <!-- Tab panes -->
  	<div class="tab-content" style="padding: 10px; background: #fff;">
		<?php if(!empty($this->categoryProducts)) { ?>
			<?php foreach ($this->categoryProducts As $key => $val){?>
				<div role="tabpanel" class="tab-pane <?php echo (!$key) ? 'active' : ''?>" id="<?php echo $val->getId().'-cat-prd-lst-plugin'?>">
					<div class="row">
						<?php if ($val->products){?>
							<?php foreach ($val->products As $prd){?>
								<?php 
									$product = $prd;
									
									// Getting Product Default Image
									$productImg = '';
									foreach ($product->getDocuments() As $dKey => $dVal)
									{
										if ($dVal->dtype_sub_code == 'DEFAULT')
										{
											$productImg = $dVal->doc_path;
										}
									}
									
									// Gettking Product Name
									$productName = '';
									foreach ($product->getTexts() As $tKey => $tVal)
									{
										if ($tVal->ptt_code == 'TITLE')
										{
											$productName = $tVal->ptxt_field_short;
										}
									}
								?>
								<div class="col-xs-4 col-sm-3 col-md-2">
									<div class="thumbnail">
										<img src="<?php echo $productImg ?>">
										<div class="caption">
											<h4>
												<?php 
													// Getting Product Price
													$prdPriceStr = null;
													foreach ($product->getPrice() As $pKey => $pVal)
													{
														$prdPriceStr = ' ('.number_format($pVal->price_net).')';
													}
												?>
												<a href="<?php echo $this->MelisCommerceLink('product', $product->getId(), $this->langId, true)?>"><?php echo $productName .$prdPriceStr ?></a>
											</h4>
											<?php foreach ($product->getCategories() As $cKey => $cVal){?>
												<p class="label label-primary"><?php echo $cVal->catt_name ?></p>
											<?php }?>
										</div>
									</div>
								</div>
							<?php }?>
						<?php }else{?>
							<div class="alert alert-warning">
								<?= $this->translate('tr_meliscommerce_plugin_sub_categories_product_list_no_result'); ?>
							</div>
						<?php }?>
					</div>
				</div>
			<?php }?>
		<?php }else{?>
			<div class="alert alert-warning">
				<?= $this->translate('tr_meliscommerce_plugin_sub_categories_product_list_no_result'); ?>
			</div>
		<?php }?>
  	</div>
</div>