<?php
    function recursiveListDisplay($categories, $selectedCategories){    
        $temp = '';
        if($categories){
            $temp .= '<ul>';
            foreach($categories as $category){
                
                $temp_1 = array(); 
                if(!empty($category->getChildren())){
                    $temp_1 = recursiveListDisplay($category->getChildren(), $selectedCategories);
                }
                $temp .= '<li>'.$category->getTranslations()[0]->catt_name;
                $temp .= (!empty($temp_1['html'])) ? $temp_1['html'] : '';
                $temp .= '</li>';
            }
            $temp .= '</ul>';
        }
        
        return array('html' => $temp);
    }
?>

<div>
    <div>
        <h5>categories</h5> 
    </div>
    <div>
    	<?php 
        	// recursive loop for displaying children, a simple loop can be done if category is a single dimension array
        	$temp = recursiveListDisplay($this->filterMenuCategoryList, $this->selectedCategories);
            echo $temp['html'];
    	?>
    </div>
</div>