<div class="form-group">
	<?php foreach ($this->attrs As $val){?>
    	<div class="row">
    		<div class="col-xs-12">
    			<div class="pdc-heading clearfix">
                    <h4>
                    	<?php echo $val->atrans_name ?>
                    </h4>
                </div>
    		</div>
    		<form>
        		<?php foreach ($val->attr_values As $vals){?>
        			<?php
        			    $checked = '';
        			    if (!empty($this->formData['m_box_filter_attribute_values_ids_selected'])){
        			        if(in_array($vals->atval_id, $this->formData['m_box_filter_attribute_values_ids_selected'])){
        			            $checked = 'check';
        			        }
        			    }
        			?>
        			<div class="col-xs-4">
                    	<label class="full-category-product-list-attr-config-checkbox">
                    		<?php $valCol = 'avt_v_'.$vals->atype_column_value;?>
                    		<i class="fa fa-<?php echo ($checked) ? $checked.'-' : '' ?>square-o fa-lg"></i> <?php echo $vals->$valCol?>
                    		<input type="checkbox" name="m_box_filter_attribute_values_ids_selected[]" value="<?php echo $vals->atval_id ?>" <?php echo ($checked) ? $checked.'ed' : '' ?> style="display: none">
                    	</label>
            		</div>
        		<?php }?>
    		</form>
    	</div>
	<?php }?>
</div>
<style>
.full-category-product-list-attr-config-checkbox {
    cursor: pointer;
    margin-left: 20px;
    font-weight: normal;
}
.full-category-product-list-attr-config-checkbox input {
    display: none;
}
.full-category-product-list-attr-config-checkbox .fa-check-square-o {
    color: #72af46;
}
</style>
<script type="text/javascript">
$(function(){
    var checkboxClass = ".full-category-product-list-attr-config-checkbox";
    //Category Information Form Countries Custom Checkboxes
    $(checkboxClass).on("click", function(evt){
    	
    	if($(this).find('.fa').hasClass('fa-check-square-o')){ // unchecking category Checkbox
    		if(!$(this).find('.fa').hasClass("check-all")){
    			$(this).find('.fa').removeClass('fa-check-square-o');
    			$(this).find('.fa').addClass('fa-square-o');
    			$(this).find('input[type="checkbox"]').removeAttr('checked');
    		}
    	}else{ // Checking Category Checkboxes
    		if($(this).find('.fa').hasClass("check-all")){ // Unchecking "All" Checkbox
    			$(checkboxClass).find('.fa').removeClass('fa-check-square-o');
    			$(checkboxClass).find('.fa').addClass('fa-square-o');
    			$(checkboxClass).find('input[type="checkbox"]').removeAttr('checked');
    		}else{ // Checking "All" Checkbox
    			$(checkboxClass).find('.check-all').removeClass('fa-check-square-o');
    			$(checkboxClass).find('.check-all').addClass('fa-square-o');
    			$(checkboxClass).find('.check-all').next('input[type="checkbox"]').removeAttr('checked'); // Unchecking "All" Checkbox
    		}
    		
    		$(this).find('.fa').removeClass('fa-square-o');
    		$(this).find('.fa').addClass('fa-check-square-o');
    		$(this).find('input[type="checkbox"]').attr('checked','checked');
    	}
    	
    	evt.stopPropagation();
    	evt.preventDefault();
    });
});
</script>