<div>
	<div class="row">
		<?php foreach ($this->categoryListProducts As $prd){?>
          	<div class="col-xs-4 col-sm-3 col-md-2">
            	<div class="thumbnail">
                  	<img src="<?php echo $prd['prd_docs_image']['imagePath']?>">
                  	<div class="caption">
                        <h4>
                        	<?php 
                        	    $prdPrice = $prd['prd_price_details'];
                        	    $prdPriceStr = 'N/A';
                        	    if (!empty($prdPrice['prd_currency_symbol']) && !empty($prdPrice['prd_price_net']))
                        	    {
                        	        $prdPriceStr = $prdPrice['prd_currency_symbol'].number_format($prdPrice['prd_price_net'],2);
                        	    }
                        	?>
                        	<a href="<?php echo $this->MelisCommerceLink('product', $prd['prd_id'], $this->langId, true)?>"><?php echo $prd['prd_text'].' ('.$prdPriceStr.')' ?></a>
                    	</h4>
                    	<?php foreach ($prd['prd_categories'] As $cats){?>
                        	<p class="label label-primary"><?php echo $cats['catt_name']?></p>
                        <?php }?>
                  	</div>
            	</div>
          	</div>
		<?php }?>
	</div>
</div>