<div class="row">
	<div class="col-md-12" id="productCategorySearchZone">
		<div class="form-group">
        	<input type="text" class="form-control" name="catPrdSliderPluginSearch" id="catPrdSliderPluginSearch" placeholder="<?= $this->translate('tr_meliscommerce_categories_list_tree_view_search_input'); ?>">
    	</div>
    	<div class="row">
    		<div class="col-xs-6 col-md-6 col-lg-3">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginClearBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_clear')?>">
    				<i class="fa fa-eraser"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_clear')?></span>
    			</button>
    		</div>
    		<div class="col-xs-6 col-md-6 col-lg-3 margin-bottom-10">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginCollapseBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_collapse_all')?>">
    				<i class="fa fa-compress fa-flip-horizontal"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_collapse_all')?></span>
    			</button>
    		</div>
    		<div class="col-xs-6 col-md-6 col-lg-3">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginExpandBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_expand_all')?>">
    				<i class="fa fa-expand fa-flip-horizontal"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_expand_all')?></span>
    			</button>
    		</div>
    		<div class="col-xs-6 col-md-6 col-lg-3">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginRefreshBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_refresh')?>">
    				<i class="fa fa-refresh"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_refresh')?></span>
    			</button>
    		</div>
    	</div>
	</div>
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6">
				<br>
        		<div class="prodCatLangDropDownContainer">
                	<div class="filter-dropdown clearfix categoryLangTreePluginDropdown" data-productid="<?= $this->productId; ?>">
                		<a href="#" class="dropdown-toggle category-list-lang-dropdown" data-toggle="dropdown">
                			<i class="fa fa-language"></i>
                			<span class="filter-key"><?= $this->currentLangName; ?></span>
                			<span class="caret"></span>
                		</a>
                		<ul class="dropdown-menu category-tree-view-lang-plugin">
						<?php 
						    if($this->langData): 
						        foreach($this->langData as $lang): ?>
                        			<li>
    									<?php
    									$imageData = $lang->elang_flag;
    									$image = !empty($imageData) ? '<img src="data:image/jpeg;base64,'. ($imageData) .'" class="imgDisplay pull-right" width="24" height="24"/>' : '<i class="fa fa-globe"></i>';
    									?>
                        				<a data-locale="<?= $lang->elang_locale; ?>"><?= $lang->elang_name; ?><span class="pull-right"><?php echo $image; ?></span></a>
                        			</li>
            			<?php 
                			    endforeach;
							endif;
						?>
                		</ul>
                	</div>
				</div>
			</div>
			<div class="col-md-6"></div>
		</div>
	</div>
	<div class="col-md-12">
		<div id="fullCategoryProductListPluginTreeConfig" class="productCategoryView" data-langlocale="<?php echo $this->currentLangLocale ?>"></div>
	</div>
	<form id="fullCategoryProductListPluginTreeConfig_form">
		<?php if (!empty($this->formData['m_box_filter_categories_ids_selected'])):?>
    		<?php foreach ($this->formData['m_box_filter_categories_ids_selected'] As $val):?>
    			<input type="hidden" name="m_box_filter_categories_ids_selected[]" value="<?php echo $val?>">
    		<?php endforeach;?>
		<?php endif;?>
	</form>
</div>

<script>
    window.initCatTree = function(){
    	
    	var categoryTree = $("#fullCategoryProductListPluginTreeConfig");
    	
        categoryTree.jstree({
            "core" : {
            	"multiple": false,
                "check_callback": true,
                "animation" : 500,
                "themes": {
                    "name": "proton",
                    "responsive": false
                },
                "dblclick_toggle" : false,
                "data" : {
                	"cache" : false,
                	"data": categoryTreeData(),
                    "url" : "/melis/MelisCommerce/MelisComCategoryList/getCategoryTreeView",
                },
            },
            "types" : {
    			"default" : {
    				"icon" : "fa fa-circle text-success",
    			},
    			"selected": {
                    select_node : false
                }
    		},
            "checkbox": {
    	        three_state: false,
    	        whole_node : false,
    	        tie_selection : false,
    	    },
            "plugins": [
                "search", // Plugins for Search of the Node(s) of the Tree View
                "types", // Plugins for Customizing the Nodes
                "checkbox",
            ]
        }).on("check_node.jstree uncheck_node.jstree", function(e, data) {
      	  	//console.log(data.node.id + ' ' + data.node.text + (data.node.state.checked ? ' CHECKED': ' NOT CHECKED'))
      	  	if(data.node.state.checked){
    			$("#fullCategoryProductListPluginTreeConfig_form").append('<input type="hidden" name="m_box_filter_categories_ids_selected[]" value="'+data.node.id+'">');
      	  	}else{
          	  	$("#fullCategoryProductListPluginTreeConfig_form input[value='"+data.node.id+"']").remove();
      	  	}
    	});
    }
    
    window.categoryTreeData = function(){
    	
    	var categoryTree = $("#fullCategoryProductListPluginTreeConfig");
    	
    	var dataString = new Array;
    	
    	dataString.push({
    		name : 'langlocale',
    		value : categoryTree.data('langlocale')
    	});
    	
    	dataString.push({
    		name : 'idAndNameOnly',
    		value : true
    	});
    
    	var catIds = new Array;
    	$("#fullCategoryProductListPluginTreeConfig_form input[name='m_box_filter_categories_ids_selected[]']").each(function(){
    		catIds.push($(this).val());
    	});
    	var catIdsStr = '';
    	if(catIds.length){
    		catIdsStr = catIds.join()
    	}
    	
    	dataString.push({
    		name : 'categoriesChecked',
    		value : catIdsStr
    	});
    
    	return dataString;
    }
    
    $(function(){
        
    	initCatTree();
    	
    	var categoryTree = $("#fullCategoryProductListPluginTreeConfig");
    	
    	$("body").on("keyup", "#catPrdSliderPluginSearch", function(e){ 
    		var searchString = $(this).val();
    		categoryTree.jstree('search', searchString);
    		console.log(searchString);
    	});
    	
    	// Clear Input Search
    	$("body").on("click", "#catPrdSliderPluginClearBtn", function(e){ 
    		$("#catPrdSliderPluginSearch").val("");
    		categoryTree.jstree('search', '');
    	});
    	
    	// Toggle Buttons for Category Tree View
    	$("body").on("click", "#catPrdSliderPluginExpandBtn", function(e){ 
    		categoryTree.jstree("open_all");
    	});
    	
    	$("body").on("click", "#catPrdSliderPluginCollapseBtn", function(e){ 
    		categoryTree.jstree("close_all");
    	});
    	
    	// Refrech Category Tree View
    	$("body").on("click", "#catPrdSliderPluginRefreshBtn", function(e){ 
    		categoryTree.jstree(true).refresh("forget_state", true);
    		categoryTree.jstree('search', '');
    		$("#catPrdSliderPluginSearch").val("");
    		categoryTree.jstree(true).refresh();
    	});
    	
    	$(".category-tree-view-lang-plugin li a").on("click", function(){
    		var langText = $(this).text();
    		var langLocale = $(this).data('locale');
    		$('.categoryLangTreePluginDropdown span.filter-key').text(langText);
    		categoryTree.data('langlocale', langLocale);
    		
    		categoryTree.jstree(true).settings.core.data.data = categoryTreeData();
    		categoryTree.jstree(true).refresh();
    	});
    });
</script>