<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id. ' '.$data_melisKey?>>	
    <div class="make-switch commerce-switch" id="cat_status" data-on-label="<?php echo $this->translate('tr_meliscommerce_categories_common_label_online')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_categories_common_label_offline')?>" data-text-label="<?php echo $this->translate('tr_meliscommerce_categories_common_label_status')?>">
        <input type="checkbox" name="cat_status" <?php echo $this->categorystatus?>>
    </div>
</div>