<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id. ' '.$data_melisKey?> class="border-bottom">	
	<div class="form-group">
		<div class="pdc-heading">
			<h4>
				<i class="fa fa-calendar"></i> <?php echo $this->translate('tr_meliscommerce_categories_category_date_validity')?>
			</h4>
		</div>
    	<?php
        	$form = $this->meliscommerce_categories_date_validty_form;
        	$form->prepare();
        	echo $this->form()->openTag($form); 
        	echo $this->melisFieldCollection($form);
        	echo $this->form()->closeTag(); 
        	echo $this->datepickerInit;
        ?>
	</div>
</div>