<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="col-xs-12 col-lg-6">
	<div <?php echo $id.' '.$data_melisKey; ?>>	
		<?php 
			if(!empty($this->zoneconfig['interface'])) {
				foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
					echo $this->$keyConfig;
					echo '<hr>';
				}
			}
		?>
	</div>
</div>