<?php 
    if ($this->catFatherId == '-1'){
        $type = 'catalog';
    }else{
        $type = 'category';
    }
?>
<button class="btn btn-success float-right" id="saveCategory" data-catid="<?php echo $this->catId ?>" data-catfatherid="<?php echo $this->catFatherId ?>" data-loading-text="<?php echo $this->translate('tr_meliscommerce_categories_common_label_saving')?>" autocomplete="off"><i class="fa fa-save"></i> <?php echo $this->translate('tr_meliscommerce_categories_'.$type.'_save')?></button>