<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div id="categoryInfoPanel" class="panel-collapse in" style="height: auto;" <?php echo $id.' '.$data_melisKey; ?>>
	<div class="panel-body">
		<?php 
        	if(!empty($this->zoneconfig['interface'])) {
        	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
        	        echo $this->$keyConfig.' ';
        	    }
        	}
        ?>
	</div>
</div>