import { mergeDict } from '../../shared/i18n'

/** Dictionnaire spécifique à l'outil Contacts (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Contacts', subtitle: 'Contacts MelisCommerce',
    new: 'Nouveau contact', search: 'Rechercher un contact…', empty: 'Aucun contact trouvé', filter_account: 'Tous les comptes', filter_type: 'Tous les types',
    count: '{n} contacts — fin de la liste',
    col_id: 'ID', col_status: 'Statut', col_firstname: 'Prénom', col_name: 'Nom', col_account: 'Compte',
    col_email: 'Email', col_type: 'Type', col_tags: 'Tags', col_created: 'Créé le',
    exp_title: 'Exporter les contacts', exp_subtitle: '{n} contacts seront exportés', exp_filename: 'contacts',
    del_title: 'Supprimer le contact', del_confirm: 'Supprimer « {u} » ? Cette action est irréversible.',
    new_title: 'Nouveau contact', edit_title: 'Modifier le contact',
    f_identity: 'Identité', f_options: 'Options',
    f_civility: 'Civilité', f_civility_ph: '— Civilité —',
    f_firstname: 'Prénom', f_firstname_ph: 'Prénom', f_name: 'Nom', f_name_ph: 'Nom',
    f_middle_name: 'Deuxième prénom', f_middle_name_ph: 'Deuxième prénom (optionnel)',
    f_language: 'Langue', f_language_ph: '— Choisir une langue —', f_language_search: 'Rechercher une langue…', f_language_none: 'Aucune langue',
    f_email: 'Email', f_email_ph: 'email@exemple.com',
    f_password: 'Mot de passe', f_password_edit: 'Mot de passe (laisser vide pour conserver)', f_password_ph: 'Nouveau mot de passe',
    f_confirm_password: 'Confirmer le mot de passe', f_confirm_password_ph: 'Confirmer',
    f_section_password: 'Mot de passe', f_section_login: 'Connexion',
    f_job: 'Fonction', f_job_ph: 'Fonction / poste',
    f_job_service: 'Service', f_job_service_ph: 'Service / département',
    f_mobile: 'Mobile', f_mobile_ph: 'Téléphone mobile',
    f_landline: 'Fixe', f_landline_ph: 'Téléphone fixe',
    f_account: 'Compte', f_account_ph: '— Choisir un compte —',
    f_type: 'Type', f_type_ph: 'Type de contact', f_tags: 'Tags', f_tags_ph: 'Tags séparés par des virgules',
    f_active: 'Actif', f_active_hint: 'Le contact est actif et utilisable.',
    err_firstname: 'Le prénom est obligatoire.', err_name: 'Le nom est obligatoire.',
    err_language: 'La langue est obligatoire.', err_email: 'Un email valide est obligatoire.',
    err_password_required: 'Le mot de passe est obligatoire.',
    err_password: 'Les mots de passe ne correspondent pas.', err_save: 'Erreur lors de la sauvegarde',
    err_required_fields: 'Veuillez vérifier les champs obligatoires.',
    tab_information: 'Information', tab_address: 'Adresse', tab_association: 'Association',
    save_first: 'Enregistrez le contact pour accéder à cet onglet.',
    f_type_label: 'Type', type_person: 'Personne', type_company: 'Société',
    a_label: 'Libellé', a_type: 'Type', a_name: 'Nom', a_address: 'Adresse', a_phone: 'Téléphone', a_empty: 'Aucune adresse',
    as_account: 'Compte', as_status: 'Statut', as_empty: 'Aucun compte associé', yes: 'Oui',
    as_def_account: 'Compte par défaut', as_def_contact: 'Contact par défaut',
    as_link_ph: 'Nom du compte', as_link: 'Lier le compte', as_add: 'Ajouter un compte',
    as_unlink_title: 'Délier le compte', as_unlink_confirm: 'Délier « {u} » de ce contact ?',
    ph_search_address: 'Rechercher une adresse…', ph_search_account: 'Rechercher un compte…',
  },
  en: {
    title: 'Contacts', subtitle: 'MelisCommerce contacts',
    new: 'New contact', search: 'Search a contact…', empty: 'No contact found', filter_account: 'All accounts', filter_type: 'All types',
    count: '{n} contacts — end of list',
    col_id: 'ID', col_status: 'Status', col_firstname: 'First name', col_name: 'Name', col_account: 'Account',
    col_email: 'Email', col_type: 'Type', col_tags: 'Tags', col_created: 'Created',
    exp_title: 'Export contacts', exp_subtitle: '{n} contacts will be exported', exp_filename: 'contacts',
    del_title: 'Delete contact', del_confirm: 'Delete “{u}”? This action is irreversible.',
    new_title: 'New contact', edit_title: 'Edit contact',
    f_identity: 'Identity', f_options: 'Options',
    f_civility: 'Civility', f_civility_ph: '— Civility —',
    f_firstname: 'First name', f_firstname_ph: 'First name', f_name: 'Name', f_name_ph: 'Name',
    f_middle_name: 'Middle name', f_middle_name_ph: 'Middle name (optional)',
    f_language: 'Language', f_language_ph: '— Choose a language —', f_language_search: 'Search a language…', f_language_none: 'No language',
    f_email: 'Email', f_email_ph: 'email@example.com',
    f_password: 'Password', f_password_edit: 'Password (leave empty to keep current)', f_password_ph: 'New password',
    f_confirm_password: 'Confirm password', f_confirm_password_ph: 'Confirm',
    f_section_password: 'Password', f_section_login: 'Login',
    f_job: 'Job title', f_job_ph: 'Job title',
    f_job_service: 'Department', f_job_service_ph: 'Department / service',
    f_mobile: 'Mobile', f_mobile_ph: 'Mobile phone',
    f_landline: 'Landline', f_landline_ph: 'Landline number',
    f_account: 'Account', f_account_ph: '— Choose an account —',
    f_type: 'Type', f_type_ph: 'Contact type', f_tags: 'Tags', f_tags_ph: 'Comma-separated tags',
    f_active: 'Active', f_active_hint: 'The contact is active and usable.',
    err_firstname: 'First name is required.', err_name: 'Last name is required.',
    err_language: 'Language is required.', err_email: 'A valid email is required.',
    err_password_required: 'Password is required.',
    err_password: 'Passwords do not match.', err_save: 'Error while saving',
    err_required_fields: 'Please check the required fields.',
    tab_information: 'Information', tab_address: 'Address', tab_association: 'Association',
    save_first: 'Save the contact to access this tab.',
    f_type_label: 'Type', type_person: 'Person', type_company: 'Company',
    a_label: 'Label', a_type: 'Type', a_name: 'Name', a_address: 'Address', a_phone: 'Phone', a_empty: 'No address',
    as_account: 'Account', as_status: 'Status', as_empty: 'No linked account', yes: 'Yes',
    as_def_account: 'Default account', as_def_contact: 'Default contact',
    as_link_ph: 'Account name', as_link: 'Link account', as_add: 'Add account',
    as_unlink_title: 'Unlink account', as_unlink_confirm: 'Unlink “{u}” from this contact?',
    ph_search_address: 'Search an address…', ph_search_account: 'Search an account…',
  },
})
