<?php 
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
?>

<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons notes" data-toggle="tab" aria-expanded="true"><i></i> 
                		<?= $this->translate('tr_meliscommerce_order_export_label')?></a></li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" <?php echo $id ?>>
                            <div class="row">
                            	<div class="col-md-12">
                            		
                                    <?php
                                    	$form = $this->meliscommerce_client_list_export_form;
                                    	echo $this->form()->openTag($form);
                                    	echo $this->melisFieldCollection($form);
                                    ?>
                                    <div class="checkbox cb-cont melis-commerce-checkbox">
                                       <label class="remember-me-cont">
                                            <span class="cbmask-outer">
                                            	<span  class="cbmask-inner"></span>
                                           	</span>
                                            <input type="hidden" name="orderExportEncapse" value="0" >
                                            <input type="checkbox" name="orderExportEncapse" value="1"> <?= $this->translate('tr_meliscommerce_orders_encapse'); ?>
                                       </label>
                                  </div>
                                  <br>
                                    <?php 
                                    	echo $this->form()->closeTag(); 
                                    ?>
                                 	<div class="footer-modal d-flex flex-row justify-content-between">
                                 		<button data-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                                 		<button class="btn btn-success" id="exportClients" ><i class="fa fa-save"></i>  <?php echo $this->translate('tr_meliscommerce_order_export_label') ?></button>
                                 	</div> 
                                 	<?= $this->datePickerInit; ?>                              	
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>