<?php 
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
?>

<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="nav-item active">
                            <a data-bs-target="#<?php echo $this->zoneconfig['conf']['id'] ?>" href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons notes" data-bs-toggle="tab" aria-expanded="true"><i></i> 
                		    <?= $this->translate('tr_meliscommerce_order_export_label')?></a>
                        </li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" <?php echo $id ?>>
                            <div class="row">
                            	<div class="col-md-12">

                                    <?php
                                    $form = $this->meliscommerce_client_list_export_accounts_form;
                                    $form->prepare();
                                    echo $this->form()->openTag($form);
                                    foreach($form->getElements() as $key => $val)  {
                                        echo '<div class="form-group">';
                                        if ($val->getLabel())
                                        {
                                            $required = '';
                                            if(!empty($val->getAttribute('required'))){
                                                $required = ' <sup>*</sup>';
                                            }
                                            echo $this->formLabel()->openTag($val);
                                            echo $val->getLabel();
                                            echo $required;
                                            echo $this->formLabel()->closeTag();
                                        }
                                        echo $this->formElement($val, array('class' => 'form-control'));
                                        echo '</div>';
                                    }
                                    ?>

                                 	<div class="footer-modal d-flex flex-row justify-content-between">
                                 		<button data-bs-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                                 		<button class="btn btn-success" id="exportAccounts" ><i class="fa fa-arrow-circle-up"></i>  <?php echo $this->translate('tr_meliscommerce_order_export_label') ?></button>
                                 	</div>
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>