<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id.' '.$data_melisKey; ?> style="position: relative">
	<iframe class="order-checkout-payment-iframe" src="/melis/MelisCommerce/MelisComOrderCheckout/renderOrderCheckoutPaymentIframe?orderId=<?php echo $this->orderId?>&totalCost=<?php echo $this->totalCost?>"></iframe>	
	<br>
    <div class="row bottom-bottons">
        <div class="me-hl col-xs-12 col-md-12">
            <button class="btn btn-success pull-right orderCheckoutConfirmPayment orderCheckoutNextStep" data-tabid="#id_meliscommerce_order_checkout_confirmation_step_nav"><i class="fa fa-check-circle"></i> <?php echo $this->translate('tr_meliscommerce_order_checkout_common_next')?></a>
        </div>
    </div>
</div>
