<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="me-hl col-xs-12 col-md-8" <?php echo $id.' '.$data_melisKey; ?>>
    <?php 
		$this->melisGenericTable()->setTable(array(
		    'id' => 'orderCheckoutProductListTbl',
		    'class' => 'table table-striped table-primary dt-responsive nowrap',
		    'cellspacing' => '0',
		    'width' => '100%'
	    ));
		
        $columns = array();
        $columnStyle = array();
        foreach($this->tableColumns as $columnText){
            $columns[] = $columnText['text']; 
        }
        
		$this->melisGenericTable()->setColumns($columns);
		echo $this->melisGenericTable()->renderTable();
	?>
</div>
<script type="text/javascript">
	<?php echo $this->getToolDataTableConfig; ?>
</script>