<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="me-hl col-xs-12 col-md-4" <?php echo $id.' '.$data_melisKey; ?>>
    <div id="basket-order-checkout" class="red-box-panel basket-panel">
        <h3><i class="icon-shopping-basket"></i> Basket List</h3>
        <div class="red-box-panel-list basket-panel-list">         
        	<?php foreach ($this->basket As $val):?>    
            	<div class="order-basket-list">
                    <div class="form-group">                                                
                        <h4><?php echo $val['product_name'] ?></h4>
                        <span><?php echo $val['var_sku'] ?></span>
                    </div>
                    <div class="form-group">
                        <i class="fa fa-minus order-basket-variant-qty-btn qty-minus text-primary" data-variantid="<?php echo $val['var_id']?>"></i>
                        <input type="text" class="form-control qty-val orderBasketVariantQty" id="<?php echo $val['var_id']?>_orderBasketVariantQty" data-variantid="<?php echo $val['var_id']?>" data-quantity="<?php echo $val['var_quantity']?>" style="width:50px" name="" id="" placeholder="" value="<?php echo $val['var_quantity']?>">
                        <i class="fa fa-plus order-basket-variant-qty-btn qty-plus text-primary" data-variantid="<?php echo $val['var_id']?>"></i>
                        <strong class="order-price float-right">€ <?php echo $val['var_total']?></strong>
                    </div>
                </div>
        	<?php endforeach;?>   
        	
        	<?php if ($this->total):?>
                <div class="form-group">
                    <br><h4 class="float-right" style="margin: 0 10px 0 0;"><strong><?php echo $this->translate('tr_meliscommerce_order_checkout_variant_sub_total')?>: € <?php echo number_format($this->total, 2)?></strong></h4><br>
                </div>
            <?php endif;?>
            
            <?php if (empty($this->basket)):?>
                <div class="me-file-cont">
        			<p><?php echo $this->translate('tr_meliscommerce_order_checkout_variant_empty_basket')?></p>
        		</div>
            <?php endif;?>
        </div>
    </div>
</div>