<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id.' '.$data_melisKey; ?>>
	<h1 class="text-center">Payment Content iFrame</h1>
	<br>
    <div class="row bottom-bottons">
        <div class="me-hl col-xs-12 col-md-12">
            <a href="#id_meliscommerce_order_checkout_summary_step" data-toggle="tab" class="btn btn-success prev-step"><i class="fa fa-arrow-left"></i> Back to Summary </a>
            <a href="#id_meliscommerce_order_checkout_confirmation_step" data-toggle="tab" class="float-right btn btn-success next-step float-right"><i class="fa fa-check-circle"></i> Confirm all Details</a>
        </div>
    </div>
</div>
