<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id.' '.$data_melisKey; ?>>
	<?php 
		$this->melisGenericTable()->setTable(array(
		    'id' => 'orderCheckoutClientListTbl',
		    'class' => 'table table-striped table-primary dt-responsive nowrap',
		    'cellspacing' => '0',
		    'width' => '100%'
	    ));
		
        $columns = array();
        $columnStyle = array();
        foreach($this->tableColumns as $columnText){
            $columns[] = $columnText['text']; 
        }
        
		$this->melisGenericTable()->setColumns($columns);
		echo $this->melisGenericTable()->renderTable();
	?>
	<br>
    <div class="row bottom-bottons">
        <div class="me-hl col-xs-12 col-md-12">
            <a href="#id_meliscommerce_order_checkout_choose_product_step" data-toggle="tab" class="btn btn-success prev-step"><i class="fa fa-arrow-left"></i> Back to Product </a>
            <a href="#id_meliscommerce_order_checkout_select_addresses_step" data-toggle="tab" class="btn btn-success pull-right next-step order-checkout">Proceed to Address <i class="fa fa-arrow-right"></i> </a>
        </div>
    </div>
</div>
<script type="text/javascript">
	<?php echo $this->getToolDataTableConfig; ?>
</script>