<?php 
    $id = 'id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] .'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="checkout-product-variant-list" <?php echo $id.' '.$data_melisKey; ?>>
    <?php foreach ($this->variants As $val):?>
        <div class="order-variant">
            <div class="float-left">
                <span class="dtr-title"><strong><?php echo $val['label']?>: </strong><?php echo $val['var_sku']?></span>
            </div>
            <div class="float-right">
                <span class="btn btn-default cell-val-table"><?php echo number_format($val['var_price'], 2)?></span>
                <button class="btn btn-success orderCheckoutVariantAddBasket" data-variantid="<?php echo $val['var_id']?>"><i class="fa fa-plus"></i></button>
            </div>  
        </div>
    <?php endforeach;?>
    
    <?php if (empty($this->variants)):?>
    	<div class="me-file-cont">
			<p>No Variant</p>
		</div>
    <?php endif;?>
</div>
