<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Payment Done</title>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
        <script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css">
    </head>
<body>
    <div class="container text-center">
    	<span class="fa-stack fa-5x text-success">
          	<i class="fa fa-circle fa-stack-2x"></i>
          	<i class="fa fa-thumbs-up fa-stack-1x fa-inverse"></i>
        </span>
        <h2 class="text-success">
        	<?php echo $this->translate('tr_meliscommerce_order_checkout_payment_done')?>
        </h2>
    </div>
</body>
</html>