<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id.' '.$data_melisKey; ?>>
	<div class="row">
        <?php 
        	if(!empty($this->zoneconfig['interface'])) {
        	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
        	        echo $this->$keyConfig.' ';
        	    }
        	}
        ?>
    </div>
    <br>
    <div class="row bottom-bottons">
        <div class="me-hl col-xs-12 col-md-12">
            <a href="#id_meliscommerce_order_checkout_choose_client_step" id="orderCheckoutFirstStepBtn" data-toggle="tab" class="pull-right btn btn-success next-step order-checkout">Proceed to Clients <i class="fa fa-arrow-right"></i> </a>
        </div>
    </div>
</div>