<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'].'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="tab-pane <?php echo ($this->activateTab) ? 'active' : '' ?>" <?php echo $id. ' '.$data_melisKey?> style="position: relative">				
	<div class="row">
        <div class="me-hl col-xs-12 col-md-9">
            <h1 class="content-heading"><?php echo $this->translate('tr_meliscommerce_order_checkout_Confirmation')?></h1>
            <p><?php echo $this->translate('tr_meliscommerce_order_checkout_confirm_description')?></p>
        </div>
    </div>
    <div class="row">
        <div class="me-hl col-xs-12 col-md-12">
            <div class="alert alert-<?php echo $this->result['alert']?>" role="alert">
            	<?php echo $this->result['message']?>
            	<?php if ($this->result['alert'] == 'success'):?>
            		<p><?php echo $this->result['refernce'] ?> </p>
            	<?php endif;?>
        	</div>
        </div>
    </div>
    <?php if ($this->result['alert'] == 'success'):?>
        <br>
        <div class="row bottom-bottons">
            <div class="me-hl col-xs-12 col-md-12">
                <button class="btn btn-success orderCheckoutEndClose close-tab" data-id="id_meliscommerce_order_checkout"><?php echo $this->translate('tr_meliscommerce_general_common_close') ?> </button>
            </div>
        </div>
    <?php endif;?>
    <?php if ($this->result['alert'] == 'info'):?>
    <br>
    <div class="row bottom-bottons">
        <div class="me-hl col-xs-12 col-md-12">
            <button class="btn btn-success orderCheckoutPrevStep" data-tabid="#id_meliscommerce_order_checkout_payment_step_nav"><i class="fa fa-arrow-left"></i> <?php echo $this->translate('tr_meliscommerce_order_checkout_confirmation_next_btn') ?> </button>
        </div>
    </div>
    <?php endif;?>
</div>