<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?>>
	<div class="pdc-content">
        <?php
        $countryFlag = false;
        $groupFlag = false;
        $name = false;
        $tags = false;

        $form = $this->meliscommerce_clients_main_form;
        $form->prepare();
        echo $this->form()->openTag($form);
        foreach ($form->getElements() As $key => $val)
        {
            $required = '';
            if(!empty($val->getAttribute('required'))){
                $required = ' <sup>*</sup>';
            }

            if($key == 'cli_name' && !$name){
                echo '<label class="'.$key.' d-flex flex-row justify-content-between">
                        <h4><span class="fa fa-user"></span> '.$val->getLabel().$required.'</h4>';
                if(!empty($val->getOption('tooltip')))
                    echo  '<div class="slider-open-tooltip"><i class="fa fa-info-circle fa-lg tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="'.$val->getOption('tooltip').'"></i></div>';

                echo '</label>';
                $name = true;
            }

            if($key == 'cli_group_id' && !$groupFlag){
                echo '<label class="'.$key.' d-flex flex-row justify-content-between">
                        <h4><span class="fa fa-user-times"></span> '.$val->getLabel().$required.'</h4>';
                if(!empty($val->getOption('tooltip')))
                    echo  '<div class="slider-open-tooltip"><i class="fa fa-info-circle fa-lg tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="'.$val->getOption('tooltip').'"></i></div>';

                echo '</label>';
                $groupFlag = true;
            }

            if($key == 'cli_country_id' && !$countryFlag){
                echo '<label class="'.$key.' d-flex flex-row justify-content-between">
                        <h4><span class="fa fa-flag"></span> '.$val->getLabel().$required.'</h4>';
                if(!empty($val->getOption('tooltip')))
                    echo  '<div class="slider-open-tooltip"><i class="fa fa-info-circle fa-lg tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="'.$val->getOption('tooltip').'"></i></div>';

                echo '</label>';

                $countryFlag = true;
            }

            if($key == 'cli_tags' && !$tags){
                echo '<label class="'.$key.' d-flex flex-row justify-content-between">
                        <h4><span class="fa fa-tags"></span> '.$val->getLabel().$required.'</h4>';
                if(!empty($val->getOption('tooltip')))
                    echo  '<div class="slider-open-tooltip"><i class="fa fa-info-circle fa-lg tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="'.$val->getOption('tooltip').'"></i></div>';

                echo '</label>';

                $tags = true;
            }

            echo '<div class="form-group">';
            echo $this->formElement($val, array('class' => 'form-control'));
            echo '</div>';
        }
        echo $this->form()->closeTag();
        ?>
	</div>
	<form id="deletedClientAddress" class="hidden"></form>
</div>
<script>
    $(document).ready(function(){
        $("#id_meliscommerce_clients_main_form #cli_tags").tagsinput({
            allowDuplicates: false
        });

        //remove extra comma when typing word with comma in the end
        $("body").on("keyup", '#id_meliscommerce_clients_main_form .bootstrap-tagsinput input', function (e) {
            if(e.keyCode == 188){//comma
                $(this).val($(this).val().replace(",",""));
            }
        });
    });
</script>