<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?>>
	<div class="row">
		<div class="col-xs-12 col-md-3 col-lg-2">
    		<div class="product-text-tab-container">
            	<ul class="nav-tabs product-text-tab" id="<?php echo $this->clientId.'_client_address_tab_nav' ?>">
            		<?php foreach ($this->clientAddresses As $val):?>
            			<?php $addressId = md5($val->cadd_id)?>
            			<li class="<?php echo $addressId.'_address'?>">
                			<a class="clearfix" data-toggle="tab" id="<?php echo 'nav_add_'.$addressId ?>" href="#<?php echo $addressId.'_address'?>" aria-expanded="false">
                				<span>
                			        <?php echo $this->escapeHtml($val->cadd_address_name) ?>
            				    </span>
                				<i class="fa fa-times deleteClientAddress" data-addressid="<?php echo $val->cadd_id ?>" data-tabclass="<?php echo $addressId.'_address'?>" data-isnewadded="0"></i>
                			</a>
                		</li>
            		<?php endforeach;?>
            	</ul>
            </div>
		</div>
		<div class="col-xs-12 col-md-9 col-lg-10">
			<div class="tab-content client-contact-tab-content" id="<?php echo $this->clientId.'_client_address_tab_content' ?>">
				<?php foreach ($this->clientAddresses As $val):?>
					<?php $addressId = md5($val->cadd_id)?>
					<div id="<?php echo $addressId.'_address' ?>" class="<?php echo $addressId.'_address'?> tab-pane product-text-tab-content" style="border: 1px solid #eee; padding: 15px; margin-bottom: 20px">
                    	<div class="me-action-button-cont">
                    		<?php 
                        		$form = clone $this->meliscommerce_clients_addresses_form;
                        		$form->setAttribute('id', $addressId.'_address_form');
                        		$form->setAttribute('class', 'clientAddressForm');
                        		$form->setAttribute('data-addressid', $addressId);

                                foreach($form->getElements() as $element => $attributes)  {
                                    $el =  $form->get((string) $element);
                                    $el->setAttribute('id', $addressId . '_' . $el->getAttribute('id'));
                                }

                        		$form->bind($val);
                        		$form->prepare();
                        		echo $this->form()->openTag($form);
                        		echo $this->melisFieldCollection($form);
                        		echo $this->form()->closeTag();
                    		?>
                    	</div>
                    </div>
                <?php endforeach;?>  
			</div>
		</div>
	</div>
</div>