<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    $hash = md5(time());
?>
<div class="tab-pane" <?php echo $id. ' '.$data_melisKey?>>				
	<div class="melis-product-heading border-bottom" style="margin-bottom: 20px">
		<h3><?php echo $this->translate('tr_meliscommerce_client_page_tab_company_title')?></h3>					
	</div>
	<?php 
		$form = $this->meliscommerce_clients_company_form;
		$form->prepare();

        foreach($form->getElements() as $element => $attributes)  {
            $el =  $form->get((string) $element);

            if ($el->getName() == "ccomp_logo")
                $el->setAttribute('id', $el->getName() . $hash);
        }

		echo $this->form()->openTag($form);
		echo $this->melisFieldCollection($form);
    ?>
        <div class="client-company-preview" style="<?= (! empty($this->ccomp_logo)) ? '' : 'display:none;' ?>">
            <span style="width:350px;">
                <img
                    class="client-company-thumbnail img-thumbnail"
                    width="300"
                    src="<?= (! empty($this->ccomp_logo)) ? $this->ccomp_logo : '' ?>"
                    style="margin-right: auto; margin-left: auto; display:block;"
                    data-img="<?= (! empty($this->ccomp_logo)) ? $this->ccomp_logo : '' ?>"
                >
            </span>
            <span class="remove-company-image"><i class="fa fa-close"></i></span>
        </div>
    <?php
		echo $this->form()->closeTag();
        echo $this->datePickerInit;
	?>
</div>
<script type="text/javascript">
    $('#ccomp_logo<?= $hash ?>').filestyle({
        buttonBefore: true,
        input: true,
        buttonText: 'Image'
    });
</script>