<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?>>
	<div class="pdc-content">
        <?php
        $countryFlag = false;
        $groupFlag = false;
        $name = false;
        $tags = false;

        $form = $this->meliscommerce_clients_main_form;
        $form->prepare();
        echo $this->form()->openTag($form);
        foreach ($form->getElements() As $key => $val)
        {
            if($key == 'cli_name' && !$name){
                echo '<h4 class="'.$key.'"><span class="fa fa-user"></span> '.$val->getLabel().'</h4>';
                $name = true;
            }

            if($key == 'cli_group_id' && !$groupFlag){
                echo '<h4 class="'.$key.'"><span class="fa fa-user-times"></span> '.$val->getLabel().'</h4>';
                $groupFlag = true;
            }

            if($key == 'cli_country_id' && !$countryFlag){
                echo '<h4 class="'.$key.'"><span class="fa fa-flag"></span> '.$val->getLabel().'</h4>';
                $countryFlag = true;
            }

            if($key == 'cli_tags' && !$tags){
                echo '<h4 class="'.$key.'"><span class="fa fa-tags"></span> '.$val->getLabel().'</h4>';
                $tags = true;
            }

            echo '<div class="form-group">';
            echo $this->formElement($val, array('class' => 'form-control'));
            echo '</div>';
        }
        echo $this->form()->closeTag();
        ?>
	</div>
	<form id="deletedClientAddress" class="hidden"></form>
</div>
<script>
    $(document).ready(function(){
        $("#id_meliscommerce_clients_main_form #cli_tags").tagsinput({
            allowDuplicates: false
        });
    });
</script>