<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    $hash = md5(time());
?>
<div class="tab-pane" <?php echo $id. ' '.$data_melisKey?>>				
	<div class="melis-product-heading border-bottom" style="margin-bottom: 20px">
		<h3><?php echo $this->translate('tr_meliscommerce_client_page_tab_company_title')?></h3>					
	</div>
	<?php 
		$form = $this->meliscommerce_clients_company_form;
		$form->prepare();

        foreach($form->getElements() as $element => $attributes)  {
            $el =  $form->get((string) $element);

            if ($el->getName() == "ccomp_logo")
                $el->setAttribute('id', $el->getName() . $hash);
        }

		echo $this->form()->openTag($form);
		echo $this->melisFieldCollection($form);
    ?>
        <div>
            <span class="thumbnail">
                <img
                    class="client-company-thumbnail"
                    width="300"
                    src="<?= (! empty($this->ccomp_logo)) ? $this->ccomp_logo : '/MelisFront/plugins/images/default.jpg' ?>"
                    alt="<?= $this->translate('tr_meliscore_tool_user_usr_profile_image'); ?>"
                    style="margin-right: auto; margin-left: auto; display:block;"
                >
            </span>
        </div>
    <?php
		echo $this->form()->closeTag();
        echo $this->datePickerInit;
	?>
</div>
<script type="text/javascript">
    $('#ccomp_logo<?= $hash ?>').filestyle({
        buttonBefore: true,
        input: true,
        buttonText: 'Image'
    });
</script>