<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="page-head-container">
	<div class="me-heading bg-white innerAll" <?php echo $id.' '.$data_melisKey; ?>>      		
		<div class="row">
			<div class="me-hl col-xs-12 col-md-9">
				<h1 class="content-heading"><?php echo $this->escapeHtml($this->title) ?></h1>
			</div>
			<div class="me-hl col-xs-12 col-md-3" align="right">
				<?php 
					if(!empty($this->zoneconfig['interface'])) {
						foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
							echo $this->$keyConfig.' ';
						}
					}
				?>
			</div>
		</div>       		
	</div>
</div>