<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="tab-pane" <?php echo $id. ' '.$data_melisKey?>>				
	<div class="melis-product-heading border-bottom" style="margin-bottom: 20px">
		<h3><?php echo $this->translate('tr_meliscommerce_client_page_tab_company_title')?></h3>					
	</div>
	<?php 
		$form = $this->meliscommerce_clients_company_form;
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->melisFieldCollection($form);
		echo $this->form()->closeTag();
	?>
</div>