<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?>>
	<div class="pdc-content">
        <?php
        $countryFlag = false;
        $groupFlag = false;

        $form = $this->meliscommerce_clients_main_form;
        $form->prepare();
        echo $this->form()->openTag($form);
        foreach ($form->getElements() As $key => $val)
        {
            if($key == 'cli_group_id' && !$groupFlag){
                echo '<h4><span class="fa fa-user-times"></span> '.$this->translate('tr_meliscommerce_clients_group_common_group').'</h4>';
                $groupFlag = true;
            }

            if($key == 'cli_country_id' && !$countryFlag){
                echo '<h4><span class="fa fa-flag"></span> '.$this->translate('tr_meliscommerce_client_Client_country').'</h4>';
                $countryFlag = true;
            }

            echo '<div class="form-group">';
            echo $this->formElement($val, array('class' => 'form-control'));
            echo '</div>';
        }
        echo $this->form()->closeTag();
        ?>
	</div>
	<form id="deletedClientAddress" class="hidden"></form>
</div>