<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->clientId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="tab-pane <?php echo $this->activateTab ?>" <?php echo $id. ' '.$data_melisKey?>>				
	<div class="melis-product-heading border-bottom" style="margin-bottom: 20px">
		<h3><?php echo $this->translate('tr_meliscommerce_client_page_tab_orders_title')?></h3>					
	</div>
	<?php 
    	$this->melisGenericTable()->setTable(array(
    	    'id' => $this->clientId.'_tableClientOrderList',
    	    'class' => 'table table-striped table-primary dt-responsive nowrap',
            'data-clientid' => $this->clientId,
    	    'cellspacing' => '0',
    	    'width' => '100%'
    	));
    	
    	$columns = array();
    	$columnStyle = array();
    	foreach($this->tableColumns as $columnText){
    	    $columns[] = $columnText['text'];
    	}
    	
    	$this->melisGenericTable()->setColumns($columns);
    	
    	echo $this->melisGenericTable()->renderTable();
	?>
	<script>
    	$(document).ready(function() {
    		<?php echo $this->getToolDataTableConfig; ?>
		});
	</script>
</div>