import { mergeDict } from '../../shared/i18n'

/** Dictionnaire de l'outil Devises (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Devises',
    subtitle: 'Retrouvez ici les différentes devises. Vous pouvez activer/désactiver, ajouter ou supprimer des devises et définir la devise par défaut en fonction des besoins de vos sites. La devise par défaut ne peut pas être supprimée.',
    new: 'Ajouter une devise', search_placeholder: 'Rechercher une devise…',
    filter_status: 'Tous les statuts',
    btn_export: 'Exporter', btn_col_manager: 'Colonnes',
    exp_title: 'Exporter les devises', exp_subtitle: '{n} devises seront exportées', exp_filename: 'devises',
    col_id: 'ID', col_default: 'Défaut', col_status: 'Statut', col_symbol: 'Symbole', col_code: 'Code', col_name: 'Nom', col_action: 'Action',
    no_items: 'Aucune devise trouvée.', count: '{n} devises — fin de la liste',
    field_name: 'Nom', field_code: 'Code', field_symbol: 'Symbole',
    make_default: 'Définir par défaut',
    err_name_required: 'Veuillez saisir le nom de la devise',
    err_code_required: 'Veuillez saisir le code de la devise',
    err_code_exists: 'Ce code de devise existe déjà',
    err_symbol_required: 'Veuillez saisir le symbole de la devise',
    del_title: 'Supprimer la devise',
    del_confirm: 'Êtes-vous sûr de vouloir supprimer cette devise ?',
    err_default_delete: 'La devise par défaut ne peut pas être supprimée.',
    status_label: 'STATUT', yes: 'Oui', no: 'Non',
  },
  en: {
    title: 'Currencies',
    subtitle: 'Find here the different currencies. You can activate/deactivate, add or delete currencies and define the default currency depending on the needs of your sites. The default currency cannot be deleted.',
    new: 'Add currency', search_placeholder: 'Search a currency…',
    filter_status: 'All statuses',
    btn_export: 'Export', btn_col_manager: 'Columns',
    exp_title: 'Export currencies', exp_subtitle: '{n} currencies will be exported', exp_filename: 'currencies',
    col_id: 'ID', col_default: 'Default', col_status: 'Status', col_symbol: 'Symbol', col_code: 'Code', col_name: 'Name', col_action: 'Action',
    no_items: 'No currency found.', count: '{n} currencies — end of list',
    field_name: 'Name', field_code: 'Code', field_symbol: 'Symbol',
    make_default: 'Set as default currency',
    err_name_required: 'Please enter the name of the currency',
    err_code_required: 'Please enter the code of the currency',
    err_code_exists: 'Currency code already exists, please choose another',
    err_symbol_required: 'Please enter the symbol of the currency',
    del_title: 'Delete currency',
    del_confirm: 'Are you sure you want to remove this currency?',
    err_default_delete: 'The default currency cannot be deleted.',
    status_label: 'STATUS', yes: 'Yes', no: 'No',
  },
})
