<?php 
$name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
?>
<a data-toggle="modal" data-target="#addImage" class="btn btn-success" title="<?php echo $name; ?>">
	<i class="fa fa-camera" style="padding-right:10px;"></i>
	<?php echo $name; ?>
</a>
	  <div class="modal fade" id="addImage" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title">
	          	<i class="fa fa-camera"></i>
	          	Add New Image
	          </h4>
	        </div>
	        <div class="modal-contet-cont">
		        <div class="">
		          <form method="POST" name="pageseo" id="1_idformpageseo" action="/MelisCms/PageSeo/saveSeo?idPage=1">
					<fieldset id="1_idformpageseo">
						
						<div class="form-group">
							<label for="1_pseo_meta_title">Image Link</label>
							<input type="file" class="form-control file-control">
						</div>
						
						<div class="form-group">
							<label for="id_usr_status" style="color: rgb(104, 104, 104);">Image Type</label>
							<select name="usr_status" id="id_usr_status" class="form-control">
								<option value="" selected="selected">Choose</option>
								<option value="0">Default</option>
								<option value="1">Small</option>
								<option value="1">Large</option>
								<option value="1">Top</option>
							</select>
						</div>
						
						<div class="form-group">
							<label for="id_usr_status" style="color: rgb(104, 104, 104);">Set Image For Country</label>
							<select name="usr_status" id="id_usr_status" class="form-control">
								<option value="" selected="selected">Choose</option>
								<option value="0">France</option>
								<option value="1">USA</option>
								<option value="1">China</option>
								<option value="1">UK</option>
							</select>
						</div>

					</fieldset>
				</form>
		        </div>
		        <div class="modal-footer">
		          <button type="button" class="btn btn-success pull-left" data-dismiss="modal">Save</button>
		          <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Close</button>
		        </div>
	        </div>
	      </div>	      
	    </div>
	  </div>	 