<?php 
$name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
$icon = '';
    if (!empty($this->zoneconfig['conf']['icon'])){
        $icon = $this->zoneconfig['conf']['icon'];
    }   
?>
<a data-bs-toggle="modal" data-bs-target="#addCountry" class="btn btn-success float-right">
	<i class="<?php echo $icon; ?>" style="padding-right:10px;"></i><?php echo $name; ?>
</a>