<?php 
$id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = ' id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] . '"';
    }
$active = '';
    if (!empty($this->zoneconfig['conf']['active'])){
        $active = $this->zoneconfig['conf']['active'];
}

?>
<div <?= $id; ?> class="<?= $active;?> tab-pane">
	<?php 
    	if(!empty($this->zoneconfig['interface'])) {
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
    	        echo $this->$keyConfig.' ';
    	    }
    	}
    ?>
</div>