<div class="portfolioContainer">					 
	<div class="a objects france">					    	
		<div class="me-p-image">
		   <img src="html/ecommerce/images/gallery-2/15.jpg">						       
		   <div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
	   </div>
	   
	</div>
 
	<div class="a people places usa">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/2.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>					 
	<div class="a food">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/3.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a href="#">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>					     
	<div class="a people places france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/4.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
 
	<div class="a places objects">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/3.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
 
	<div class="a people food objects usa">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/5.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image" >
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
 
	<div class="a food objects">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/8.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>    
	 
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/avatar-large-girl.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>   
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/6.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>  
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/7.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div> 
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/1.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>    
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/1.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
</div>


	  <!--VIEW IMAGE Modal -->
	<div class="modal fade" id="viewImage" role="dialog">
	    <div class="modal-dialog">	    
	      <!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
				  <button type="button" class="close" data-dismiss="modal">&times;</button>
				  <h4 class="modal-title">
					<i class="fa fa-camera"></i>
					View Image
				  </h4>
				</div>
				<div class="modal-contet-cont">
					<div class="">
						<h4>Image Title</h4>
						<img src="html/ecommerce/images/fashion/female/2.jpg" style="border-radius: 3px;" width="570">
					</div>
					<div class="modal-footer">
						<p>Image Description Lorem ipsum dolor</p>
					</div>
				</div>
			</div>	      
	    </div>
	</div>
	
	
		  <!--EDIT IMAGE Modal -->
	  <div class="modal fade" id="editImage" role="dialog">
	    <div class="modal-dialog">	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title">
	          	<i class="fa fa-camera"></i>
	          	Edit Image
	          </h4>
	        </div>
	        <div class="modal-contet-cont">
		        <div class="">
		          <form method="POST" name="editImage" id="1_idformpageseo" action="">
					<fieldset id="1_idformpageseo">
						
						<div class="form-group">
							<label for="1_pseo_meta_title">Image Link</label>
							<input type="file" class="form-control file-control">
						</div>
						
						<div class="form-group">
							<label for="id_usr_status" style="color: rgb(104, 104, 104);">Image Type</label>
							<select name="usr_status" id="id_usr_status" class="form-control">
								<option value="" selected="selected">Choose</option>
								<option value="0">Default</option>
								<option value="1">Small</option>
								<option value="1">Large</option>
								<option value="1">Top</option>
							</select>
						</div>
						
						<div class="form-group">
							<label for="id_usr_status" style="color: rgb(104, 104, 104);">Set Image For Country</label>
							<select name="usr_status" id="id_usr_status" class="form-control">
								<option value="" selected="selected">Choose</option>
								<option value="0">France</option>
								<option value="1">USA</option>
								<option value="1">China</option>
								<option value="1">UK</option>
							</select>
						</div>

					</fieldset>
				</form>
		        </div>
		        <div class="modal-footer">
		          <button type="button" class="btn btn-success pull-left" data-dismiss="modal">Save</button>
		          <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Close</button>
		        </div>
	        </div>
	      </div>
	      
	    </div>
	  </div> 

