<?php 
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = ' data-meliskey="'. $this->melisKey. '"';
	
?>
<div class="melis-product-heading border-bottom" <?php echo $id. ' '. $data_melisKey; ?>>
	<?php 
    	if(!empty($this->zoneconfig['interface'])) {
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
    	        echo $this->$keyConfig;
    	    }
    	}
    	
	?>
</div>

				