 <?php 
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] . '"';

	$data_melisKey = ' data-meliskey="'. $this->melisKey. '"';
	$name = '';
	if (!empty($this->zoneconfig['conf']['name']))
	    $name = $this->zoneconfig['conf']['name'];
	
    $active = '';
    if (!empty($this->zoneconfig['conf']['active']))
        $active = $this->zoneconfig['conf']['active'];
    
    $href = '';
    if (!empty($this->zoneconfig['conf']['href']))
        $href = '#'.$this->productId.'_'.$this->zoneconfig['conf']['href'];
    
    $icon = '';
    if (!empty($this->zoneconfig['conf']['icon']))
        $icon = $this->zoneconfig['conf']['icon'];

?>
<li class="nav-item <?= $active;?>" <?php echo $id. ' '. $data_melisKey;?>>
	<a data-bs-toggle="tab" href="<?= $href;?>" aria-expanded="true" class="nav-link <?= $icon;?>">
		<i class=""></i>
		<span><?= $this->translate($name); ?></span>
	</a>
</li>