<?php 
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = ' data-meliskey="'. $this->melisKey. '"';
    

?>
<div class="page-head-container">
	<div class="me-heading bg-white border-bottom innerAll" <?php echo $id. ' '. $data_melisKey?>>      		
		<div class="row">
			<?php 
				if(!empty($this->zoneconfig['interface'])) {
					foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
						echo $this->$keyConfig;
					}
				}
				
			?>		
		</div>
	</div>
</div>