<?php 
$id ='';
if (!empty($this->zoneconfig['conf']['id'])){
    $id = $this->productId.'_'.$this->zoneconfig['conf']['id'];
}

$formText = $this->productTextForm;
$formText->setAttribute('data-modalForm', $this->productId.'_productTextForm');
$formText->get('ptxt_id')->setAttribute('style', 'display: none')->setLabel('');
$formText->get('ptxt_lang_id')->setAttribute('style', 'display: none')->setLabel('');
$formText->get('ptxt_field_short')->setAttribute('style', 'display: none')->setLabel('');
$formText->get('ptxt_field_long')->setAttribute('style', 'display: none')->setLabel('');
$content = '<div id="'.$id.'" data-melisKey="'.$this->melisKey.'">'.
    '<h4>'.$this->translate('tr_meliscommerce_products_add_product_text').'</h4>'.
    '<div data-class="addTextFieldNotif"></div>'.
    $this->form()->openTag($formText).
    $this->melisFieldCollection($formText).
    $this->form()->closeTag() . '</div>';

echo $content;

?>
<script type="text/javascript">
    $(function() {
        reInitProductTextTypeSelect();
    })
</script>
