<?php 
$refVal = '';
$data = array();
if(isset($this->layout()->product->prd_reference))
    $data = (array) $this->layout()->product;
?>
<div>
    <br/>
    <h4><i class="fa fa-asterisk"></i> <?= $this->translate('tr_meliscommerce_products_reference'); ?></h4>
    
    <div class="pdc-content border-bottom">
        <?php 
        $form = $this->referenceForm;
        $form->setData($data);
        echo $this->form()->openTag($form);
        echo $this->melisFieldCollection($form);
        echo $this->form()->closeTag();
        ?>
    </div>
</div>