<?php 
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = ' data-meliskey="'. $this->melisKey. '"';
	$name = '';
	if (!empty($this->zoneconfig['conf']['name']))
	    $name = $this->zoneconfig['conf']['name'];

?>
<div class="me-hr col-xs-12 col-md-3" <?php echo $id. ' '.$data_melisKey;?>>
	<?php 
    	if(!empty($this->zoneconfig['interface'])) {
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
    	        echo $this->$keyConfig;
    	    }
    	}
    	
	?>	
</div>