<div>
    <div class="pdc-heading clearfix">
        <h4><i class="fa fa-link"></i> <?= $this->translate('tr_meliscommerce_products_page_page_association'); ?></h4>
    </div>
    <?php
        $form = $this->pageAssociationsForm;
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->melisFieldCollection($form);
        echo $this->form()->closeTag();
    ?>
    <div class="pdc-content border-bottom"></div>
</div>