<?php 
$name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
$icon = '';
    if (!empty($this->zoneconfig['conf']['icon'])){
        $icon = $this->zoneconfig['conf']['icon'];
    }   
$img = '';
    if (!empty($this->zoneconfig['conf']['img'])){
        $img = $this->zoneconfig['conf']['img'];
    }
$active = 'active';
$ctr = 0;
    ?>
<?php 
foreach($this->lang as $lang):

$href = $this->layout()->productId . '_id_meliscommerce_products_page_content_tab_text_language_list_field_'.$lang->elang_locale;
if($ctr>0){
    $active = '';
}
?>

<li class="nav-item <?= $active ?>" id="languageList">
	<a class="nav-link clearfix" data-bs-toggle="tab" href="#<?php echo $href;?>" aria-expanded="true">
        <?php
        $imageData = $lang->elang_flag;
        if(!empty($imageData)){
            echo '<span class="float-right"><img src="data:image/jpeg;base64,'. ($imageData) .'" class="imgDisplay float-right"/></span>';
        }else{
            echo '<i class="fa fa-globe"></i>';
        }
        
        ?>
		<span><?php echo $lang->elang_name;?></span>
	</a>
</li>

<?php 
$ctr++;
endforeach;
?>