<?php 
$id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = ' id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] . '"';
    }

$icon = '';
    if (!empty($this->zoneconfig['conf']['icon'])){
        $icon = $this->zoneconfig['conf']['icon'];
    }
$name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
$productId = $this->productId;
?>
<br>
<div class="form-group">
	<label>
		<i class="fa fa-info-circle fa-lg" data-toggle="tooltip" data-placement="left" title="" data-original-title="<?= $this->translate('tr_meliscommerce_attribute_input tooltip')?>"></i>
	</label>
</div>
<div class="ui-widget" <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
	

    <select placeholder="<?php echo $this->translate('tr_meliscommerce_products_main_tab_attributes_content_label');?>"style="display:none" class="form-control dropdown-input<?= $this->productId; ?>" name="prodAttrib" id="<?= $this->productId; ?>_prodAttribInput">
    <option value=""><?php echo $this->translate('tr_meliscommerce_products_main_tab_attributes_content_label'); ?></option>
    <?php
    foreach($this->attributes as $attribute) {
        echo '<option value="'.$attribute['id'].'">'.$attribute['text'].'</option>';
    }
    ?>

    </select>
    <div class="loadAttrCont"><?php echo $this->translate('tr_meliscommerce_products_attributes_lists_loading'); ?></div>

    <script>
        $(function() {
            var attributeLists = $('select.dropdown-input<?php echo $productId; ?>');
            $('div.loadAttrCont').hide();
            attributeLists.fadeIn();
            attributeLists.select2({
                placeholder: '<?php echo $this->translate('tr_meliscommerce_products_main_tab_attributes_content_label'); ?>',
            });
        });
    </script>
</div>	
