<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = ' id="'.$this->productId.'_'.$this->zoneconfig['conf']['id'] . '"';
    }
    
    $name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
    
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<a class="btn btn-default add-product" <?php echo $id.' '.$data_melisKey; ?>><?php echo $this->translate($name);?></a>