<?php 
$icon = '';
    if (!empty($this->zoneconfig['conf']['icon'])){
        $icon = $this->zoneconfig['conf']['icon'];
    }
?>
<div class="me-file-cont">
	<p>awesomefile.attached-here.pdf 
		<i class="<?php echo $icon ?>" ></i>
	</p>								
	<p>shirt-collection01.doc 
		<i class="<?php echo $icon ?>" ></i>
	</p>								
	<p>product-documentations-guide.pdf 
		<i class="<?php echo $icon ?>" ></i>
	</p>								
</div>	