<?php 
$name = '';
$id = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
    
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = $this->productId.'_'.$this->zoneconfig['conf']['id'];
    }
?>

<a data-bs-toggle="modal" data-bs-target="#<?= $this->productId; ?>_modal-add-product-text" class="btn btn-success add-product-text" title="<?= $name; ?>">
	<i class="fa fa-plus" style="padding-right:10px;"></i>
	<?= $this->translate('tr_meliscommerce_products_add_product_text'); ?>
</a>
