-- MySQL Script generated by MySQL Workbench
-- 11/22/16 11:58:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MelisCommerceV2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_ecom_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Category ID',
  `cat_father_cat_id` INT NOT NULL DEFAULT -1 COMMENT 'The id of the parent\'s category. If first category, -1',
  `cat_order` INT NOT NULL DEFAULT 1 COMMENT 'Displaying order',
  `cat_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active / not active',
  `cat_reference` VARCHAR(45) NULL COMMENT 'Reference of the category',
  `cat_date_valid_start` DATETIME NULL COMMENT 'Starting datetime for showing the category',
  `cat_date_valid_end` DATETIME NULL COMMENT 'Ending datetime for showing the category',
  `cat_date_creation` DATETIME NOT NULL COMMENT 'Creation date of this category',
  `cat_user_id_creation` INT NOT NULL COMMENT 'BO user who created this category',
  `cat_date_edit` DATETIME NULL COMMENT 'Last edition date',
  `cat_user_id_edit` INT NULL COMMENT 'Last BO user who created this category',
  PRIMARY KEY (`cat_id`),
  INDEX `father_idx` (`cat_father_cat_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the categories of the ecommerce database';


-- -----------------------------------------------------
-- Table `melis_ecom_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_lang` (
  `elang_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Lang id for all the commerce module',
  `elang_locale` VARCHAR(45) NOT NULL COMMENT 'Lang\'s locale',
  `elang_name` VARCHAR(45) NOT NULL COMMENT 'Lang\'s name',
  `elang_status` TINYINT(1) NULL,
  PRIMARY KEY (`elang_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the languages available for the ecommerce translations';


-- -----------------------------------------------------
-- Table `melis_ecom_category_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_category_trans` (
  `catt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Category translation Id',
  `catt_category_id` INT NOT NULL COMMENT 'Category Id',
  `catt_lang_id` INT NOT NULL COMMENT 'Lang Id',
  `catt_name` VARCHAR(100) NOT NULL COMMENT 'Name of the category in the given lang',
  `catt_description` TEXT NULL COMMENT 'Description of the category in the given lang',
  PRIMARY KEY (`catt_id`),
  INDEX `category_idx` (`catt_category_id` ASC),
  INDEX `lang_idx` (`catt_lang_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the translations of categories';


-- -----------------------------------------------------
-- Table `melis_ecom_currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_currency` (
  `cur_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Currency Id',
  `cur_default` TINYINT(1) NULL DEFAULT 0 COMMENT 'Default currency',
  `cur_name` VARCHAR(45) NOT NULL COMMENT 'Currency name',
  `cur_code` VARCHAR(8) NOT NULL COMMENT 'Currency code',
  `cur_symbol` VARCHAR(5) NOT NULL COMMENT 'Currency symbol',
  `cur_status` TINYINT(1) NULL,
  PRIMARY KEY (`cur_id`))
ENGINE = InnoDB
COMMENT = 'This tables stores the currency used in melis Ecommerce';


-- -----------------------------------------------------
-- Table `melis_ecom_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_country` (
  `ctry_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Country Id',
  `ctry_name` VARCHAR(45) NOT NULL COMMENT 'Country name',
  `ctry_currency_id` INT NOT NULL COMMENT 'Currency used in the country',
  `ctry_status` TINYINT(1) NULL,
  `ctry_flag` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ctry_id`),
  INDEX `currency_idx` (`ctry_currency_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the countries';


-- -----------------------------------------------------
-- Table `melis_ecom_country_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_country_category` (
  `ccat_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Id of table entry',
  `ccat_category_id` INT NOT NULL COMMENT 'Category id',
  `ccat_country_id` INT NOT NULL COMMENT 'Country id',
  PRIMARY KEY (`ccat_id`),
  INDEX `country_idx` (`ccat_country_id` ASC),
  INDEX `category_idx` (`ccat_category_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the relation between categories and countries';


-- -----------------------------------------------------
-- Table `melis_ecom_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_product` (
  `prd_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Product Id',
  `prd_reference` VARCHAR(45) NULL COMMENT 'Reference for this product',
  `prd_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active / Not acitve',
  `prd_date_creation` DATETIME NOT NULL COMMENT 'Creation date of this product',
  `prd_user_id_creation` INT NOT NULL COMMENT 'BO user who created this product',
  `prd_date_edit` DATETIME NULL COMMENT 'Last edit date of this product',
  `prd_user_id_edit` INT NULL COMMENT 'Last BO User who edited this product',
  PRIMARY KEY (`prd_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the products';


-- -----------------------------------------------------
-- Table `melis_ecom_variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_variant` (
  `var_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Variant Id, final product which is really sold',
  `var_prd_id` INT NOT NULL COMMENT 'Product Id of the variant',
  `var_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active / Not active',
  `var_sku` VARCHAR(100) NULL COMMENT 'SKU of the variant, unique selling code',
  `var_main_variant` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Determines if the variant is the main one for pushing it on top or using its image in display',
  `var_date_creation` DATETIME NOT NULL COMMENT 'Creation date of the variant',
  `var_user_id_creation` INT NOT NULL COMMENT 'BO user Id who created the variant',
  `var_date_edit` DATETIME NULL COMMENT 'Last edit date of the variant',
  `var_user_id_edit` INT NULL COMMENT 'Last BO user who edited the variant',
  PRIMARY KEY (`var_id`),
  INDEX `product_idx` (`var_prd_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the variants';


-- -----------------------------------------------------
-- Table `melis_ecom_product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_product_category` (
  `pcat_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Relation product category Id',
  `pcat_prd_id` INT NOT NULL COMMENT 'Product Id',
  `pcat_cat_id` INT NOT NULL COMMENT 'Category Id',
  `pcat_order` INT NOT NULL COMMENT 'Number for displaying product in a specific order',
  PRIMARY KEY (`pcat_id`),
  INDEX `product_idx` (`pcat_prd_id` ASC),
  INDEX `category_idx` (`pcat_cat_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the relation between categories ans products';


-- -----------------------------------------------------
-- Table `melis_ecom_product_text_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_product_text_type` (
  `ptt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Text\'s type Id',
  `ptt_code` VARCHAR(45) NOT NULL COMMENT 'Code for the type, ex \'TITLE\' or \'DESCRIPTION\'',
  `ptt_name` VARCHAR(255) NOT NULL COMMENT 'Name of the type',
  `ptt_field_type` INT NOT NULL COMMENT '1 for short text, 2 for long text',
  PRIMARY KEY (`ptt_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the type of product text';


-- -----------------------------------------------------
-- Table `melis_ecom_product_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_product_text` (
  `ptxt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Product\'s translation Id',
  `ptxt_prd_id` INT NOT NULL COMMENT 'Product Id',
  `ptxt_lang_id` INT NOT NULL COMMENT 'Lang Id',
  `ptxt_type` INT NOT NULL COMMENT 'Type of the text. The type is used to define different text zones and be able to find them easily',
  `ptxt_field_short` VARCHAR(255) NULL COMMENT 'Varchar field to be used if text is short',
  `ptxt_field_long` TEXT NULL COMMENT 'Text field to be used if text is long',
  PRIMARY KEY (`ptxt_id`),
  INDEX `product_idx` (`ptxt_prd_id` ASC),
  INDEX `lang_idx` (`ptxt_lang_id` ASC),
  INDEX `type_idx` (`ptxt_type` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the texts associated with the products';


-- -----------------------------------------------------
-- Table `melis_ecom_variant_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_variant_stock` (
  `stock_id` INT NOT NULL AUTO_INCREMENT,
  `stock_var_id` INT NOT NULL,
  `stock_country_id` INT NOT NULL DEFAULT 0,
  `stock_quantity` INT NULL DEFAULT 0,
  `stock_next_fill_up` DATETIME NULL,
  PRIMARY KEY (`stock_id`),
  INDEX `variant_idx` (`stock_var_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stocks the stocks of a variant';


-- -----------------------------------------------------
-- Table `melis_ecom_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_price` (
  `price_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Price Id for the product',
  `price_prd_id` INT NULL COMMENT 'Product Id, if all variants have the same price',
  `price_var_id` INT NULL COMMENT 'Variant Id, if variants have different prices',
  `price_country_id` INT NOT NULL DEFAULT 0 COMMENT 'Country Id if the price is different per country',
  `price_currency` INT NOT NULL COMMENT 'Currency of the price',
  `price_net` DECIMAL(10,2) NULL COMMENT 'Net price, all-in',
  `price_gross` DECIMAL(10,2) NULL COMMENT 'Gross price, without taxes',
  `price_vat_percent` DECIMAL(10,2) NULL COMMENT 'Percentage of VAT for this product',
  `price_vat_price` DECIMAL(10,2) NULL COMMENT 'VAT price',
  `price_other_tax_price` DECIMAL(10,2) NULL COMMENT 'Any other taxes to add',
  PRIMARY KEY (`price_id`),
  INDEX `product_idx` (`price_prd_id` ASC),
  INDEX `variant_idx` (`price_var_id` ASC),
  INDEX `country_idx` (`price_country_id` ASC),
  INDEX `cuurency_idx` (`price_currency` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the price of the product or variant';


-- -----------------------------------------------------
-- Table `melis_ecom_doc_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_doc_type` (
  `dtype_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Document type Id',
  `dtype_code` VARCHAR(10) NOT NULL COMMENT 'Document code Id, \'IMG\', or \'LARGE\' for a subtype',
  `dtype_name` VARCHAR(45) NOT NULL COMMENT 'Name of the document type, ex \'Image\'',
  `dtype_parent_type_id` INT NULL DEFAULT 0,
  PRIMARY KEY (`dtype_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the different type sof documents that can be saved\n';


-- -----------------------------------------------------
-- Table `melis_ecom_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_document` (
  `doc_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Document Id',
  `doc_name` VARCHAR(255) NOT NULL COMMENT 'Document name',
  `doc_path` VARCHAR(255) NOT NULL COMMENT 'Document Path',
  `doc_type_id` INT NOT NULL COMMENT 'Document type Id, ex \'IMG\' or \'PDF\'',
  `doc_subtype_id` INT NULL COMMENT 'Document subtype Id, ex \'LARGE\' for \'IMG\' type',
  PRIMARY KEY (`doc_id`),
  INDEX `type_idx` (`doc_type_id` ASC),
  INDEX `type2_idx` (`doc_subtype_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the images used in the ecommerce';


-- -----------------------------------------------------
-- Table `melis_ecom_doc_relations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_doc_relations` (
  `rdoc_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Relation Document Id',
  `rdoc_doc_id` INT NOT NULL COMMENT 'Document id',
  `rdoc_category_id` INT NULL COMMENT 'Category Id',
  `rdoc_product_id` INT NULL COMMENT 'Product Id',
  `rdoc_variant_id` INT NULL COMMENT 'Variant Id',
  `rdoc_country_id` INT NULL COMMENT 'Country Id',
  PRIMARY KEY (`rdoc_id`),
  INDEX `document_idx` (`rdoc_doc_id` ASC),
  INDEX `category_idx` (`rdoc_category_id` ASC),
  INDEX `product_idx` (`rdoc_product_id` ASC),
  INDEX `variant_idx` (`rdoc_variant_id` ASC),
  INDEX `country_idx` (`rdoc_country_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the relations between the documents and products, variants, categories, countries';


-- -----------------------------------------------------
-- Table `melis_ecom_attribute_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_attribute_type` (
  `atype_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Attribute Type Id',
  `atype_name` VARCHAR(45) NOT NULL COMMENT 'Attribute name',
  `atype_column_value` VARCHAR(45) NOT NULL COMMENT 'Column used in values for saving the value of this attribute',
  PRIMARY KEY (`atype_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the type of attribute, letting user know what type of field is used for the value';


-- -----------------------------------------------------
-- Table `melis_ecom_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_attribute` (
  `attr_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Attribute Id',
  `attr_type_id` INT NOT NULL COMMENT 'Type Id of the attribute',
  `attr_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active / Not active',
  `attr_reference` VARCHAR(45) NULL COMMENT 'REference of the attribute',
  `attr_visible` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Display or not the attribute',
  `attr_searchable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Used to know if searches can use this attribute',
  PRIMARY KEY (`attr_id`),
  INDEX `type_idx` (`attr_type_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the attributes that can be used by the products';


-- -----------------------------------------------------
-- Table `melis_ecom_attribute_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_attribute_trans` (
  `atrans_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Attribute translation Id',
  `atrans_attribute_id` INT NOT NULL COMMENT 'Attribute Id',
  `atrans_lang_id` INT NOT NULL COMMENT 'Lang Id of the translation',
  `atrans_name` VARCHAR(100) NOT NULL COMMENT 'Name of the attribute',
  `atrans_description` VARCHAR(45) NULL COMMENT 'Description of the attribute',
  PRIMARY KEY (`atrans_id`),
  INDEX `attributeid_idx` (`atrans_attribute_id` ASC),
  INDEX `langid_idx` (`atrans_lang_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the translations of the attributes names';


-- -----------------------------------------------------
-- Table `melis_ecom_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_attribute_value` (
  `atval_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Attribute Value Id',
  `atval_attribute_id` INT NOT NULL COMMENT 'Attribute Id which the value is linked to',
  `atval_type_id` INT NOT NULL COMMENT 'Type of attribute',
  `atval_reference` VARCHAR(45) NULL COMMENT 'Reference of the value',
  PRIMARY KEY (`atval_id`),
  INDEX `attributeid_idx` (`atval_attribute_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the values of the attributes';


-- -----------------------------------------------------
-- Table `melis_ecom_attribute_value_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_attribute_value_trans` (
  `avt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Attribute value translation Id',
  `av_attribute_value_id` INT NOT NULL COMMENT 'Attribute Value Id of the translation',
  `avt_lang_id` INT NOT NULL COMMENT 'Lang Id of the translation',
  `avt_v_int` INT NULL COMMENT 'Saving in here if type of attribute is INT',
  `avt_v_float` FLOAT NULL COMMENT 'Saving in here if type of attribute is FLOAT',
  `avt_v_bool` TINYINT(1) NULL COMMENT 'Saving in here if type of attribute is BOOLEAN',
  `avt_v_varchar` VARCHAR(255) NULL COMMENT 'Saving in here if type of attribute is short text - varchar',
  `avt_v_text` TEXT NULL COMMENT 'Saving in here if type of attribute is long text',
  `avt_v_datetime` DATETIME NULL COMMENT 'Saving in here if type of attribute is a date',
  `avt_v_binary` LONGBLOB NULL COMMENT 'Saving in here if type of attribute is binary',
  PRIMARY KEY (`avt_id`),
  INDEX `attributevalueid_idx` (`av_attribute_value_id` ASC),
  INDEX `langid_idx` (`avt_lang_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the values of the attributes';


-- -----------------------------------------------------
-- Table `melis_ecom_product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_product_attribute` (
  `patt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Relation product Attribute Id',
  `patt_product_id` INT NOT NULL COMMENT 'Product id',
  `patt_attribute_id` INT NOT NULL COMMENT 'Attribute Id',
  PRIMARY KEY (`patt_id`),
  INDEX `product_idx` (`patt_product_id` ASC),
  INDEX `attribute_idx` (`patt_attribute_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the relation between a product and its attributes';


-- -----------------------------------------------------
-- Table `melis_ecom_variant_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_variant_attribute_value` (
  `vatv_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Relation attribute value variant Id',
  `vatv_variant_id` INT NOT NULL COMMENT 'Variant Id',
  `vatv_attribute_value_id` INT NOT NULL COMMENT 'Attribute Value Id',
  PRIMARY KEY (`vatv_id`),
  INDEX `variant_idx` (`vatv_variant_id` ASC),
  INDEX `attributevalue_idx` (`vatv_attribute_value_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the the values of the attribute for variants';


-- -----------------------------------------------------
-- Table `melis_ecom_basket_anonymous`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_basket_anonymous` (
  `bano_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Anonymous Id of this basket',
  `bano_key` VARCHAR(100) NOT NULL COMMENT 'Cookie saved key for this basket',
  `bano_variant_id` INT NOT NULL COMMENT 'Variant Id in the basket',
  `bano_quantity` INT NOT NULL DEFAULT 1 COMMENT 'Quantity of this variant in the basket',
  `bano_date_added` DATETIME NULL COMMENT 'Datetime when added to the basket',
  PRIMARY KEY (`bano_id`),
  INDEX `variant_idx` (`bano_variant_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores basket when no client is yet identified';


-- -----------------------------------------------------
-- Table `melis_ecom_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_client` (
  `cli_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Client Id',
  `cli_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active / Not active',
  `cli_country_id` INT NOT NULL COMMENT 'Country Id of the client',
  `cli_date_creation` DATETIME NOT NULL COMMENT 'Creation date of the client',
  `cli_date_edit` DATETIME NULL COMMENT 'Last edit date of the client',
  PRIMARY KEY (`cli_id`),
  INDEX `country_idx` (`cli_country_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the clients\' account';


-- -----------------------------------------------------
-- Table `melis_ecom_basket_persistent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_basket_persistent` (
  `bper_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Persistent Basket Id',
  `bper_client_id` INT NOT NULL COMMENT 'Client Id whom the basket belongs to',
  `bper_variant_id` INT NOT NULL COMMENT 'Variant Id in the basket',
  `bper_quantity` INT NOT NULL DEFAULT 1 COMMENT 'Quantity of this variant in the basket',
  `bper_date_added` DATETIME NULL COMMENT 'Datetime when this variant has been added to the basket',
  PRIMARY KEY (`bper_id`),
  INDEX `variant_idx` (`bper_variant_id` ASC),
  INDEX `client_idx` (`bper_client_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the basket of an identified client';


-- -----------------------------------------------------
-- Table `melis_ecom_civility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_civility` (
  `civ_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Civility Id',
  PRIMARY KEY (`civ_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the civilities per language and country';


-- -----------------------------------------------------
-- Table `melis_ecom_client_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_client_person` (
  `cper_id` INT NOT NULL AUTO_INCREMENT COMMENT 'client person Id, as more than one person can be affected to a client account',
  `cper_client_id` INT NOT NULL COMMENT 'client Id',
  `cper_lang_id` INT NOT NULL COMMENT 'Lang Id',
  `cper_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active / Not active',
  `cper_is_main_person` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Main contact of the client account',
  `cper_email` VARCHAR(255) NOT NULL COMMENT 'Email / Login of the person',
  `cper_password` VARCHAR(255) NOT NULL COMMENT 'Password of the person',
  `cper_password_recovery_key` VARCHAR(255) NULL COMMENT 'Hash key used for password recovery',
  `cper_civility` INT NULL COMMENT 'Civility id',
  `cper_name` VARCHAR(255) NOT NULL COMMENT 'Name of person',
  `cper_middle_name` VARCHAR(255) NULL COMMENT 'Middle name of person',
  `cper_firstname` VARCHAR(255) NOT NULL COMMENT 'Firstname of person',
  `cper_job_title` VARCHAR(80) NULL COMMENT 'Job title in the company',
  `cper_job_service` VARCHAR(80) NULL COMMENT 'Job service where person works',
  `cper_tel_mobile` VARCHAR(45) NULL COMMENT 'Mobile phone number',
  `cper_tel_landline` VARCHAR(45) NULL COMMENT 'Landline phone number',
  `cper_date_creation` DATETIME NOT NULL COMMENT 'Creation date of the person',
  `cper_date_edit` DATETIME NULL COMMENT 'Last edit date of the person',
  PRIMARY KEY (`cper_id`),
  INDEX `client_idx` (`cper_client_id` ASC),
  INDEX `lang_idx` (`cper_lang_id` ASC),
  INDEX `civility_idx` (`cper_civility` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the persons linked to a client account';


-- -----------------------------------------------------
-- Table `melis_ecom_client_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_client_company` (
  `ccomp_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Company Id',
  `ccomp_client_id` INT NOT NULL COMMENT 'Client Id whom the company is linked to',
  `ccomp_name` VARCHAR(100) NOT NULL COMMENT 'Company name',
  `ccomp_number_id` VARCHAR(150) NULL COMMENT 'Official administration number of the company',
  `ccomp_vat_number` VARCHAR(150) NULL COMMENT 'Official VAT number of the company',
  `ccomp_group` VARCHAR(100) NULL COMMENT 'Group of the company',
  `ccomp_date_creation` DATETIME NOT NULL COMMENT 'Creation date of the company',
  `ccomp_date_edit` DATETIME NULL COMMENT 'Last edit date of the company',
  PRIMARY KEY (`ccomp_id`),
  INDEX `client_idx` (`ccomp_client_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores datas about the company if need be';


-- -----------------------------------------------------
-- Table `melis_ecom_client_address_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_client_address_type` (
  `catype_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Type id of address',
  `catype_code` VARCHAR(10) NULL COMMENT 'Code if needed',
  PRIMARY KEY (`catype_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the address types';


-- -----------------------------------------------------
-- Table `melis_ecom_client_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_client_address` (
  `cadd_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Address Id',
  `cadd_client_id` INT NOT NULL COMMENT 'Client Id if the address is linked directly to the client account',
  `cadd_client_person` INT NULL COMMENT 'Client Person Id if the address is linked to a person',
  `cadd_type` INT NULL COMMENT 'Type of address, delivery, billing, ...',
  `cadd_address_name` VARCHAR(45) NOT NULL COMMENT 'Name of this address given by the client',
  `cadd_civility` INT NULL COMMENT 'Civility Id',
  `cadd_name` VARCHAR(255) NOT NULL COMMENT 'Name',
  `cadd_middle_name` VARCHAR(255) NULL COMMENT 'Middle Name',
  `cadd_firstname` VARCHAR(255) NOT NULL COMMENT 'Firstname',
  `cadd_num` VARCHAR(10) NULL COMMENT 'Number in street',
  `cadd_stairs` VARCHAR(10) NULL COMMENT 'Stairs if needed',
  `cadd_building_name` VARCHAR(45) NULL COMMENT 'Building name if needed',
  `cadd_company` VARCHAR(100) NULL COMMENT 'Company if needed',
  `cadd_street` VARCHAR(255) NULL COMMENT 'Street name',
  `cadd_zipcode` VARCHAR(15) NULL COMMENT 'Zipcode',
  `cadd_city` VARCHAR(100) NULL COMMENT 'City',
  `cadd_state` VARCHAR(50) NULL COMMENT 'State',
  `cadd_country` VARCHAR(50) NULL COMMENT 'Country',
  `cadd_complementary` VARCHAR(255) NULL COMMENT 'Optional informations',
  `cadd_phone_mobile` VARCHAR(45) NULL COMMENT 'Mobile phone number',
  `cadd_phone_landline` VARCHAR(45) NULL COMMENT 'Landline phone number',
  `cadd_creation_date` DATETIME NOT NULL COMMENT 'Creation date of this address',
  PRIMARY KEY (`cadd_id`),
  INDEX `client_idx` (`cadd_client_id` ASC),
  INDEX `clientperson_idx` (`cadd_client_person` ASC),
  INDEX `civility_idx` (`cadd_civility` ASC),
  INDEX `addresstype_idx` (`cadd_type` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the addresses of the clients';


-- -----------------------------------------------------
-- Table `melis_ecom_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_status` (
  `osta_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Order status Id',
  `osta_color_code` VARCHAR(45) NOT NULL COMMENT 'Color associated to this status',
  `osta_status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`osta_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the different status available for an order';


-- -----------------------------------------------------
-- Table `melis_ecom_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order` (
  `ord_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Order Id',
  `ord_client_id` INT NOT NULL COMMENT 'Client Id',
  `ord_client_person_id` INT NOT NULL COMMENT 'Person who made the order',
  `ord_status` INT NOT NULL COMMENT 'Order status Id',
  `ord_reference` VARCHAR(100) NOT NULL COMMENT 'Order reference',
  `ord_billing_address` INT NOT NULL COMMENT 'Order address Id for billing',
  `ord_delivery_address` INT NOT NULL COMMENT 'Order address Id for delivery',
  `ord_date_creation` DATETIME NOT NULL COMMENT 'Creation date of the order',
  PRIMARY KEY (`ord_id`),
  INDEX `status_idx` (`ord_status` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the orders made by clients';


-- -----------------------------------------------------
-- Table `melis_ecom_order_status_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_status_trans` (
  `ostt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Order status translation Id',
  `ostt_status_id` INT NOT NULL COMMENT 'Order Status Id',
  `ostt_lang_id` INT NOT NULL COMMENT 'Lang Id of the translation',
  `ostt_status_name` VARCHAR(50) NOT NULL COMMENT 'Name of the order status',
  PRIMARY KEY (`ostt_id`),
  INDEX `status_idx` (`ostt_status_id` ASC),
  INDEX `lang_idx` (`ostt_lang_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the different status translations available for an order';


-- -----------------------------------------------------
-- Table `melis_ecom_order_basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_basket` (
  `obas_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Order basket Id',
  `obas_order_id` INT NOT NULL COMMENT 'Order Id',
  `obas_variant_id` INT NOT NULL COMMENT 'Variant Id',
  `obas_product_name` VARCHAR(255) NOT NULL COMMENT 'Name of the product',
  `obas_quantity` INT NOT NULL COMMENT 'Quantity of this variant ordered',
  `obas_sent` INT NOT NULL DEFAULT 0 COMMENT 'Item(s) sent',
  `obas_sku` VARCHAR(100) NOT NULL COMMENT 'Sku of the variant',
  `obas_attributes` TEXT NULL COMMENT 'Attributes list of the variant',
  `obas_category_id` INT NULL COMMENT 'Category where the variant was affected',
  `obas_category_name` VARCHAR(255) NULL COMMENT 'Name of the category where the variant was affected',
  `obas_currency` INT NOT NULL COMMENT 'Currency id of the price of the product',
  `obas_price_net` FLOAT NOT NULL COMMENT 'Net price of the product',
  `obas_price_gross` FLOAT NULL COMMENT 'Gross price of the product',
  `obas_price_vat` FLOAT NULL COMMENT 'VAT price of the product',
  `obas_price_other_tax` FLOAT NULL COMMENT 'Other taxes price of the product',
  PRIMARY KEY (`obas_id`),
  INDEX `order_idx` (`obas_order_id` ASC),
  INDEX `variant_idx` (`obas_variant_id` ASC),
  INDEX `currency_idx` (`obas_currency` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the basket of the order';


-- -----------------------------------------------------
-- Table `melis_ecom_order_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_address` (
  `oadd_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Order address Id',
  `oadd_order_id` INT NOT NULL COMMENT 'Order Id',
  `oadd_type` INT NULL COMMENT 'Type of address, delivery or billing',
  `oadd_civility` INT NOT NULL COMMENT 'Civility Id',
  `oadd_name` VARCHAR(255) NOT NULL COMMENT 'Name',
  `oadd_middle_name` VARCHAR(255) NULL COMMENT 'Middle name',
  `oadd_firstname` VARCHAR(255) NOT NULL COMMENT 'Firstname',
  `oadd_num` VARCHAR(10) NULL COMMENT 'Number in the street',
  `oadd_stairs` VARCHAR(10) NULL COMMENT 'Stairs',
  `oadd_building_name` VARCHAR(45) NULL COMMENT 'Building Name',
  `oadd_company` VARCHAR(100) NULL COMMENT 'Company',
  `oadd_street` VARCHAR(255) NULL COMMENT 'Street',
  `oadd_zipcode` VARCHAR(15) NULL COMMENT 'Zipcode',
  `oadd_city` VARCHAR(100) NULL COMMENT 'City',
  `oadd_state` VARCHAR(50) NULL COMMENT 'State',
  `oadd_country` VARCHAR(50) NULL COMMENT 'Country',
  `oadd_complementary` VARCHAR(255) NULL COMMENT 'Optional informations',
  `oadd_phone_mobile` VARCHAR(45) NULL COMMENT 'Mobile phone number',
  `oadd_phone_landline` VARCHAR(45) NULL COMMENT 'Landline phone number',
  `oadd_creation_date` DATETIME NOT NULL COMMENT 'Creation date of the order address',
  PRIMARY KEY (`oadd_id`),
  INDEX `civility_idx` (`oadd_civility` ASC),
  INDEX `order_idx` (`oadd_order_id` ASC),
  INDEX `type_idx` (`oadd_type` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the addresses defined for the order';


-- -----------------------------------------------------
-- Table `melis_ecom_client_address_type_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_client_address_type_trans` (
  `catypt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Type translation id',
  `catypt_type_id` INT NOT NULL COMMENT 'Type id of address',
  `catypt_lang_id` INT NOT NULL COMMENT 'Lang id for translation',
  `catypt_name` VARCHAR(100) NOT NULL COMMENT 'Type\'s name, ex \'Delivery\'',
  PRIMARY KEY (`catypt_id`),
  INDEX `type_idx` (`catypt_type_id` ASC),
  INDEX `lang_idx` (`catypt_lang_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the translation of the addresses types';


-- -----------------------------------------------------
-- Table `melis_ecom_civility_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_civility_trans` (
  `civt_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Civility translation Id',
  `civt_civ_id` INT NOT NULL COMMENT 'Civility Id',
  `civt_lang_id` INT NOT NULL COMMENT 'Lang Id for translation',
  `civt_min_name` VARCHAR(45) NOT NULL COMMENT 'Abbreviation of the civility, ex \'M\'',
  `civt_max_name` VARCHAR(45) NOT NULL COMMENT 'Full translation of the civility, ex \"Madame\"',
  PRIMARY KEY (`civt_id`),
  INDEX `lang_idx` (`civt_lang_id` ASC),
  INDEX `civility_idx` (`civt_civ_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the translations of the civilities';


-- -----------------------------------------------------
-- Table `melis_ecom_order_payment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_payment_type` (
  `opty_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Payment Type Id',
  `opty_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Active / Not active',
  `opty_code` VARCHAR(10) NOT NULL COMMENT 'Code of payment, ex \'VISA\'',
  `opty_name` VARCHAR(50) NOT NULL COMMENT 'Payment name',
  PRIMARY KEY (`opty_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the different types of payment allowed';


-- -----------------------------------------------------
-- Table `melis_ecom_order_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_payment` (
  `opay_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Order Payment Id',
  `opay_order_id` INT NOT NULL COMMENT 'Order Id',
  `opay_price_total` FLOAT NOT NULL COMMENT 'Total price of the order',
  `opay_price_order` FLOAT NOT NULL COMMENT 'Price of the basket only',
  `opay_price_shipping` FLOAT NOT NULL DEFAULT 0 COMMENT 'Price of the shipping',
  `opay_currency_id` INT NOT NULL COMMENT 'Payment currency',
  `opay_payment_type_id` INT NOT NULL COMMENT 'Type of payment Id',
  `opay_transac_id` VARCHAR(100) NOT NULL COMMENT 'Transaction return Id',
  `opay_transac_return_value` VARCHAR(10) NOT NULL COMMENT 'Transaction return value',
  `opay_transac_price_paid_confirm` FLOAT NOT NULL COMMENT 'Transaction confirmed price  paid',
  `opay_transac_raw_response` TEXT NOT NULL COMMENT 'Raw transaction received undecoded',
  `opay_date_payment` DATETIME NOT NULL COMMENT 'Datetime of payment',
  PRIMARY KEY (`opay_id`),
  INDEX `order_idx` (`opay_order_id` ASC),
  INDEX `cuurency_idx` (`opay_currency_id` ASC),
  INDEX `paymentype_idx` (`opay_payment_type_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the payment datas about the order';


-- -----------------------------------------------------
-- Table `melis_ecom_order_shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_shipping` (
  `oship_id` INT NOT NULL AUTO_INCREMENT,
  `oship_order_id` INT NOT NULL,
  `oship_tracking_code` VARCHAR(100) NOT NULL,
  `oship_content` TEXT NOT NULL,
  `oship_date_sent` DATETIME NOT NULL,
  PRIMARY KEY (`oship_id`),
  INDEX `order_idx` (`oship_order_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the shipment made for orders';


-- -----------------------------------------------------
-- Table `melis_ecom_order_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_order_message` (
  `omsg_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Order message Id',
  `omsg_order_id` INT NOT NULL COMMENT 'Order Id ',
  `omsg_client_id` INT NOT NULL COMMENT 'Client id',
  `omsg_client_person_id` INT NULL COMMENT 'Client Person talking',
  `omsg_user_id` INT NOT NULL COMMENT 'BO user Id who is talking',
  `omsg_message` TEXT NOT NULL COMMENT 'Message',
  `omsg_date_creation` DATETIME NOT NULL COMMENT 'Creation date of the message',
  PRIMARY KEY (`omsg_id`),
  INDEX `order_idx` (`omsg_order_id` ASC),
  INDEX `client_idx` (`omsg_client_id` ASC),
  INDEX `clientperson_idx` (`omsg_client_person_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores messages exchanged by the client and the shop about orders';


-- -----------------------------------------------------
-- Table `melis_ecom_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_coupon` (
  `coup_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Coupon Id',
  `coup_code` VARCHAR(45) NOT NULL COMMENT 'Code of the coupon',
  `coup_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Active / Not active',
  `coup_type` INT NOT NULL COMMENT 'Type of coupon: for all or affected to a client',
  `coup_percentage` FLOAT NULL COMMENT 'Percentage of discount',
  `coup_discount_value` FLOAT NULL COMMENT 'Value of discount',
  `coup_max_use_number` INT NOT NULL COMMENT 'Max number of use',
  `coup_current_use_number` INT NOT NULL DEFAULT 0 COMMENT 'Current number of use',
  `coup_date_valid_start` DATETIME NULL COMMENT 'Start datetime of validity',
  `coup_date_valid_end` DATETIME NULL COMMENT 'End datetime of validity',
  `coup_date_creation` DATETIME NOT NULL COMMENT 'Creation date of the coupon',
  `coup_user_id` INT NOT NULL COMMENT 'BO user id who created the coupon',
  PRIMARY KEY (`coup_id`))
ENGINE = InnoDB
COMMENT = 'This table stores the coupons which can be used in the shop	';


-- -----------------------------------------------------
-- Table `melis_ecom_coupon_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_coupon_order` (
  `cord_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Relation coupon order Id',
  `cord_coupon_id` INT NOT NULL COMMENT 'Coupon Id',
  `cord_order_id` INT NOT NULL COMMENT 'Order Id',
  PRIMARY KEY (`cord_id`),
  INDEX `coupon_idx` (`cord_coupon_id` ASC),
  INDEX `order_idx` (`cord_order_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the relation between used coupons and their order';


-- -----------------------------------------------------
-- Table `melis_ecom_coupon_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_coupon_client` (
  `ccli_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Relation coupon client Id',
  `ccli_coupon_id` INT NOT NULL COMMENT 'Coupon Id',
  `ccli_client_id` INT NOT NULL COMMENT 'Client Id',
  PRIMARY KEY (`ccli_id`),
  INDEX `coupon_idx` (`ccli_coupon_id` ASC),
  INDEX `client_idx` (`ccli_client_id` ASC))
ENGINE = InnoDB
COMMENT = 'This table stores the coupons that are affected to a client';


-- -----------------------------------------------------
-- Table `melis_ecom_seo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_seo` (
  `eseo_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Ecommerce SEO id',
  `eseo_page_id` INT NOT NULL COMMENT 'The page id to redirect to',
  `eseo_category_id` INT NULL COMMENT 'Category id if seo is linked to a category',
  `eseo_product_id` INT NULL COMMENT 'Product Id if SEO is linked to product',
  `eseo_variant_id` INT NULL COMMENT 'Variant Id if SEO is linked to variant',
  `eseo_lang_id` INT NOT NULL COMMENT 'Lang id if multiple pages for 1 item',
  `eseo_url` VARCHAR(255) NULL COMMENT 'URL',
  `eseo_url_redirect` VARCHAR(255) NULL COMMENT 'Url to redirect if needed',
  `eseo_url_301` VARCHAR(255) NULL COMMENT 'Url to redirect if item offline',
  `eseo_meta_title` VARCHAR(255) NULL COMMENT 'Meta title',
  `eseo_meta_description` VARCHAR(255) NULL COMMENT 'Meta description',
  PRIMARY KEY (`eseo_id`),
  INDEX `category_id_idx` (`eseo_category_id` ASC),
  INDEX `product_id_idx` (`eseo_product_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_ecom_assoc_variants_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_assoc_variants_type` (
  `avart_id` INT NOT NULL AUTO_INCREMENT,
  `avart_code` VARCHAR(45) NOT NULL,
  `avart_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`avart_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_ecom_assoc_variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_ecom_assoc_variant` (
  `avar_id` INT NOT NULL AUTO_INCREMENT,
  `avar_to` INT NOT NULL,
  `avar_from` INT NOT NULL,
  `avar_type_id` INT NULL,
  PRIMARY KEY (`avar_id`),
  INDEX `var_id_idx` (`avar_to` ASC),
  INDEX `var_id_idx1` (`avar_from` ASC),
  INDEX `avart_id_idx` (`avar_type_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `melis_ecom_category`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_category` (`cat_id`, `cat_father_cat_id`, `cat_order`, `cat_status`, `cat_reference`, `cat_date_valid_start`, `cat_date_valid_end`, `cat_date_creation`, `cat_user_id_creation`, `cat_date_edit`, `cat_user_id_edit`) VALUES (1, -1, 1, 1, NULL, NULL, NULL, '2016-12-01 00:00:01', 1, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_lang`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_lang` (`elang_id`, `elang_locale`, `elang_name`, `elang_status`) VALUES (1, 'en_EN', 'English', NULL);
INSERT INTO `melis_ecom_lang` (`elang_id`, `elang_locale`, `elang_name`, `elang_status`) VALUES (2, 'fr_FR', 'Français', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_category_trans`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_category_trans` (`catt_id`, `catt_category_id`, `catt_lang_id`, `catt_name`, `catt_description`) VALUES (1, 1, 1, 'My catalog', NULL);
INSERT INTO `melis_ecom_category_trans` (`catt_id`, `catt_category_id`, `catt_lang_id`, `catt_name`, `catt_description`) VALUES (2, 1, 2, 'Mon catalogue', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_currency`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_currency` (`cur_id`, `cur_default`, `cur_name`, `cur_code`, `cur_symbol`, `cur_status`) VALUES (1, 0, 'EURO', 'EUR', '€', NULL);
INSERT INTO `melis_ecom_currency` (`cur_id`, `cur_default`, `cur_name`, `cur_code`, `cur_symbol`, `cur_status`) VALUES (2, 1, 'DOLLAR', 'DOL', '$', NULL);
INSERT INTO `melis_ecom_currency` (`cur_id`, `cur_default`, `cur_name`, `cur_code`, `cur_symbol`, `cur_status`) VALUES (3, 0, 'RENMINBI', 'RMB', '¥', NULL);
INSERT INTO `melis_ecom_currency` (`cur_id`, `cur_default`, `cur_name`, `cur_code`, `cur_symbol`, `cur_status`) VALUES (4, 0, 'POUND', 'GBP', '£', NULL);
INSERT INTO `melis_ecom_currency` (`cur_id`, `cur_default`, `cur_name`, `cur_code`, `cur_symbol`, `cur_status`) VALUES (5, 0, 'YEN', 'JPY', '¥', NULL);
INSERT INTO `melis_ecom_currency` (`cur_id`, `cur_default`, `cur_name`, `cur_code`, `cur_symbol`, `cur_status`) VALUES (6, 0, 'AUSTRALIAN DOLLAR', 'AUD', 'A$', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_country`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (1, 'France', 1, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (2, 'USA', 2, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (3, 'China', 3, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (4, 'United Kingdom', 4, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (5, 'Germany', 1, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (6, 'Spain', 1, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (7, 'Italy', 1, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (8, 'Japan', DEFAULT, NULL, NULL);
INSERT INTO `melis_ecom_country` (`ctry_id`, `ctry_name`, `ctry_currency_id`, `ctry_status`, `ctry_flag`) VALUES (9, 'Australia', DEFAULT, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_product_text_type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_product_text_type` (`ptt_id`, `ptt_code`, `ptt_name`, `ptt_field_type`) VALUES (1, 'TITLE', 'Title', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_doc_type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_doc_type` (`dtype_id`, `dtype_code`, `dtype_name`, `dtype_parent_type_id`) VALUES (1, 'IMG', 'Image', NULL);
INSERT INTO `melis_ecom_doc_type` (`dtype_id`, `dtype_code`, `dtype_name`, `dtype_parent_type_id`) VALUES (2, 'FILE', 'File', NULL);
INSERT INTO `melis_ecom_doc_type` (`dtype_id`, `dtype_code`, `dtype_name`, `dtype_parent_type_id`) VALUES (3, 'DEFAULT', 'Default', 1);
INSERT INTO `melis_ecom_doc_type` (`dtype_id`, `dtype_code`, `dtype_name`, `dtype_parent_type_id`) VALUES (4, 'SMALL', 'Small', 1);
INSERT INTO `melis_ecom_doc_type` (`dtype_id`, `dtype_code`, `dtype_name`, `dtype_parent_type_id`) VALUES (5, 'BIG', 'Big', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_attribute_type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_attribute_type` (`atype_id`, `atype_name`, `atype_column_value`) VALUES (1, 'Integer', 'int');
INSERT INTO `melis_ecom_attribute_type` (`atype_id`, `atype_name`, `atype_column_value`) VALUES (2, 'Decimal', 'float');
INSERT INTO `melis_ecom_attribute_type` (`atype_id`, `atype_name`, `atype_column_value`) VALUES (3, 'Boolean', 'bool');
INSERT INTO `melis_ecom_attribute_type` (`atype_id`, `atype_name`, `atype_column_value`) VALUES (4, 'Short string', 'varchar');
INSERT INTO `melis_ecom_attribute_type` (`atype_id`, `atype_name`, `atype_column_value`) VALUES (5, 'Text', 'text');
INSERT INTO `melis_ecom_attribute_type` (`atype_id`, `atype_name`, `atype_column_value`) VALUES (6, 'Date and time', 'datetime');
INSERT INTO `melis_ecom_attribute_type` (`atype_id`, `atype_name`, `atype_column_value`) VALUES (7, 'File', 'binary');

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_civility`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_civility` (`civ_id`) VALUES (1);
INSERT INTO `melis_ecom_civility` (`civ_id`) VALUES (2);
INSERT INTO `melis_ecom_civility` (`civ_id`) VALUES (3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_client_address_type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_client_address_type` (`catype_id`, `catype_code`) VALUES (1, 'BIL');
INSERT INTO `melis_ecom_client_address_type` (`catype_id`, `catype_code`) VALUES (2, 'DEL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_order_status`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_order_status` (`osta_id`, `osta_color_code`, `osta_status`) VALUES (1, '#0696cb', DEFAULT);
INSERT INTO `melis_ecom_order_status` (`osta_id`, `osta_color_code`, `osta_status`) VALUES (2, '#f08c17', DEFAULT);
INSERT INTO `melis_ecom_order_status` (`osta_id`, `osta_color_code`, `osta_status`) VALUES (3, '#06cb65', DEFAULT);
INSERT INTO `melis_ecom_order_status` (`osta_id`, `osta_color_code`, `osta_status`) VALUES (4, '#06cb65', DEFAULT);
INSERT INTO `melis_ecom_order_status` (`osta_id`, `osta_color_code`, `osta_status`) VALUES (5, '#ababab', DEFAULT);
INSERT INTO `melis_ecom_order_status` (`osta_id`, `osta_color_code`, `osta_status`) VALUES (6, '#ff3300', DEFAULT);
INSERT INTO `melis_ecom_order_status` (`osta_id`, `osta_color_code`, `osta_status`) VALUES (-1, '#00ccff', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_order_status_trans`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (1, 1, 1, 'New order');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (2, 1, 2, 'Nouvelle commande');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (3, 2, 1, 'Order on hold');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (4, 2, 2, 'Commande en attente');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (5, 3, 1, 'Order shipped');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (6, 3, 2, 'Commande envoyée');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (7, 4, 1, 'Order delivered');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (8, 4, 2, 'Commande livrée');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (9, 5, 1, 'Order canceled');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (10, 5, 2, 'Commande annulée');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (11, 6, 1, 'Error payment');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (12, 6, 2, 'Erreur paiement');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (13, -1, 1, 'Temporary');
INSERT INTO `melis_ecom_order_status_trans` (`ostt_id`, `ostt_status_id`, `ostt_lang_id`, `ostt_status_name`) VALUES (14, -1, 2, 'Temporary');

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_client_address_type_trans`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_client_address_type_trans` (`catypt_id`, `catypt_type_id`, `catypt_lang_id`, `catypt_name`) VALUES (1, 1, 1, 'Billing');
INSERT INTO `melis_ecom_client_address_type_trans` (`catypt_id`, `catypt_type_id`, `catypt_lang_id`, `catypt_name`) VALUES (2, 1, 2, 'Facturation');
INSERT INTO `melis_ecom_client_address_type_trans` (`catypt_id`, `catypt_type_id`, `catypt_lang_id`, `catypt_name`) VALUES (3, 2, 1, 'Delivery');
INSERT INTO `melis_ecom_client_address_type_trans` (`catypt_id`, `catypt_type_id`, `catypt_lang_id`, `catypt_name`) VALUES (4, 2, 2, 'Livraison');

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_civility_trans`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_civility_trans` (`civt_id`, `civt_civ_id`, `civt_lang_id`, `civt_min_name`, `civt_max_name`) VALUES (1, 1, 1, 'Mr', 'Mister');
INSERT INTO `melis_ecom_civility_trans` (`civt_id`, `civt_civ_id`, `civt_lang_id`, `civt_min_name`, `civt_max_name`) VALUES (2, 1, 2, 'M', 'Monsieur');
INSERT INTO `melis_ecom_civility_trans` (`civt_id`, `civt_civ_id`, `civt_lang_id`, `civt_min_name`, `civt_max_name`) VALUES (3, 2, 1, 'Mrs', 'Madam');
INSERT INTO `melis_ecom_civility_trans` (`civt_id`, `civt_civ_id`, `civt_lang_id`, `civt_min_name`, `civt_max_name`) VALUES (4, 2, 2, 'Mme', 'Madame');
INSERT INTO `melis_ecom_civility_trans` (`civt_id`, `civt_civ_id`, `civt_lang_id`, `civt_min_name`, `civt_max_name`) VALUES (5, 3, 1, 'Miss', 'Miss');
INSERT INTO `melis_ecom_civility_trans` (`civt_id`, `civt_civ_id`, `civt_lang_id`, `civt_min_name`, `civt_max_name`) VALUES (6, 3, 2, 'Mlle', 'Mademoiselle');

COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_ecom_order_payment_type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_ecom_order_payment_type` (`opty_id`, `opty_status`, `opty_code`, `opty_name`) VALUES (1, 1, 'VISA', 'Visa');
INSERT INTO `melis_ecom_order_payment_type` (`opty_id`, `opty_status`, `opty_code`, `opty_name`) VALUES (2, 1, 'MASTERCARD', 'Mastercard');
INSERT INTO `melis_ecom_order_payment_type` (`opty_id`, `opty_status`, `opty_code`, `opty_name`) VALUES (3, 0, 'AMEX', 'American Express');
INSERT INTO `melis_ecom_order_payment_type` (`opty_id`, `opty_status`, `opty_code`, `opty_name`) VALUES (4, 0, 'PAYPAL', 'PayPal');
INSERT INTO `melis_ecom_order_payment_type` (`opty_id`, `opty_status`, `opty_code`, `opty_name`) VALUES (5, 0, 'TRANSFERT', 'Account Transfert');

COMMIT;

