<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = $this->zoneconfig['conf']['id'];
    }
    $name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
    
?>
<h1 id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="content-heading"><?= $this->translate($this->escapeHtml($name)); ?></h1>
<p><?= $this->translate('tr_meliscommerce_coupon_list_page_description')?></p>