<?php if ($this->prefixId):?>
<?php
$name = '';
if (!empty($this->zoneconfig['conf']['name'])){
    $name = $this->zoneconfig['conf']['name'];
}
$icon = '';
if (!empty($this->zoneconfig['conf']['icon'])){
    $icon = $this->zoneconfig['conf']['icon'];
}
$active = '';
if (!empty($this->zoneconfig['conf']['icon'])){
    $icon = $this->zoneconfig['conf']['icon'];
}
$href = '';
if (!empty($this->zoneconfig['conf']['href'])){
    $href = $this->zoneconfig['conf']['href'];
}

$id = 'id="';
if (!empty($this->prefixId)){
    $id .= $this->prefixId.'_';
    $href = $this->prefixId . '_' . $this->zoneconfig['conf']['href'];
}

$id .= $this->zoneconfig['conf']['id'].'"';
$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<li class="nav-item" <?= $id. ' '. $data_melisKey?> class="<?= $active;?>">
    <a class="nav-link <?= $icon;?>" data-bs-toggle="tab" href="#<?= $href;?>" aria-expanded="true">
        <i></i>
        <span><?= $name;?></span>
    </a>
</li>
<?php endif;?>