<?php
$name = '';
if (!empty($this->zoneconfig['conf']['name'])){
    $name = $this->zoneconfig['conf']['name'];
}

$id = 'id="';
if (!empty($this->prefixId)){
    $id .= $this->prefixId.'_';
}

$id .= $this->zoneconfig['conf']['id'].'"';
$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';

?>


<div class="melis-product-heading border-bottom" <?php echo $id. ' '. $data_melisKey;?>>
    <h3 <?= $id. ' '.$data_melisKey?>><?= $this->translate('tr_meliscommerce_avar_title'); ?></h3>
    <div class="float-right">
        <?php
        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
        ?>
    </div>
</div>