<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="'.$this->prefixId.'_'.$this->zoneconfig['conf']['id'] . '"';
$data_melisKey = $this->melisKey;
?>

<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
    <div class="spacing-x2">
        <?php
        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
        ?>
    </div>
</div>