import { mergeDict } from '../../shared/i18n'

/** Dictionnaire de l'outil Statuts de commande (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Statuts de commande',
    subtitle: 'Retrouvez ici les différents statuts de commande. Vous pouvez activer/désactiver, ajouter ou supprimer des statuts selon les besoins de vos sites. Les statuts de base ne peuvent pas être supprimés.',
    new: 'Ajouter un statut', search_placeholder: 'Rechercher un statut…',
    filter_status: 'Tous les statuts',
    btn_export: 'Exporter', btn_col_manager: 'Colonnes',
    exp_title: 'Exporter les statuts', exp_subtitle: '{n} statuts seront exportés', exp_filename: 'statuts-de-commande',
    del_title: 'Supprimer le statut', del_confirm: 'Êtes-vous sûr de vouloir supprimer le statut « {u} » ?',
    err_permanent_delete: 'Ce statut est indispensable à la plateforme et ne peut pas être supprimé.',
    col_id: 'ID', col_name: 'Nom', col_color: 'Couleur', col_status: 'Statut', col_action: 'Action',
    no_items: 'Aucun statut trouvé.', count: '{n} statuts — fin de la liste',
    tab_main: 'Propriétés', tab_labels: 'Labels',
    status_label: 'STATUT',
    section_general_data: 'Données générales',
    field_color: 'Code couleur', tip_color: 'Couleur utilisée pour afficher ce statut dans les listes.',
    field_name: 'Nom', tip_name: 'Nom du statut.',
    err_color_required: 'La couleur est obligatoire.',
    err_name_required: 'Le nom est obligatoire pour au moins une langue.',
    permanent_badge: 'Statut indispensable',
  },
  en: {
    title: 'Order status',
    subtitle: 'Find here the different order statuses. You can activate/deactivate, add or delete statuses depending on the needs of your sites. The basic statuses cannot be deleted.',
    new: 'Add status', search_placeholder: 'Search a status…',
    filter_status: 'All statuses',
    btn_export: 'Export', btn_col_manager: 'Columns',
    exp_title: 'Export order statuses', exp_subtitle: '{n} statuses will be exported', exp_filename: 'order-statuses',
    del_title: 'Delete status', del_confirm: 'Are you sure you want to delete status "{u}"?',
    err_permanent_delete: 'This status is mandatory for the commerce platform, it cannot be deleted.',
    col_id: 'ID', col_name: 'Name', col_color: 'Color', col_status: 'Status', col_action: 'Action',
    no_items: 'No status found.', count: '{n} statuses — end of list',
    tab_main: 'Properties', tab_labels: 'Labels',
    status_label: 'STATUS',
    section_general_data: 'General Data',
    field_color: 'Color code', tip_color: 'Color used to display this status in lists.',
    field_name: 'Name', tip_name: 'Status name.',
    err_color_required: 'The color is required.',
    err_name_required: 'Name is required for at least one language.',
    permanent_badge: 'Mandatory status',
  },
})
