import { mergeDict } from '../../shared/i18n'

/** Dictionnaire spécifique à l'outil Catalogues / Catégories (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Catalogues / Catégories', subtitle: 'Gérez vos catalogues et catégories. Réordonnez-les par glisser-déposer.',
    search: 'Rechercher un catalogue / une catégorie…', empty: 'Aucun catalogue. Créez-en un pour commencer.',
    search_not_found: '"{q}" non trouvé',
    add_catalog: 'Ajouter un catalogue', add_category: 'Ajouter une catégorie', add_child: 'Ajouter une sous-catégorie',
    ctx_add: 'Ajouter', ctx_update: 'Modifier', ctx_delete: 'Supprimer',
    clear: 'Effacer', collapse_all: 'Tout réduire', expand_all: 'Tout déplier',
    products_n: '{n} produit(s)',
    sel_parent_hint: 'Sélectionnez d’abord un catalogue ou une catégorie comme parent.',
    status_label: 'Statut', online: 'Actif', offline: 'Inactif',
    save_catalog: 'Enregistrer le catalogue', save_category: 'Enregistrer la catégorie',
    tab_properties: 'Propriétés', tab_seo: 'SEO', tab_products: 'Produits',
    sec_texts: 'Textes', sec_dates: 'Validité', sec_countries: 'Pays', f_parent: 'Parent',
    seo_page_id: 'ID de page', seo_url: 'URL', seo_url_redirect: 'Redirection d’URL', seo_url_301: 'URL 301', seo_meta_title: 'Titre meta', seo_meta_desc: 'Description meta',
    seo_page_id_ph: 'ID de la page associée', seo_url_ph: 'url-de-la-categorie', seo_url_redirect_ph: '/nompage/id/1 ou http://…', seo_url_301_ph: '/nompage/id/1 ou http://…',
    seo_meta_title_ph: 'Titre pour les moteurs', seo_meta_desc_ph: 'Description pour les moteurs',
    prod_title: 'Produits de la catégorie', prod_empty: 'Aucun produit dans cette catégorie.',
    prod_col_id: 'ID', prod_col_ref: 'Référence', prod_col_name: 'Nom', prod_col_status: 'Statut',
    countries_all: 'Tous les pays', save_first_tab: 'Enregistrez d’abord pour gérer cet onglet.',
    del_title: 'Supprimer', del_confirm: 'Supprimer « {u} » ? Cette action est irréversible (les sous-catégories et liens produits sont retirés).',
    del_catalog_warn: 'Ce catalogue contient des catégories ; elles seront détachées.',
    new_catalog_title: 'Nouveau catalogue', new_category_title: 'Nouvelle catégorie',
    edit_catalog_title: 'Modifier le catalogue', edit_category_title: 'Modifier la catégorie',
    tab_main: 'Général', tab_texts: 'Traductions', tab_countries: 'Pays',
    f_reference: 'Référence', f_reference_ph: 'Référence (optionnelle)',
    f_valid_start: 'Valide à partir du', f_valid_end: 'Valide jusqu’au',
    f_active: 'Actif', f_active_hint: 'L’élément est actif et visible.',
    f_name: 'Nom', f_name_ph: 'Nom', f_description: 'Description', f_description_ph: 'Description',
    f_countries: 'Pays', f_no_country: 'Aucun pays disponible.', f_countries_hint: 'Sélectionnez les pays concernés.',
    err_name: 'Un nom est obligatoire (au moins une langue).', err_dates: 'La date de fin doit être postérieure à la date de début.', field_required: 'Ce champ est obligatoire.',
    err_save: 'Erreur lors de la sauvegarde', err_move: 'Déplacement impossible.',
    move_cat_to_root: 'Une catégorie ne peut pas devenir un catalogue.',
    lang_display: 'Langue d’affichage', reorder_hint: 'Double-clic pour éditer · clic droit pour le menu · glisser-déposer pour réordonner.',
    drag_hint: 'Glisser pour réordonner', no_name: '(sans nom)', empty_tree: 'Aucun résultat.', add_catalog_root: 'Nouveau catalogue',
    editor_empty: 'Sélectionnez un catalogue ou une catégorie dans l’arbre, ou créez-en un nouveau.',
  },
  en: {
    title: 'Catalogs / Categories', subtitle: 'Manage your catalogs and categories. Reorder them by drag and drop.',
    search: 'Search a catalog / category…', empty: 'No catalog yet. Create one to get started.',
    search_not_found: '"{q}" not found',
    add_catalog: 'Add catalog', add_category: 'Add category', add_child: 'Add subcategory',
    ctx_add: 'Add', ctx_update: 'Update', ctx_delete: 'Delete',
    clear: 'Clear', collapse_all: 'Collapse all', expand_all: 'Expand all',
    products_n: '{n} product(s)',
    sel_parent_hint: 'Select a catalog or category first as parent.',
    status_label: 'Status', online: 'Active', offline: 'Inactive',
    save_catalog: 'Save catalog', save_category: 'Save category',
    tab_properties: 'Properties', tab_seo: 'SEO', tab_products: 'Products',
    sec_texts: 'Texts', sec_dates: 'Validity', sec_countries: 'Countries', f_parent: 'Parent',
    seo_page_id: 'Page ID', seo_url: 'URL', seo_url_redirect: 'URL redirection', seo_url_301: 'URL 301', seo_meta_title: 'Meta title', seo_meta_desc: 'Meta description',
    seo_page_id_ph: 'ID of the linked page', seo_url_ph: 'category-url', seo_url_redirect_ph: '/mypagename/id/1 or http://…', seo_url_301_ph: '/mypagename/id/1 or http://…',
    seo_meta_title_ph: 'Title for search engines', seo_meta_desc_ph: 'Description for search engines',
    prod_title: 'Category products', prod_empty: 'No product in this category.',
    prod_col_id: 'ID', prod_col_ref: 'Reference', prod_col_name: 'Name', prod_col_status: 'Status',
    countries_all: 'All countries', save_first_tab: 'Save first to manage this tab.',
    del_title: 'Delete', del_confirm: 'Delete “{u}”? This is irreversible (subcategories and product links are removed).',
    del_catalog_warn: 'This catalog contains categories; they will be detached.',
    new_catalog_title: 'New catalog', new_category_title: 'New category',
    edit_catalog_title: 'Edit catalog', edit_category_title: 'Edit category',
    tab_main: 'General', tab_texts: 'Translations', tab_countries: 'Countries',
    f_reference: 'Reference', f_reference_ph: 'Reference (optional)',
    f_valid_start: 'Valid from', f_valid_end: 'Valid until',
    f_active: 'Active', f_active_hint: 'The item is active and visible.',
    f_name: 'Name', f_name_ph: 'Name', f_description: 'Description', f_description_ph: 'Description',
    f_countries: 'Countries', f_no_country: 'No country available.', f_countries_hint: 'Select the relevant countries.',
    err_name: 'A name is required (at least one language).', err_dates: 'End date must be after start date.', field_required: 'This field is required.',
    err_save: 'Error while saving', err_move: 'Move not allowed.',
    move_cat_to_root: 'A category cannot become a catalog.',
    lang_display: 'Display language', reorder_hint: 'Double-click to edit · right-click for menu · drag and drop to reorder.',
    drag_hint: 'Drag to reorder', no_name: '(no name)', empty_tree: 'No result.', add_catalog_root: 'New catalog',
    editor_empty: 'Select a catalog or category in the tree, or create a new one.',
  },
})
