import { mergeDict } from '../../shared/i18n'

/** Dictionnaire de l'outil Attributs (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Attributs', subtitle: 'Retrouvez ici les différents attributs. Ils correspondent aux caractéristiques des produits.',
    new: 'Ajouter un attribut', search_placeholder: 'Rechercher un attribut…',
    filter_status: 'Tous les statuts', filter_type: 'Tous les types',
    btn_export: 'Exporter', btn_col_manager: 'Colonnes',
    exp_title: 'Exporter les attributs', exp_subtitle: '{n} attributs seront exportés', exp_filename: 'attributs',
    del_title: 'Supprimer l\'attribut',
    del_confirm: 'En supprimant cet attribut, vous supprimerez également les informations et paramètres critiques qui lui sont rattachés. Voulez-vous vraiment supprimer « {u} » ?',
    col_id: 'ID', col_name: 'Attribut', col_reference: 'Référence', col_type: 'Type',
    col_status: 'Statut', col_visible: 'Visible', col_searchable: 'Recherchable', col_values: 'Valeurs', col_action: 'Action',
    no_items: 'Aucun attribut trouvé.', count: '{n} attributs — fin de la liste',
    tab_main: 'Propriétés', tab_labels: 'Labels', tab_values: 'Valeurs',
    status_label: 'STATUT', yes: 'Oui', no: 'Non',
    section_general_data: 'Données générales', section_display: 'Affichage',
    field_reference: 'Référence', field_type: 'Type',
    field_visible: 'Visible', field_searchable: 'Recherchable',
    tip_reference: "Référence interne de l'attribut.",
    tip_type: "Type de valeur dans lequel sera renseigné l'attribut (cette valeur est définitive et ne pourra plus être modifiée une fois l'attribut créé).",
    tip_visible: "Sélectionnez si l'attribut sera visible en Front.",
    tip_searchable: "Sélectionnez si l'attribut sera recherchable en Front.",
    err_reference_required: 'La référence est obligatoire.', err_type_required: 'Le type est obligatoire.',
    err_name_required: 'Le nom est obligatoire pour au moins une langue.',
    err_required_fields: 'Veuillez vérifier les champs obligatoires.',
    field_name: 'Label', field_description: 'Description',
    tip_name: "Nom de l'attribut.", tip_description: "Description de l'attribut.",
    values_add: 'Ajouter une valeur', values_empty: 'Aucune valeur.', values_save_first: "Enregistrez l'attribut pour gérer ses valeurs.",
    values_count: '{n} valeurs — fin de la liste',
    value_new_title: 'Nouvelle valeur', value_edit_title: 'Modifier la valeur',
    value_field_perlang: 'Ou saisir individuellement pour chaque langage',
    value_del_title: 'Supprimer la valeur', value_del_confirm: 'Supprimer cette valeur ?',
    value_col_id: 'ID', value_col_reference: 'Référence', value_col_value: 'Valeur',
    value_file_current: 'Fichier existant', value_file_none: 'Aucun fichier', value_file_download: 'Télécharger', value_file_replace: 'Remplacer le fichier',
    type_int: 'Entier', type_float: 'Décimal', type_bool: 'Booléen', type_varchar: 'Texte court', type_text: 'Texte', type_datetime: 'Date', type_binary: 'Fichier',
  },
  en: {
    title: 'Attributes', subtitle: 'Find here the different attributes. They correspond to the product characteristics.',
    new: 'Add attribute', search_placeholder: 'Search an attribute…',
    filter_status: 'All statuses', filter_type: 'All types',
    btn_export: 'Export', btn_col_manager: 'Columns',
    exp_title: 'Export attributes', exp_subtitle: '{n} attributes will be exported', exp_filename: 'attributes',
    del_title: 'Delete attribute',
    del_confirm: 'By removing this attribute, you will also be removing critical information and settings attached to it. Are you sure you want to delete "{u}"?',
    col_id: 'ID', col_name: 'Attribute', col_reference: 'Reference', col_type: 'Type',
    col_status: 'Status', col_visible: 'Visible', col_searchable: 'Searchable', col_values: 'Values', col_action: 'Action',
    no_items: 'No attribute found.', count: '{n} attributes — end of list',
    tab_main: 'Properties', tab_labels: 'Labels', tab_values: 'Values',
    status_label: 'STATUS', yes: 'Yes', no: 'No',
    section_general_data: 'General Data', section_display: 'Display',
    field_reference: 'Reference', field_type: 'Type',
    field_visible: 'Visible', field_searchable: 'Searchable',
    tip_reference: 'Internal reference of the attribute.',
    tip_type: 'Type of value in which the attribute will be filled (this value is definitive and can no longer be modified once the attribute is created).',
    tip_visible: 'Select if the attribute will be visible in Front.',
    tip_searchable: 'Select if the attribute will be searchable in Front.',
    err_reference_required: 'Reference is required.', err_type_required: 'Type is required.',
    err_name_required: 'Name is required for at least one language.',
    err_required_fields: 'Please check the required fields.',
    field_name: 'Label', field_description: 'Description',
    tip_name: 'Attribute name.', tip_description: 'Attribute description.',
    values_add: 'Add value', values_empty: 'No value.', values_save_first: 'Save the attribute first to manage its values.',
    values_count: '{n} values — end of list',
    value_new_title: 'New value', value_edit_title: 'Edit value',
    value_field_perlang: 'Or enter individually for each language',
    value_del_title: 'Delete value', value_del_confirm: 'Delete this value?',
    value_col_id: 'ID', value_col_reference: 'Reference', value_col_value: 'Value',
    value_file_current: 'Existing file', value_file_none: 'No file', value_file_download: 'Download', value_file_replace: 'Replace file',
    type_int: 'Integer', type_float: 'Decimal', type_bool: 'Boolean', type_varchar: 'Short string', type_text: 'Text', type_datetime: 'Date', type_binary: 'File',
  },
})
