<div class="row">
	<div class="col-md-12" id="productCategorySearchZone">
		<div class="form-group">
        	<input type="text" class="form-control" name="catPrdSliderPluginSearch" id="catPrdSliderPluginSearch" placeholder="<?= $this->translate('tr_meliscommerce_categories_list_tree_view_search_input'); ?>">
    	</div>
    	<div class="row">
    		<div class="col-xs-6 col-md-6 col-lg-3">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginClearBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_clear')?>">
    				<i class="fa fa-eraser"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_clear')?></span>
    			</button>
    		</div>
    		<div class="col-xs-6 col-md-6 col-lg-3 margin-bottom-10">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginCollapseBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_collapse_all')?>">
    				<i class="fa fa-compress fa-flip-horizontal"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_collapse_all')?></span>
    			</button>
    		</div>
    		<div class="col-xs-6 col-md-6 col-lg-3">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginExpandBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_expand_all')?>">
    				<i class="fa fa-expand fa-flip-horizontal"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_expand_all')?></span>
    			</button>
    		</div>
    		<div class="col-xs-6 col-md-6 col-lg-3">
    			<button class="btn btn-success btn-block margin-bottom-10" id="catPrdSliderPluginRefreshBtn" title="<?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_refresh')?>">
    				<i class="fa fa-refresh"></i> 
    				<span><?php echo $this->translate('tr_meliscommerce_categories_list_tree_view_refresh')?></span>
    			</button>
    		</div>
    	</div>
	</div>
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6">
				<br>
        		<div class="prodCatLangDropDownContainer">
                	<div class="filter-dropdown clearfix categoryLangTreePluginDropdown" data-productid="<?= $this->productId; ?>">
                		<a href="#" class="dropdown-toggle category-list-lang-dropdown" data-toggle="dropdown">
                			<i class="fa fa-language"></i>
                			<span class="filter-key"><?= $this->currentLangName; ?></span>
                			<span class="caret"></span>
                		</a>
                		<ul class="dropdown-menu category-tree-view-lang-plugin">
						<?php 
						    if($this->langData): 
						        foreach($this->langData as $lang): ?>
                        			<li>
    									<?php
    									$imageData = $lang->elang_flag;
    									$image = !empty($imageData) ? '<img src="data:image/jpeg;base64,'. ($imageData) .'" class="imgDisplay float-right" width="24" height="24"/>' : '<i class="fa fa-globe"></i>';
    									?>
                        				<a data-locale="<?= $lang->elang_locale; ?>"><?= $lang->elang_name; ?><span class="float-right"><?php echo $image; ?></span></a>
                        			</li>
            			<?php 
                			    endforeach;
							endif;
						?>
                		</ul>
                	</div>
				</div>
			</div>
			<div class="col-md-6"></div>
		</div>
	</div>
	<div class="col-md-12">
		<div id="productListPluginTreeConfig" class="productCategoryView" data-langlocale="<?php echo $this->currentLangLocale ?>"></div>
	</div>
	<form id="productListPluginTreeConfig_form" data-input-field-selected="m_box_category_tree_ids_selected">
		<?php if (!empty($this->formData['m_box_category_tree_ids_selected'])):?>
    		<?php foreach ($this->formData['m_box_category_tree_ids_selected'] As $val):?>
    			<input type="hidden" name="m_box_category_tree_ids_selected[]" value="<?php echo $val?>">
    		<?php endforeach;?>
		<?php endif;?>
	</form>
</div>
<?php
    $selected_tree_ids = json_encode(array_unique($this->formData['m_box_category_tree_ids_selected']));
?>
<script>
    commerceCategoryTree.initCategoryTree("productListPluginTreeConfig", function(e, data, categoryTree){
        catTreeConfig.setCategoryTreeConfig(categoryTree, <?=$selected_tree_ids;?>, 0, false, false);
    });
</script>