<form action="">
	<div class="input-group">
      	<input type="text" class="form-control" name="m_box_product_search" placeholder="Search here" value="<?php echo $this->searchKey ?>">
      	<span class="input-group-btn">
        	<button class="btn btn-default" type="submit"><?= $this->translate('tr_meliscommerce_general_common_search') ?></button>
      	</span>
	</div><!-- /input-group -->
</form>