<?php if(!empty($this->relatedProducts)) { ?>
    <div class="row">
        <?php
            foreach($this->relatedProducts as $product)
            {
                $categoryName = '';
                $productName = '';
                $price = !empty($product->display_price)? $product->display_price : '';
                $mainImage = '';
                $hoverImage = '';

                $productPageLink = $this->MelisCommerceLink('product', $product->getId(), $this->langId, true);

                if(!empty($product->getTexts())){
                    foreach($product->getTexts() as $text){
                        if($text->ptt_code == 'TITLE'){
                            $productName = $text->ptxt_field_short;
                            break;
                        }
                    }
                }
                // if no texts or translations use the reference name
                if(empty($productName)){
                    $productName = $product->getProduct()->prd_reference;
                }

                foreach($product->getDocuments() as $document){
                    if($document->doc_type_id){
                        /*
                         * get image type, 3 for defualt image, 4 for small image.
                         * see melis_ecom_doc_type for all the document and images type
                         */
                        switch ($document->doc_subtype_id) {
                            case(3):
                                $mainImage = $document->doc_path;
                                break;
                            case(4):
                                $hoverImage = $document->doc_path;
                                break;
                        }
                    }
                }

                $categories = $product->getCategories();
                foreach($categories AS $cat_info){
                    $categoryName = $cat_info->catt_name;
                }

            ?>
            <div class="col-md-3">
                <div class="single-product">
                    <div class="product-img">
                        <div class="product-label">
                            <div class="new"><?= $categoryName ?></div>
                        </div>
                        <div class="single-prodcut-img  product-overlay pos-rltv">
                            <a href="<?= $productPageLink ?>">
                                <img alt="" src="<?= $mainImage ?>" class="primary-image">
                                <img alt="" src="<?= $hoverImage ?>" class="secondary-image">
                            </a>
                        </div>
                    </div>
                    <div>
                        <div><?= $productName?></div>
                        <div>
                            <div>
                                <div> <?= $price->cur_symbol.' '.$price->price_net ?> </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php
            }
        ?>
    </div>
<?php } ?>
