import type { Dict } from '../../shared/i18n'

export const DICT: Dict = {
  en: {
    loading: 'Loading…',
    save: 'Save', cancel: 'Cancel', confirm_delete: 'Delete?',
    title: 'Orders', subtitle: 'Manage customer orders.',
    back: 'Back', refresh: 'Refresh', new: 'New order',
    search_placeholder: 'Search reference, client…',
    dr_label: 'Date', dr_all: 'All', dr_today: 'Today', dr_yesterday: 'Yesterday',
    dr_last7: 'Last 7 days', dr_last30: 'Last 30 days',
    dr_thismonth: 'This month', dr_lastmonth: 'Last month',
    dr_custom: 'Custom range', dr_from: 'From', dr_to: 'To', dr_apply: 'Apply',
    filter_status: 'All statuses',
    filter_date_from: 'From', filter_date_to: 'To',
    btn_export: 'Export',
    btn_col_manager: 'Columns',
    btn_legacy: 'Old view',
    status_cancelled: 'Cancelled',
    kpi_total: 'Total orders',
    kpi_today: 'Today',
    kpi_month: 'This month',
    kpi_pending: 'Pending (new)',
    kpi_revenue: 'Revenue (month)',
    exp_title: 'Export orders', exp_subtitle: '{n} orders will be exported', exp_filename: 'orders',
    col_id: 'ID',
    col_reference: 'Reference',
    col_status: 'Status',
    col_products: 'Products',
    col_total: 'Price',
    col_firstname: 'First name',
    col_name: 'Last name',
    col_company: 'Company',
    col_date: 'Date',
    col_action: 'Action',
    tab_information: 'Information',
    tab_basket: 'Basket',
    tab_addresses: 'Addresses',
    tab_payment: 'Payment',
    tab_shipping: 'Shipping',
    tab_messages: 'Messages',
    section_status: 'Order status',
    section_invoice: 'Invoice (Manual Upload, Custom Document)',
    section_attachments: 'File Attachments',
    btn_add_file: 'Add file',
    no_attachments: 'No attached file',
    upload_title: 'File',
    upload_subtitle: 'Attach a file to this order (ex: invoice)',
    upload_select: 'Select file',
    upload_name_label: 'Name',
    upload_close: 'Close',
    upload_save: 'Save',
    upload_saving: 'Saving…',
    upload_delete_confirm: 'Delete this file?',
    section_order: 'ORDER',
    section_client: 'CLIENT',
    section_basket: 'BASKET',
    section_billing: 'BILLING ADDRESS',
    section_delivery: 'DELIVERY ADDRESS',
    section_payment: 'PAYMENT',
    section_shipping: 'SHIPPING',
    section_messages: 'MESSAGES',
    field_reference: 'Reference',
    field_company: 'Company',
    field_contact: 'Contact',
    field_date: 'Order date',
    field_civility: 'Civility',
    field_firstname: 'First name',
    field_name: 'Last name',
    field_middle_name: 'Middle name',
    field_num: 'Street number',
    field_street: 'Street',
    field_building: 'Building',
    field_stairs: 'Stairs',
    field_city: 'City',
    field_state: 'State / Region',
    field_country: 'Country',
    field_zipcode: 'Zip code',
    field_phone_mobile: 'Mobile',
    field_phone_landline: 'Phone',
    field_complementary: 'Complementary',
    basket_col_sku: 'SKU',
    basket_col_name: 'Product',
    basket_col_category: 'Category',
    basket_col_qty: 'Qty',
    basket_col_price_net: 'Price (net)',
    basket_col_price_gross: 'Price (gross)',
    basket_col_currency: 'Currency',
    payment_col_type: 'Method',
    payment_col_transac: 'Transaction ID',
    payment_col_total: 'Total',
    payment_col_order: 'Order',
    payment_col_shipping: 'Shipping',
    payment_col_currency: 'Currency',
    payment_col_date: 'Date',
    shipping_col_tracking: 'Tracking code',
    shipping_col_content: 'Notes',
    shipping_col_date: 'Sent date',
    shipping_add: 'Add tracking',
    field_tracking: 'Tracking code',
    field_content: 'Notes',
    field_date_sent: 'Sent date',
    msg_placeholder: 'Write a message…',
    msg_send: 'Send',
    msg_empty: 'No messages yet.',
    no_address: 'No address on file.',
    no_payments: 'No payment recorded.',
    no_shippings: 'No shipping recorded.',
    no_items: 'No orders found.',
    no_basket_items: 'No items in basket.',
    tab_returns: 'Returns',
    section_returns: 'RETURN OF PRODUCTS',
    no_returns: 'No returns recorded.',
    return_col_id: 'Return ID',
    return_col_sku: 'SKU',
    return_col_product: 'Product',
    return_col_qty: 'Qty',
    return_col_date: 'Date',
    err_reference_required: 'Reference is required.',
    err_tracking_required: 'Tracking code is required.',
    err_message_required: 'Message cannot be empty.',
    err_cancelled: 'This order is cancelled and cannot be updated.',
    address_saved: 'Address saved.',
    shipping_saved: 'Tracking added.',
    message_sent: 'Message sent.',
    status_changed: 'Status updated.',
  },
  fr: {
    loading: 'Chargement…',
    save: 'Enregistrer', cancel: 'Annuler', confirm_delete: 'Supprimer ?',
    title: 'Commandes', subtitle: 'Gestion des commandes clients.',
    back: 'Retour', refresh: 'Actualiser', new: 'Nouvelle commande',
    search_placeholder: 'Rechercher référence, client…',
    dr_label: 'Date', dr_all: 'Tout', dr_today: "Aujourd'hui", dr_yesterday: 'Hier',
    dr_last7: '7 derniers jours', dr_last30: '30 derniers jours',
    dr_thismonth: 'Ce mois', dr_lastmonth: 'Mois dernier',
    dr_custom: 'Plage personnalisée', dr_from: 'Du', dr_to: 'Au', dr_apply: 'Appliquer',
    filter_status: 'Tous les statuts',
    filter_date_from: 'Du', filter_date_to: 'Au',
    btn_export: 'Exporter',
    btn_col_manager: 'Colonnes',
    btn_legacy: 'Ancienne vue',
    status_cancelled: 'Annulée',
    kpi_total: 'Commandes total',
    kpi_today: "Aujourd'hui",
    kpi_month: 'Ce mois',
    kpi_pending: 'En attente (new)',
    kpi_revenue: 'CA (mois)',
    exp_title: 'Exporter les commandes', exp_subtitle: '{n} commandes seront exportées', exp_filename: 'commandes',
    col_id: 'ID',
    col_reference: 'Référence',
    col_status: 'Statut',
    col_products: 'Produits',
    col_total: 'Prix',
    col_firstname: 'Prénom',
    col_name: 'Nom',
    col_company: 'Société',
    col_date: 'Date',
    col_action: 'Action',
    tab_information: 'Informations',
    tab_basket: 'Panier',
    tab_addresses: 'Adresses',
    tab_payment: 'Paiement',
    tab_shipping: 'Expédition',
    tab_messages: 'Messages',
    section_status: 'Statut de la commande',
    section_invoice: 'Facture (Upload manuel, Document personnalisé)',
    section_attachments: 'Pièces jointes',
    btn_add_file: 'Ajouter un fichier',
    no_attachments: 'Aucun fichier joint',
    upload_title: 'Fichier',
    upload_subtitle: 'Joindre un fichier à cette commande (ex : facture)',
    upload_select: 'Sélectionner un fichier',
    upload_name_label: 'Nom',
    upload_close: 'Fermer',
    upload_save: 'Enregistrer',
    upload_saving: 'Enregistrement…',
    upload_delete_confirm: 'Supprimer ce fichier ?',
    section_order: 'COMMANDE',
    section_client: 'CLIENT',
    section_basket: 'PANIER',
    section_billing: 'ADRESSE DE FACTURATION',
    section_delivery: 'ADRESSE DE LIVRAISON',
    section_payment: 'PAIEMENT',
    section_shipping: 'EXPÉDITION',
    section_messages: 'MESSAGES',
    field_reference: 'Référence',
    field_company: 'Société',
    field_contact: 'Contact',
    field_date: 'Date commande',
    field_civility: 'Civilité',
    field_firstname: 'Prénom',
    field_name: 'Nom',
    field_middle_name: 'Deuxième prénom',
    field_num: 'Numéro de rue',
    field_street: 'Rue',
    field_building: 'Bâtiment',
    field_stairs: 'Escalier',
    field_city: 'Ville',
    field_state: 'Région',
    field_country: 'Pays',
    field_zipcode: 'Code postal',
    field_phone_mobile: 'Mobile',
    field_phone_landline: 'Téléphone',
    field_complementary: 'Complément',
    basket_col_sku: 'SKU',
    basket_col_name: 'Produit',
    basket_col_category: 'Catégorie',
    basket_col_qty: 'Qté',
    basket_col_price_net: 'Prix (HT)',
    basket_col_price_gross: 'Prix (TTC)',
    basket_col_currency: 'Devise',
    payment_col_type: 'Méthode',
    payment_col_transac: 'Transaction ID',
    payment_col_total: 'Total',
    payment_col_order: 'Commande',
    payment_col_shipping: 'Livraison',
    payment_col_currency: 'Devise',
    payment_col_date: 'Date',
    shipping_col_tracking: 'N° suivi',
    shipping_col_content: 'Notes',
    shipping_col_date: 'Date envoi',
    shipping_add: 'Ajouter un suivi',
    field_tracking: 'N° de suivi',
    field_content: 'Notes',
    field_date_sent: 'Date d\'envoi',
    msg_placeholder: 'Écrire un message…',
    msg_send: 'Envoyer',
    msg_empty: 'Aucun message.',
    no_address: 'Aucune adresse enregistrée.',
    no_payments: 'Aucun paiement enregistré.',
    no_shippings: 'Aucune expédition enregistrée.',
    no_items: 'Aucune commande trouvée.',
    no_basket_items: 'Aucun article dans le panier.',
    tab_returns: 'Retours',
    section_returns: 'RETOUR DE PRODUITS',
    no_returns: 'Aucun retour enregistré.',
    return_col_id: 'ID retour',
    return_col_sku: 'SKU',
    return_col_product: 'Produit',
    return_col_qty: 'Qté',
    return_col_date: 'Date',
    err_reference_required: 'La référence est requise.',
    err_tracking_required: 'Le numéro de suivi est requis.',
    err_message_required: 'Le message ne peut pas être vide.',
    err_cancelled: 'Cette commande est annulée et ne peut pas être modifiée.',
    address_saved: 'Adresse enregistrée.',
    shipping_saved: 'Suivi ajouté.',
    message_sent: 'Message envoyé.',
    status_changed: 'Statut mis à jour.',
  },
}
