import { mergeDict } from '../../shared/i18n'

export const DICT = mergeDict({
  en: {
    loading: 'Loading…',
    save: 'Save', cancel: 'Cancel', confirm_delete: 'Delete?',
    title: 'Orders', subtitle: 'Manage customer orders.',
    checkout_title: 'New order', checkout_subtitle: 'Create a new order for a customer.',
    checkout_step_contact: 'Contact', checkout_step_account: 'Account', checkout_step_products: 'Products',
    checkout_step_addresses: 'Addresses', checkout_step_summary: 'Summary', checkout_step_payment: 'Payment',
    checkout_step_confirmation: 'Confirmation', checkout_step_todo: 'Coming up next…',
    checkout_step_contact_hint: 'Select the contact for this order.',
    checkout_step_account_hint: 'Select the account linked to this contact.',
    checkout_col_contact: 'Contact', checkout_col_group: 'Group', checkout_col_orders: 'Orders', checkout_col_last_order: 'Last order',
    checkout_col_account: 'Account', checkout_col_default_account: 'Default',
    checkout_no_contacts: 'No contact found.', checkout_no_accounts: 'This contact has no linked account.',
    checkout_search: 'Search…', checkout_back: 'Back', col_email: 'Email',
    checkout_step_products_hint: 'Choose a country, then browse the catalog and add products to the basket.',
    checkout_choose_country: '— Choose a country —', checkout_choose_country_hint: 'Choose a country to browse the catalog.',
    checkout_col_product: 'Product', checkout_col_variants: 'Variants',
    checkout_no_products: 'No product found.', checkout_no_variants: 'No variant for this product.',
    checkout_in_stock: 'in stock', checkout_add: 'Add', checkout_prev: 'Previous', checkout_next: 'Next',
    checkout_basket_title: 'Basket', checkout_basket_empty: 'Basket is empty.', checkout_basket_total: 'Total',
    checkout_step_addresses_hint: 'Pick or add the billing and delivery addresses for this order.',
    checkout_save_addresses: 'Save addresses', checkout_delivery_address: 'Delivery Address', checkout_billing_address: 'Billing Address',
    checkout_same_as_delivery: 'Use the same address',
    checkout_choose_ph: 'Choose', checkout_delivery_select: 'Choose a delivery address', checkout_billing_select: 'Choose a billing address',
    checkout_create_delivery_btn: 'Or create a new delivery address', checkout_create_billing_btn: 'Or create a new billing address',
    checkout_addresses_required: 'Please save and select a delivery (and billing) address.',
    checkout_step_summary_hint: 'Review the order before confirming.',
    checkout_col_qty: 'Qty', checkout_col_price: 'Price', checkout_col_total: 'Total',
    checkout_summary_errors: 'Some basket items have a pricing issue — go back to Products to review.',
    checkout_coupon_ph: 'Coupon code', checkout_apply_coupon: 'Apply', checkout_coupon_applied: 'Applied ✓',
    checkout_coupon_remove: 'Remove', checkout_coupon_already_applied: 'This coupon is already applied.',
    checkout_subtotal: 'Subtotal',
    checkout_addr_title: 'Address title', checkout_addr_civility: 'Civility', checkout_addr_firstname: 'First name', checkout_addr_name: 'Last name',
    checkout_addr_num: 'Street number', checkout_addr_street: 'Street', checkout_addr_city: 'City', checkout_addr_zipcode: 'Zip code', checkout_addr_phone: 'Phone',
    checkout_reduction: 'Discount', checkout_reduction_products: 'Products:', checkout_reduction_order: 'Order:',
    checkout_step_payment_hint: 'This order has no online payment gateway configured — confirming records it as paid manually.',
    checkout_confirm_order: 'Confirm order',
    checkout_payment_api: 'Payment API',
    checkout_card_name: 'Name on Card', checkout_card_name_ph: "Card Holder's Name",
    checkout_card_number: 'Card Number', checkout_card_number_ph: 'Debit/Credit Card Number',
    checkout_card_expiry: 'Expiration Date', checkout_card_month: 'Month', checkout_card_year: 'Year',
    checkout_card_cvv: 'Card CVV', checkout_card_cvv_ph: 'Security Code', checkout_pay_now: 'Pay Now',
    checkout_error_basket: 'Some items are no longer available in the requested quantity.',
    checkout_error_addresses: 'The billing/delivery addresses could not be validated.',
    checkout_error_costs: 'The order total could not be computed.',
    checkout_error_generic: 'The order could not be confirmed. Please review the previous steps.',
    checkout_success_title: 'Order created', checkout_success_hint: 'Order {ref} has been created successfully.',
    checkout_view_order: 'View order',
    back: 'Back', refresh: 'Refresh', new: 'New order',
    search_placeholder: 'Search reference, client…',
    dr_label: 'Date', dr_all: 'All', dr_today: 'Today', dr_yesterday: 'Yesterday',
    dr_last7: 'Last 7 days', dr_last30: 'Last 30 days',
    dr_thismonth: 'This month', dr_lastmonth: 'Last month',
    dr_custom: 'Custom range', dr_from: 'From', dr_to: 'To', dr_apply: 'Apply',
    filter_status: 'All statuses',
    filter_date_from: 'From', filter_date_to: 'To',
    btn_export: 'Export',
    btn_col_manager: 'Columns',
    btn_legacy: 'Old view',
    status_cancelled: 'Cancelled',
    kpi_total: 'Total orders',
    kpi_today: 'Today',
    kpi_month: 'This month',
    kpi_pending: 'Pending (new)',
    kpi_revenue: 'Revenue (month)',
    exp_title: 'Export orders', exp_subtitle: '{n} orders will be exported', exp_filename: 'orders',
    col_id: 'ID',
    col_reference: 'Reference',
    col_status: 'Status',
    col_products: 'Products',
    col_total: 'Price',
    col_firstname: 'First name',
    col_name: 'Last name',
    col_company: 'Company',
    col_date: 'Date',
    col_action: 'Action',
    tab_information: 'Information',
    tab_basket: 'Basket',
    tab_addresses: 'Addresses',
    tab_payment: 'Payment',
    tab_shipping: 'Shipping',
    tab_messages: 'Messages',
    section_status: 'Order status',
    section_invoice: 'Invoice (Manual Upload, Custom Document)',
    section_attachments: 'File Attachments',
    btn_add_file: 'Add file',
    no_attachments: 'No attached file',
    upload_title: 'File',
    upload_subtitle: 'Attach a file to this order (ex: invoice)',
    upload_select: 'Select file',
    upload_name_label: 'Name',
    upload_close: 'Close',
    upload_save: 'Save',
    upload_saving: 'Saving…',
    upload_delete_title: 'Delete file', upload_delete_confirm: 'Delete "{u}"? This action cannot be undone.',
    section_order: 'ORDER',
    section_client: 'CLIENT',
    section_basket: 'BASKET',
    section_billing: 'BILLING ADDRESS',
    section_delivery: 'DELIVERY ADDRESS',
    section_payment: 'PAYMENT',
    section_shipping: 'SHIPPING',
    section_messages: 'MESSAGES',
    field_reference: 'Reference',
    field_company: 'Company',
    field_contact: 'Contact',
    field_date: 'Order date',
    field_civility: 'Civility',
    field_firstname: 'First name',
    field_name: 'Last name',
    field_middle_name: 'Middle name',
    field_num: 'Street number',
    field_street: 'Street',
    field_building: 'Building',
    field_stairs: 'Stairs',
    field_city: 'City',
    field_state: 'State / Region',
    field_country: 'Country',
    field_zipcode: 'Zip code',
    field_phone_mobile: 'Mobile',
    field_phone_landline: 'Phone',
    field_complementary: 'Complementary',
    basket_col_sku: 'SKU',
    basket_col_name: 'Product',
    basket_col_category: 'Category',
    basket_col_qty: 'Qty',
    basket_col_price_net: 'Price (net)',
    basket_col_price_gross: 'Price (gross)',
    basket_col_currency: 'Currency',
    payment_col_type: 'Method',
    payment_col_transac: 'Transaction ID',
    payment_col_total: 'Total',
    payment_col_order: 'Order',
    payment_col_shipping: 'Shipping',
    payment_col_currency: 'Currency',
    payment_col_date: 'Date',
    shipping_col_tracking: 'Tracking code',
    shipping_col_content: 'Notes',
    shipping_col_date: 'Sent date',
    shipping_add: 'Add tracking',
    field_tracking: 'Tracking code',
    field_content: 'Notes',
    field_date_sent: 'Sent date',
    tip_date_sent: 'Date the parcel was sent to the customer.',
    msg_placeholder: 'Write a message…',
    msg_send: 'Send',
    msg_empty: 'No messages yet.',
    msg_author_admin: 'ADMIN',
    no_address: 'No address on file.',
    no_payments: 'No payment recorded.',
    no_shippings: 'No shipping recorded.',
    no_items: 'No orders found.',
    count: '{n} orders — end of list',
    no_basket_items: 'No items in basket.',
    tab_returns: 'Returns',
    tab_invoices: 'Invoices',
    section_returns: 'RETURN OF PRODUCTS',
    no_returns: 'No returns recorded.',
    return_col_id: 'Return ID',
    return_col_sku: 'SKU',
    return_col_product: 'Product',
    return_col_qty: 'Qty',
    return_col_date: 'Date',
    err_reference_required: 'Reference is required.',
    err_required_fields: 'Please check the required fields.',
    err_tracking_required: 'Tracking code is required.',
    err_message_required: 'Message cannot be empty.',
    err_cancelled: 'This order is cancelled and cannot be updated.',
    address_saved: 'Address saved.',
    shipping_saved: 'Tracking added.',
    message_sent: 'Message sent.',
    status_changed: 'Status updated.',
  },
  fr: {
    loading: 'Chargement…',
    save: 'Enregistrer', cancel: 'Annuler', confirm_delete: 'Supprimer ?',
    title: 'Commandes', subtitle: 'Gestion des commandes clients.',
    checkout_title: 'Nouvelle commande', checkout_subtitle: 'Créez ici une nouvelle commande.',
    checkout_step_contact: 'Contact', checkout_step_account: 'Compte', checkout_step_products: 'Produits',
    checkout_step_addresses: 'Adresses', checkout_step_summary: 'Récapitulatif', checkout_step_payment: 'Paiement',
    checkout_step_confirmation: 'Confirmation', checkout_step_todo: 'À venir…',
    checkout_step_contact_hint: 'Sélectionnez le contact de la commande.',
    checkout_step_account_hint: 'Sélectionnez le compte lié à ce contact.',
    checkout_col_contact: 'Contact', checkout_col_group: 'Groupe', checkout_col_orders: 'Commandes', checkout_col_last_order: 'Dernière commande',
    checkout_col_account: 'Compte', checkout_col_default_account: 'Défaut',
    checkout_no_contacts: 'Aucun contact trouvé.', checkout_no_accounts: 'Ce contact n\'a aucun compte lié.',
    checkout_search: 'Rechercher…', checkout_back: 'Retour', col_email: 'Email',
    checkout_step_products_hint: 'Choisissez un pays, puis parcourez le catalogue pour ajouter des produits au panier.',
    checkout_choose_country: '— Choisir un pays —', checkout_choose_country_hint: 'Choisissez un pays pour parcourir le catalogue.',
    checkout_col_product: 'Produit', checkout_col_variants: 'Variants',
    checkout_no_products: 'Aucun produit trouvé.', checkout_no_variants: 'Aucun variant pour ce produit.',
    checkout_in_stock: 'en stock', checkout_add: 'Ajouter', checkout_prev: 'Précédent', checkout_next: 'Suivant',
    checkout_basket_title: 'Panier', checkout_basket_empty: 'Le panier est vide.', checkout_basket_total: 'Total',
    checkout_step_addresses_hint: 'Choisissez ou ajoutez les adresses de facturation et de livraison de cette commande.',
    checkout_save_addresses: 'Enregistrer les adresses', checkout_delivery_address: 'Adresse de Livraison', checkout_billing_address: 'Adresse de Facturation',
    checkout_same_as_delivery: 'Utiliser la même adresse',
    checkout_choose_ph: 'Choisir', checkout_delivery_select: 'Choisir une adresse de livraison', checkout_billing_select: 'Choisir une adresse de facturation',
    checkout_create_delivery_btn: 'Ou créer une nouvelle adresse de livraison', checkout_create_billing_btn: 'Ou créer une nouvelle adresse de facturation',
    checkout_addresses_required: 'Veuillez enregistrer et sélectionner une adresse de livraison (et de facturation).',
    checkout_step_summary_hint: 'Vérifiez la commande avant de confirmer.',
    checkout_col_qty: 'Qté', checkout_col_price: 'Prix', checkout_col_total: 'Total',
    checkout_summary_errors: 'Certains articles du panier ont un problème de prix — retournez à Produits pour vérifier.',
    checkout_coupon_ph: 'Code promo', checkout_apply_coupon: 'Appliquer', checkout_coupon_applied: 'Appliqué ✓',
    checkout_coupon_remove: 'Retirer', checkout_coupon_already_applied: 'Ce coupon est déjà appliqué.',
    checkout_subtotal: 'Sous-total',
    checkout_addr_title: "Titre de l'adresse", checkout_addr_civility: 'Civilité', checkout_addr_firstname: 'Prénom', checkout_addr_name: 'Nom',
    checkout_addr_num: 'Numéro de rue', checkout_addr_street: 'Rue', checkout_addr_city: 'Ville', checkout_addr_zipcode: 'Code postal', checkout_addr_phone: 'Téléphone',
    checkout_reduction: 'Réduction', checkout_reduction_products: 'Produits :', checkout_reduction_order: 'Commande :',
    checkout_step_payment_hint: 'Aucune passerelle de paiement en ligne n\'est configurée — la confirmation enregistre la commande comme payée manuellement.',
    checkout_confirm_order: 'Confirmer la commande',
    checkout_payment_api: 'Payment API',
    checkout_card_name: 'Nom sur la carte', checkout_card_name_ph: 'Nom du titulaire de la carte',
    checkout_card_number: 'Numéro de carte', checkout_card_number_ph: 'Numéro de carte bancaire',
    checkout_card_expiry: "Date d'expiration", checkout_card_month: 'Mois', checkout_card_year: 'Année',
    checkout_card_cvv: 'CVV', checkout_card_cvv_ph: 'Code de sécurité', checkout_pay_now: 'Payer maintenant',
    checkout_error_basket: 'Certains articles ne sont plus disponibles dans la quantité demandée.',
    checkout_error_addresses: 'Les adresses de facturation/livraison n\'ont pas pu être validées.',
    checkout_error_costs: 'Le total de la commande n\'a pas pu être calculé.',
    checkout_error_generic: 'La commande n\'a pas pu être confirmée. Veuillez vérifier les étapes précédentes.',
    checkout_success_title: 'Commande créée', checkout_success_hint: 'La commande {ref} a été créée avec succès.',
    checkout_view_order: 'Voir la commande',
    back: 'Retour', refresh: 'Actualiser', new: 'Nouvelle commande',
    search_placeholder: 'Rechercher référence, client…',
    dr_label: 'Date', dr_all: 'Tout', dr_today: "Aujourd'hui", dr_yesterday: 'Hier',
    dr_last7: '7 derniers jours', dr_last30: '30 derniers jours',
    dr_thismonth: 'Ce mois', dr_lastmonth: 'Mois dernier',
    dr_custom: 'Plage personnalisée', dr_from: 'Du', dr_to: 'Au', dr_apply: 'Appliquer',
    filter_status: 'Tous les statuts',
    filter_date_from: 'Du', filter_date_to: 'Au',
    btn_export: 'Exporter',
    btn_col_manager: 'Colonnes',
    btn_legacy: 'Ancienne vue',
    status_cancelled: 'Annulée',
    kpi_total: 'Commandes total',
    kpi_today: "Aujourd'hui",
    kpi_month: 'Ce mois',
    kpi_pending: 'En attente (new)',
    kpi_revenue: 'CA (mois)',
    exp_title: 'Exporter les commandes', exp_subtitle: '{n} commandes seront exportées', exp_filename: 'commandes',
    col_id: 'ID',
    col_reference: 'Référence',
    col_status: 'Statut',
    col_products: 'Produits',
    col_total: 'Prix',
    col_firstname: 'Prénom',
    col_name: 'Nom',
    col_company: 'Société',
    col_date: 'Date',
    col_action: 'Action',
    tab_information: 'Informations',
    tab_basket: 'Panier',
    tab_addresses: 'Adresses',
    tab_payment: 'Paiement',
    tab_shipping: 'Expédition',
    tab_messages: 'Messages',
    section_status: 'Statut de la commande',
    section_invoice: 'Facture (Upload manuel, Document personnalisé)',
    section_attachments: 'Pièces jointes',
    btn_add_file: 'Ajouter un fichier',
    no_attachments: 'Aucun fichier joint',
    upload_title: 'Fichier',
    upload_subtitle: 'Joindre un fichier à cette commande (ex : facture)',
    upload_select: 'Sélectionner un fichier',
    upload_name_label: 'Nom',
    upload_close: 'Fermer',
    upload_save: 'Enregistrer',
    upload_saving: 'Enregistrement…',
    upload_delete_title: 'Supprimer le fichier', upload_delete_confirm: 'Supprimer « {u} » ? Cette action est irréversible.',
    section_order: 'COMMANDE',
    section_client: 'CLIENT',
    section_basket: 'PANIER',
    section_billing: 'ADRESSE DE FACTURATION',
    section_delivery: 'ADRESSE DE LIVRAISON',
    section_payment: 'PAIEMENT',
    section_shipping: 'EXPÉDITION',
    section_messages: 'MESSAGES',
    field_reference: 'Référence',
    field_company: 'Société',
    field_contact: 'Contact',
    field_date: 'Date commande',
    field_civility: 'Civilité',
    field_firstname: 'Prénom',
    field_name: 'Nom',
    field_middle_name: 'Deuxième prénom',
    field_num: 'Numéro de rue',
    field_street: 'Rue',
    field_building: 'Bâtiment',
    field_stairs: 'Escalier',
    field_city: 'Ville',
    field_state: 'Région',
    field_country: 'Pays',
    field_zipcode: 'Code postal',
    field_phone_mobile: 'Mobile',
    field_phone_landline: 'Téléphone',
    field_complementary: 'Complément',
    basket_col_sku: 'SKU',
    basket_col_name: 'Produit',
    basket_col_category: 'Catégorie',
    basket_col_qty: 'Qté',
    basket_col_price_net: 'Prix (HT)',
    basket_col_price_gross: 'Prix (TTC)',
    basket_col_currency: 'Devise',
    payment_col_type: 'Méthode',
    payment_col_transac: 'Transaction ID',
    payment_col_total: 'Total',
    payment_col_order: 'Commande',
    payment_col_shipping: 'Livraison',
    payment_col_currency: 'Devise',
    payment_col_date: 'Date',
    shipping_col_tracking: 'N° suivi',
    shipping_col_content: 'Notes',
    shipping_col_date: 'Date envoi',
    shipping_add: 'Ajouter un suivi',
    field_tracking: 'N° de suivi',
    field_content: 'Notes',
    field_date_sent: 'Date d\'envoi',
    tip_date_sent: 'Date à laquelle le colis a été envoyé au client.',
    msg_placeholder: 'Écrire un message…',
    msg_send: 'Envoyer',
    msg_empty: 'Aucun message.',
    msg_author_admin: 'ADMIN',
    no_address: 'Aucune adresse enregistrée.',
    no_payments: 'Aucun paiement enregistré.',
    no_shippings: 'Aucune expédition enregistrée.',
    no_items: 'Aucune commande trouvée.',
    count: '{n} commandes — fin de la liste',
    no_basket_items: 'Aucun article dans le panier.',
    tab_returns: 'Retours',
    tab_invoices: 'Factures',
    section_returns: 'RETOUR DE PRODUITS',
    no_returns: 'Aucun retour enregistré.',
    return_col_id: 'ID retour',
    return_col_sku: 'SKU',
    return_col_product: 'Produit',
    return_col_qty: 'Qté',
    return_col_date: 'Date',
    err_reference_required: 'La référence est requise.',
    err_required_fields: 'Veuillez vérifier les champs obligatoires.',
    err_tracking_required: 'Le numéro de suivi est requis.',
    err_message_required: 'Le message ne peut pas être vide.',
    err_cancelled: 'Cette commande est annulée et ne peut pas être modifiée.',
    address_saved: 'Adresse enregistrée.',
    shipping_saved: 'Suivi ajouté.',
    message_sent: 'Message envoyé.',
    status_changed: 'Statut mis à jour.',
  },
})
