<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    
    $formType = '';
    if (!empty($this->zoneconfig['conf']['formType'])){
        $formType = $this->zoneconfig['conf']['formType'];
    }
    
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id. ' '.$data_melisKey?>>	
	<div class="melis-product-heading border-bottom">
		<h3><?php echo $this->translate('tr_meliscommerce_seo_Seo') ?></h3>					
	</div>
	<div class="row">
		<div class="col-xs-12 col-md-3 col-lg-2">
    		<div class="product-text-tab-container">
            	<ul class="nav-tabs product-text-tab">
            		<?php foreach ($this->ecomLang As $val):?>
                		<li class="">
                			<a class="clearfix" data-toggle="tab" href="#<?php echo $val['elang_locale'].'_'.$this->typeId.'_'.$formType.'_seo'?>" aria-expanded="true">
								<?php
                                    $imageData = $val['elang_flag'];
                                    if(!empty($imageData)){
                                        echo '<span class="pull-right"><img src="data:image/jpeg;base64,'. ($imageData) .'" class="imgDisplay pull-right"/></span>';
                                    }else{
                                        echo '<i class="fa fa-globe"></i>';
                                    }                                    
                                ?>
                				<span><?php echo $val['elang_name'] ?></span>
                			</a>
                		</li>
            		<?php endforeach;?>
            	</ul>
            </div>
		</div>
		<div class="col-xs-12 col-md-9 col-lg-10">
			<div class="tab-content">
				<?php foreach ($this->ecomLang As $val):?>
    				<div id="<?php echo $val['elang_locale'].'_'.$this->typeId.'_'.$formType.'_seo'?>" class="tab-pane product-text-tab-content">
    					<div class="me-heading bg-white border-bottom">
                			<h3 class=""><i class="fa fa-language" aria-hidden="true"></i> <?php echo $val['elang_name'] ?></h3>
                		</div>
                		<div class="product-text-tab-form-content">
                		<?php 
                        	$form = clone $this->meliscommerce_seo_form;
                        	$form->setData($this->formDefaultValues);
                        	$form->setAttribute('class', $formType.'_'.$this->typeId.'_seo_form seoForm');
                        	$form->setAttribute('data-langid', $val['elang_id']);
                        	$form->get('eseo_lang_id')->setValue($val['elang_id']);
                        	$form->add(array(
                        	    'name' => 'eseo_'.$formType.'_id',
                        	    'attributes' => array(
                        	        'type'  => 'hidden',
                        	        'value' => $this->typeId,
                        	    )
                        	));
                        	
                        	if (!empty($this->seoData)){
                        	    foreach ($this->seoData As $sval){
                        	        if ($val['elang_id'] == $sval->eseo_lang_id){
                        	            $form->bind($sval);
                        	        }
                        	    }
                        	}
                        	$form->prepare();
                        	
                        	echo $this->form()->openTag($form);
                        	echo $this->melisFieldCollection($form);
                        	echo $this->form()->closeTag();
                    	?>
                		</div>
                    </div>
                <?php endforeach;?>
			</div>
		</div>
	</div>
</div>