<div id="<?= $this->zoneconfig['conf']['id'] ?>" data-melisKey="<?= $this->melisKey; ?>">
	<div class="melis-product-heading border-bottom clearfix" style="margin-bottom: 20px">
    	<?php 
        	if(!empty($this->zoneconfig['interface'])) {
        	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
        	        echo $this->$keyConfig;
        	    }
        	}
       ?>
   </div>
</div>