<?php 
$id = $this->zoneconfig['conf']['id'];
    if(!empty($this->productId)){
        $id = $this->productId . '_' . $id;
    }
?>
<div class="email-alert-area  border-bottom">
	<div class="pdc-heading clearfix">
		<h4><i class="fa fa-cogs"></i>Alert</h4>
	</div>
	<div id="<?= $id; ?>" data-meliskey="<?= $this->melisKey ?>" class="pdc-content">
		<?php 
		echo $this->form()->openTag($this->alertForm);
		echo $this->melisFieldCollection($this->alertForm);
		echo $this->form()->closeTag();
		
		?>
    </div>
    
    <div class="pdc-heading ui-widget available-categories" id ="<?= $this->zoneconfig['conf']['id'] ?>"  data-melisKey="<?= $this->melisKey; ?>">
    
        <select placeholder="Recipient" style="display:none" class="form-control dropdown-settings-email stockAlertSelect" name="prodAttrib">
        <option value=""><?= $this->translate('tr_meliscommerce_settings_page_recepients'); ?></option>
        <?php
        foreach($this->users as $user) {
            echo '<option value="'.$user['id'].'">'.$user['email'].'</option>';
        }
        ?>
        </select>
        <div class="loadAttrCont"><?php echo $this->translate('tr_meliscommerce_products_attributes_lists_loading'); ?></div>
    	<button class="btn btn-success addStockAlertEmail" title="<?= $this->translate('tr_meliscommerce_settings_page_add_recepient') ?>">
    		<i class="fa fa-plus" style="padding-right:10px;"></i>
    		<?= $this->translate('tr_meliscommerce_settings_page_add_recepient') ?>
		</button>
        <script>
            $(function() {
                var emailList = $('select.dropdown-settings-email');
                $('div.loadAttrCont').hide();
                emailList.fadeIn();
                emailList.select2({
                    placeholder: '<?= $this->translate('tr_meliscommerce_settings_page_recepients'); ?>',
                    tags: true,
                    createTag: function (params) {
                        return {
                          id: -1,
                          text: params.term,
                          newOption: true
                        }
                      }
                });
            });
        </script>
	</div>	
    
    
    <br>
    <div id="frmProdAttribNotif"></div>	
	<div class="me-action-button-cont email_area" >
	<?php 
        foreach($this->recipients as $recipient){
    ?>
    	<span class="alert-email-values" data-seaid="<?= $recipient['sea_id']?>" data-userid="<?= $recipient['sea_user_id'] ?>" data-alertemail="<?=  $recipient['sea_email']?>">
        	<span class="ab-attr">
            	<span class="alert-email-value-email">
            		<?= $this->escapeHtml($recipient['sea_email']); ?>
            	</span> 
            	<i class="alert-email-remove fa fa-times"></i>
    		</span>
        </span>
        
    <?php 
        }
        $style = '';
        if(!empty($this->recipients)){
           $style = 'display:none;';
        }
	?>
	<p class="noAlertRecipients" style="<?= $style; ?>"><?=$this->translate('tr_meliscommerce_settings_page_no_recepient') ?> </p>
	</div>
</div>