<?php 
    $id = '';
    $relationType = '';

    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    if (!empty($this->zoneconfig['conf']['docRelationType'])){
        $relationType = $this->zoneconfig['conf']['docRelationType'];
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<?php if($this->relationId): ?>
<div <?php echo $id. ' '.$data_melisKey?> class="ecom-doc-container" data-doc-relation-type="<?= $relationType; ?>" data-doc-relation-id="<?= $this->relationId; ?>" data-doc-type="file">
	<div class="pdc-heading clearfix">
		<h4>
			<i class="fa fa-paperclip"></i> <?php echo $this->translate('tr_meliscommerce_documents_file_attachments')?>
		</h4>
		<button class="btn btn-success addFileImageDocument" data-type="file">
			<i class="fa fa-plus"></i>
			<?php echo $this->translate('tr_meliscommerce_documents_file_attachments_button')?>
		</button>
	</div>							
    <?php 
    if(!empty($this->zoneconfig['interface'])) {
        foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
            echo $this->$keyConfig;
        }
    }
    ?>
</div>
<?php endif; ?>