<?php
	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>
<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="nav-item active">
							<a href="#<?php echo $id ?>" class="nav-link glyphicons more_items" data-bs-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate('tr_meliscommerce_duplication_Duplicate_variant') ?></a>
						</li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" <?php echo $id ?>>
                            <div class="row">
                            	<div class="col-md-12">
                                    <p class="duplication-note"><?php echo $this->translate('tr_meliscommerce_duplication_variant_note')?></p>
                                    <table class="duplication-table">
                                    	<tr>
                                    		<td>
                                    			<label class="duplicate-table-label"><?php echo $this->translate('tr_meliscommerce_duplication_Duplicate_images')?></label>
                                    		</td>
                                    		<td>
                                        		<div class="make-switch modalDuplicateOptions" data-label-icon="fa fa-arrows-h" data-on-label="<?php echo $this->translate('tr_meliscommerce_duplication_common_yes')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_duplication_common_no')?>">
                                                    <input type="checkbox" id="duplicate_images" checked>
                                                </div>
                                    		</td>
                                    	</tr>
                                    	<tr>
                                    		<td>
                                    			<label class="duplicate-table-label"><?php echo $this->translate('tr_meliscommerce_duplication_Duplicate_documents')?></label>
                                    		</td>
                                    		<td>
                                    			<div class="make-switch modalDuplicateOptions" data-label-icon="fa fa-arrows-h" data-on-label="<?php echo $this->translate('tr_meliscommerce_duplication_common_yes')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_duplication_common_no')?>">
                                                    <input type="checkbox" id="duplicate_documents" checked>
                                                </div>
                                    		</td>
                                    	</tr>
                                    	<tr>
                                    		<td>
                                    			<label class="duplicate-table-label"><?php echo $this->translate('tr_meliscommerce_duplication_Put_online')?></label>
                                    		</td>
                                    		<td>
                                        		<div class="make-switch modalDuplicateOptions" data-label-icon="fa fa-arrows-h" data-on-label="<?php echo $this->translate('tr_meliscommerce_duplication_common_yes')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_duplication_common_no')?>">
                                                    <input type="checkbox" id="put_online">
                                                </div>
                                    		</td>
                                    	</tr>
                                    	<tr>
                                    		<td></td>
                                    		<td style="padding-top: 18px;">
                                    			<div class="form-group">
                                            		<label class="duplicate-table-label"><?php echo $this->translate('tr_meliscommerce_duplication_Var_sku')?>
                                            			<i class="fa fa-info-circle fa-lg" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_meliscommerce_variant_main_information_main_variant_input_label tooltip')?>"></i>
                                            		</label>
                                        		</div>
                                    		</td>
                                    	</tr>
                                    	<tr>
                                    		<td>
                                    			<label class="duplicate-table-label" id="<?php echo $this->variantId.'_var_sku_label'?>"><?php echo $this->translate('tr_meliscommerce_duplication_Var_sku').' ('.$this->variantSku.')'?></label>
                                    		</td>
                                    		<td>
                                        		<?php 
                                                    $form = $this->meliscommerce_duplications_sku_form;
                                                    $form->prepare();
                                                    $form->get('var_sku')->setLabel('');
                                                    echo $this->form()->openTag($form);
                                                    echo $this->melisFieldCollection($form);
                                                    echo $this->form()->closeTag();
                                                ?>
                                    		</td>
                                    	</tr>
                                    </table>
                                    
									<div class="footer-modal d-flex flex-row justify-content-between">
                                 		<button data-bs-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_duplication_common_close')?></button>
                                 		<button class="btn btn-success" id="melisComStartDuplicateVariant" data-varianid="<?php echo $this->variantId?>"><i class="fa fa-clone"></i>  <?php echo $this->translate('tr_meliscommerce_duplication_common_duplicate') ?></button>
                                 	</div>
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
	$('.modalDuplicateOptions').bootstrapSwitch();
</script>
