<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
    } 
    $order = empty($this->layout()->order->ord_id)? 0 : $this->layout()->order->ord_id;
    $order = empty(!$this->layout()->order->ord_reference)? $this->layout()->order->ord_reference : $order;
?>
<h1 id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="content-heading"><a href="#" class="orderList" style="color: #686868;"><?= $this->translate('tr_meliscommerce_orders_Orders')?></a> / <?= $order ?></h1>