<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
    }
?>

<ul id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="nav nav-tabs product-text-tab">
	<?php 
	$c = 0 ;
	foreach($this->addressTypes as $type):
	if($c<1){$active='active';}else{$active='';}
	$name = $this->orderId .'_'. $type->catypt_name;
	?>
	<li class="nav-item <?= $active?>">
		<a class="nav-link clearfix" data-bs-toggle="tab" data-bs-target="#<?= $name?>" href="#<?= $name?>" aria-expanded="true">
			<i class=""></i>
			<span><?= $type->catypt_name ?></span>
		</a>
	</li>
	<?php 
	$c++;
	endforeach;?>
</ul>