<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
    }
?>
<div class="row">
	<div class="col-12 col-md-2 layout-timeline-spacer"></div>
	<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="col-12 col-md-10">
		<?php 
			if(!empty($this->zoneconfig['interface'])) {
				foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
					echo $this->$keyConfig;
				}
			}
		?>
	</div>
</div>