<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
    }
    $collapse = 'collapse in';
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="tab-pane active custom-field-type">
	
	<?php 
	$forms = $this->orderShippingForm;
	$shippings = $this->shippings;
	for($c = 0; $c < count($forms); $c++):
	if($c>0){
	    $collapse = 'collapse';
	}
	?>
	<a class="btn btn-primary form-control collapsed a-accordion" data-toggle="collapse" href="#<?= $shippings[$c]->oship_id.'_'.$this->melisKey?>" aria-expanded="false" aria-controls="shipping1">
		<span><?= $shippings[$c]->oship_tracking_code ?></span>
		<span style="float:right"><?=$shippings[$c]->oship_date_sent;?></span>
		
	</a>
	<div class="<?= $collapse; ?>" id="<?= $shippings[$c]->oship_id.'_'.$this->melisKey?>">
		<br>
		<?php
		
    	
    	    echo $this->form()->openTag($forms[$c]);
    	    echo $this->melisFieldCollection($forms[$c]);
    	    echo $this->form()->closeTag();
    	
    	?>
	</div>
	<br>
	<?php 
	endfor;
	?>
</div>
<?= $this->datePickerInit; ?>	