<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
	$id .= $this->orderId . '_' . $this->zoneconfig['conf']['id'];
}
$c = 0;
$collapse = 'collapse in';
$collapsed = '';

$optyName = (!empty($payment->payment_type)) ? $payment->payment_type->opty_name : null;
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="tab-pane active custom-field-type">
	<?php foreach ($this->payments as $payment): ?>
		<a class="btn btn-primary form-control a-accordion" data-bs-toggle="collapse" href="#<?= $payment->opay_id . '_' . $this->melisKey ?>" aria-expanded="false" aria-controls="payment1">
			<span><?= $this->translate('tr_meliscommerce_orders_content_tab_paymnet') . ' ' . $payment->payment_type->opty_name ?></span>
			<span style="float:right"><?= $payment->opay_date_payment ?></span>
		</a>
		<div class="<?= $collapse ?> show" id="<?= $payment->opay_id . '_' . $this->melisKey ?>">
			<table class="info-table">
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_price') ?></label></td>
					<td><?= $payment->cur_symbol . number_format($payment->opay_price_order, 2) ?></td>
				</tr>
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_shipment') ?></label></td>
					<td><?= $payment->cur_symbol . number_format($payment->opay_price_shipping, 2) ?></td>
				</tr>
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_price_with_discount') ?></label></td>
					<td><?= $payment->cur_symbol . number_format($payment->opay_price_total, 2) ?></td>
				</tr>
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_paid') ?></label></td>
					<td><?= $payment->cur_symbol . number_format($payment->opay_transac_price_paid_confirm, 2) ?></td>
				</tr>
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_type') ?></label></td>
					<td><?= $optyName ?? null ?></td>
				</tr>
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_validation') ?></label></td>
					<td><?= $payment->opay_transac_id ?></td>
				</tr>
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_date') ?></label></td>
					<td><?= $payment->opay_date_payment ?></td>
				</tr>
				<tr>
					<td><label><?= $this->translate('tr_meliscommerce_order_payment_coupon') ?></label></td>
					<td>
						<?php
						$coupons = array();
						$labelContainer = '<span class="orderPaymentCouponLink" data-couponid="%s"  data-couponname="%s">%s (%s) x %s</span>';
						foreach ($payment->coupons as $coupon) {
							$coupons[]  = sprintf(
								$labelContainer,
								$coupon->coup_id,
								$coupon->coup_code,
								$coupon->coup_code,
								($coupon->coup_percentage) ? $coupon->coup_percentage . '%' : $payment->cur_symbol . number_format($coupon->coup_discount_value, 2),
								$coupon->qty_used
							);
						}
						echo implode(', <br>', $coupons);
						?>
					</td>
				</tr>
			</table>
		</div>
		<br>
	<?php
		$collapse = 'collapse';
		$collapsed = 'collapsed';
		$c++;
	endforeach;
	?>
</div>