<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
    }
    $icon = '';
    if (!empty($this->zoneconfig['conf']['icon'])){
        $icon = $this->zoneconfig['conf']['icon'];
    }
    $name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
?>
<a class="btn btn-success addMessage" title="<?= $this->translate($name); ?>">
	<i class="<?= $icon; ?>" style="padding-right:10px;"></i>
	<?= $this->translate($name); ?>
</a>
