<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
    }
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="col-12 col-md-10">
	<?php 
		if(!empty($this->zoneconfig['interface'])) {
			foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
				echo $this->$keyConfig;
			}
		}
?>
</div>