<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->orderId.'_'.$this->zoneconfig['conf']['id'];
    }
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>">
	<?php 
		$this->melisGenericTable()->setTable(array(
		    'id' => $this->orderId.'_tableOrderBasketList',
		    'class' => 'table table-striped table-primary dt-responsive nowrap',
		    'cellspacing' => '0',
		    'width' => '100%'
	     ));
        $columns = array();
        $columnStyle = array();

        foreach($this->tableColumns as $colName => $columnText)
        {
            $columns[] = $columnText['text'];
        }
		$this->melisGenericTable()->setColumns($columns);

		echo $this->melisGenericTable()->renderTable();
	?>
	<script type="text/javascript">			
		$(document).ready(function() {
			<?php echo $this->getToolDataTableConfig; ?>
		});
	</script>
</div>	