<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = ' id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    
    $name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
    
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<button class="btn btn-success addCategory" disabled title="<?php echo $this->translate('tr_meliscommerce_categories_category_no_selected_catalog_category')?>" <?php echo $id.' '.$data_melisKey; ?> ><i class="fa fa-plus"></i> <?php echo $this->translate($name)?></button>