<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div id="categoryTreeViewPanel" class="card-collapse collapse show" style="height: auto;" <?php echo $id.' '.$data_melisKey; ?>>
	<div class="card-body">
		<div class="spacing-x2 innerAll">
			<div class="row">
    			<?php 
                	if(!empty($this->zoneconfig['interface'])) {
                	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                	        echo $this->$keyConfig.' ';
                	    }
                	}
                ?>
            </div>
        </div>
	</div>
</div>