<?php 
	$id = 'id="';
	if (!empty($this->variantId)){
		$id .= $this->variantId.'_';
	}
	
	$id .= $this->zoneconfig['conf']['id'].'"';
	$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div class="me-hl col-xs-12 col-md-9" <?php echo $id. ' '. $data_melisKey;?>>
	<?php 
    	if(!empty($this->zoneconfig['interface'])) {
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
    	        echo $this->$keyConfig;
    	    }
    	}
	?>
</div>