<?php 
    $id = 'id="';
	if (!empty($this->variantId)){
		$id .= $this->variantId.'_';
	}
	
	$id .= $this->zoneconfig['conf']['id'].'"';
	$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="page-head-container">
	<div class="me-heading bg-white innerAll border-bottom" <?php echo $id.' '.$data_melisKey; ?>>      		
		<div class="row">
		<?php 
			if(!empty($this->zoneconfig['interface'])) {
				foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
					echo $this->$keyConfig.' ';
				}
			}
		?>     		
		</div>
				
	</div>
</div>