<?php 
	$id = 'id="';
	if (!empty($this->variantId)){
		$id .= $this->variantId.'_';
	}
	
	$id .= $this->zoneconfig['conf']['id'].'"';
	$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?= $id. ' '. $data_melisKey?> class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive" style="margin-bottom:0">
	<div class="widget-head nav">
		<ul class="tabs-label nav-tabs nav">
			<?php 
            	if(!empty($this->zoneconfig['interface'])) {
            	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
            	        echo $this->$keyConfig;
            	    }
            	}
        	?>
		</ul>
	</div>			
</div>