<?php 
	$id = 'id="';
    if (!empty($this->variantId)){
        $id .= $this->variantId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
    
    $var_sku = (!empty($this->layout()->variantObj)) ? $this->layout()->variantObj->getVariant()->var_sku : $this->translate('tr_meliscommerce_variant_main_information_sku_new');
    $prod_name = empty($this->prodTitle) ? '' : $this->prodTitle;
?>
<h1 class="content-heading" <?php echo $id. ' '. $data_melisKey;?>>
<a href="products.php" style="color: #686868;"><?= $this->translate('tr_meliscommerce_variants_Products');?></a>
 / <a href="#" style="color: #686868;"><?= $this->escapeHtml($prod_name) ?></a>  / <?= $this->escapeHtml($var_sku) ?></h1>
