<?php 
    $name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
            $name = $this->zoneconfig['conf']['name'];
        }
    $id = 'id="';
    if (!empty($this->variantId)){
        $id .= $this->variantId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<a <?= $id. ' '. $data_melisKey?> data-toggle="modal" data-target="#addFile" class="btn btn-success add-product" title="Add files">
	<i class="fa fa-link" style="padding-right:10px;"></i>
	<?= $name;?>
</a>