<?php 
    $id = 'id="';
    if (!empty($this->variantId)){
        $id .= $this->variantId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<ul <?= $id. ' '. $data_melisKey?> class="nav-tabs product-text-tab">
	<li class="active">
		<a class="clearfix" data-bs-toggle="tab" href="#ptext-french" aria-expanded="true">
			&nbsp;<img src="html/ecommerce/images/fr.png">
			<span>French</span>
			<i class="fa fa-times"></i>
		</a>
	</li>
	<li class="">
		<a class="clearfix" data-bs-toggle="tab" href="#ptext-english" aria-expanded="false">
			&nbsp;<img src="html/ecommerce/images/en.png">
			<span>English</span>
			<i class="fa fa-times"></i>
		</a>
	</li>
</ul>	