<?php 
    $icon = '';
    if (!empty($this->zoneconfig['conf']['icon'])){
        $icon = $this->zoneconfig['conf']['icon'];
    }
    $name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
    $id = 'id="';
    if (!empty($this->variantId)){
        $id .= $this->variantId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<a <?= $id. ' ' .$data_melisKey?> data-toggle="modal" data-target="#addLanguage" class="btn btn-success add-product" title="Add Language">
	<i class="<?= $icon;?>" style="padding-right:10px;"></i>
	<?= $name;?>
</a>
