<?php 
    $id = 'id="';
    if (!empty($this->variantId)){
        $id .= $this->variantId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?= $id. ' '. $data_melisKey?> class="portfolioContainer">						 
	<div class="a objects france">
		
		<div class="me-p-image">
		   <img src="html/ecommerce/images/gallery-2/15.jpg">
		   
		   <div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
	   </div>
	   
	</div>
 
	<div class="a people places usa">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/2.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>    
 
	<div class="a food">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/3.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a href="#">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
	 
	<div class="a people places france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/4.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
 
	<div class="a places objects">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/3.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
 
	<div class="a people food objects usa">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/5.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image" >
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>
 
	<div class="a food objects">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/8.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>    
	 
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/avatar-large-girl.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>   
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/6.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>  
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/7.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div> 
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/fashion/female/1.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>    
	
	<div class="a food usa france">
		<div class="me-p-image">
			<img src="html/ecommerce/images/gallery-2/1.jpg">
			<div class="hover-details">
				<div class="me-p-btn-cont">
					<a data-toggle="modal" data-target="#viewImage">
						<i class="fa fa-eye"></i>
					</a>
					<a data-toggle="modal" data-target="#editImage">
						<i class="fa fa-pencil"></i>
					</a>
					<a class="delete-p-image">
						<i class="fa fa-times"></i>
					</a>
				</div>
		   </div>
		</div>
	</div>   
 
</div>