<style>
.default-form-err-msg-plugin li{
    display: inherit;
}
</style>
<?php if (!empty($this->errors)){?>
    <div class="alert alert-danger">
    	<?php foreach ($this->errors As $err){?>
    		<?php foreach ($err As $error){?>
    			<p><?php echo $error?></p>
    		<?php }?>
    	<?php }?>
    </div>
<?php }?>
<?php
    if ($this->hasStock)
    {
        $form = $this->addToCcart;
        $form->prepare();
        echo $this->form()->openTag($form);
        
        foreach ($form->getElements() As $key => $val)
        {
            echo '<div class="form-group">';
            if ($val->getLabel())
            {
                echo $this->formLabel($val);
            }
            echo $this->formElement($val);
            echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
            echo '</div>';
        }
        
        echo '<button type="submit" class="btn btn-default">'.$this->translate('tr_meliscommerce_general_common_submit').'</button>';
        echo $this->form()->closeTag(); 
    }
?>