<style>
.default-form-err-msg-plugin li{
    display: inherit;
}
</style>
<?php if ($this->orderMessages){ ?>
	<h3><?= $this->translate('tr_meliscommerce_plugin_order_messages_area' ); ?></h3>
    <?php foreach($this->orderMessages as $message){ ?>
    	<div class="media">
          	<div class="media-body">
            	<h4 class="media-heading"><i class="fa fa-user"></i> <?= $message['firstName'] .' '. $message['middleName'] .' '. $message['lastName'] ?> <small><?= date("F d, Y " ,strtotime($message['omsg_date_creation'])) ?> </span> <span>, at <?= date("h:i a" ,strtotime($message['omsg_date_creation'])) ?></small></h4>
            	<p><?= $message['omsg_message']?></p>
          	</div>
        </div>
    <?php } ?>
<?php }?>
<?php
    $form = $this->addMessageForm;
	$form->prepare();
	echo $this->form()->openTag($form); 
	
	foreach ($form->getElements() As $key => $val)
	{
	    echo '<div class="form-group">';
	    if ($val->getLabel())
	    {
	        echo $this->formLabel($val);
	    }
	    echo $this->formElement($val);
	    echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
	    echo '</div>';
	}
    
    echo '<button type="submit" class="btn btn-default">'.$this->translate('tr_meliscommerce_general_common_submit').'</button>';
	echo $this->form()->closeTag(); 
?>