<?php if($this->hasData) { ?>
    <table class="table">
        <thead>
            <tr>
                <td><b>Date</b></td>
                <td><b>Reference</b></td>
                <td><b>Status</b></td>
                <td><b>Items</b></td>
                <td><b>Total</b></td>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($this->orders as $order) {
                    echo "<tr>";
                    echo "<td>" . $order['date'] . "</td>";
                    echo "<td>" . $order['reference'] . "</td>";
                    echo "<td>" . $order['status'] . "</td>";
                    echo "<td>" . $order['itemCount'] . "</td>";
                    echo "<td>" . $order['currency'].number_format($order['total'], 2). "</td>";
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <!--pagination start-->
    <?php
        echo $this->paginationcontrol(
            $this->orders,
            'Sliding',
            'MelisCommerceOrder/order-history-paginator',
            array('orderHistoryBeforeAfter' => $this->orderHistoryBeforeAfter)
        );
    ?>
<?php } else { ?>
    <div class="text-center">
        <span><?= $this->translate('tr_meliscommerce_order_history_empty_order');?></span>
    </div>
<?php } ?>
