<table>
    <thead>
    	<tr>
        	<td>Date</td>
        	<td>Reference</td>
        	<td>Status</td>
        	<td>Items</td>
        	<td>Total</td>
    	</tr>
    </thead>
    <tbody>
    <?php 
    foreach($this->orders as $order){
        echo "<tr>";
        echo "<td>" . $order['date'] . "</td>";
        echo "<td>" . $order['reference'] . "</td>";
        echo "<td>" . $order['status'] . "</td>";
        echo "<td>" . $order['itemCount'] . "</td>";
        echo "<td>" . $order['currency'] . "</td>";
        echo '</tr>';
    }
    
    ?>
    </tbody>    
</table>