<?php 
    $id = 'id="';
    if (!empty($this->prefixId)){
        $id .= $this->prefixId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?= $id. ' '. $data_melisKey?> class="tab-content variant-prices-forms">
	<?php
	foreach($this->data as $key => $groups){?>
    <div id="<?= $groups['tab_id']?>" class="tab-pane prices-accordion">
    <?php
	    foreach($groups['data'] as $groupId => $group){
	        $status = $groupId == 1 ? 'false' : 'true';
	        $show = $groupId == 1 ? 'show' : '';
	        ?>
            <div class="widget" data-toggle="collapse-widget" data-collapse-closed="<?= $status; ?>">
                <div class="widget-head melis-primary-bg">
                    <h4 class="heading"><?= $this->translate('Group').': '.$group['group_name']; ?></h4>
                </div>
                <div class="widget-body <?= $show;?>">
                    <?php
                    echo $this->form()->openTag($this->forms[$key]['data'][$groupId]);
                    echo $this->melisFieldCollection($this->forms[$key]['data'][$groupId]);
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
	    <?php } ?>
    </div>
	<?php } ?>
</div>