<?php 
    $id = 'id="';
    if (!empty($this->prefixId)){
        $id .= $this->prefixId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<ul <?= $id. ' '. $data_melisKey?> class="nav-tabs product-text-tab country-price-tab" data-id="<?= $this->prefixId ?>">
	<?php 
	foreach ($this->countries as $country){
	    echo $country;
	}
	?>
</ul>