<?php 
	$id = 'id="';
    if (!empty($this->prefixId)){
        $id .= $this->prefixId.'_';
    }
    
    $id .= $this->zoneconfig['conf']['id'].'"';
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div class="melis-product-heading border-bottom" <?php echo $id. ' '. $data_melisKey;?>>
	<?php 
    	if(!empty($this->zoneconfig['interface'])) {
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
    	        echo $this->$keyConfig;
    	    }
    	}
	?>
</div>