import { mergeDict } from '../../shared/i18n'

/** Dictionnaire de l'outil Coupons (fusionné avec les clés COMMUNES). */
export const DICT = mergeDict({
  fr: {
    title: 'Coupons', subtitle: 'Codes de réduction MelisCommerce.',
    new: 'Nouveau coupon', search_placeholder: 'Rechercher un code…',
    filter_status: 'Tous les statuts',
    btn_export: 'Exporter', btn_col_manager: 'Colonnes',
    exp_title: 'Exporter les coupons', exp_subtitle: '{n} coupons seront exportés', exp_filename: 'coupons',
    del_title: 'Supprimer le coupon', del_confirm: 'Supprimer le coupon « {u} » ? Cette action est irréversible.',
    kpi_total: 'Total', kpi_active: 'Actifs', kpi_uses: 'Utilisations',
    col_id: 'ID', col_code: 'Code', col_status: 'Statut', col_discount: 'Réduction',
    col_uses: 'Utilisations', col_valid: 'Validité', col_action: 'Action',
    no_items: 'Aucun coupon trouvé.', count: '{n} coupons — fin de la liste',
    tab_information: 'Informations', tab_clients: 'Clients assignés', tab_products: 'Produits assignés', tab_orders: 'Commandes',
    status_label: 'STATUT', yes: 'Oui', no: 'Non',
    section_properties: 'Propriétés', section_general_data: 'Données générales', section_values: 'Valeurs',
    field_code: 'Code',
    field_percentage: 'Pourcentage', field_discount_value: 'Montant',
    field_max_use: "Limite d'utilisation", field_current_use: 'Utilisations',
    field_valid_start: 'Date de début', field_valid_end: 'Date de fin',
    field_assign_clients: 'Assigner à des comptes', field_assign_products: 'Assigner à des produits',
    tip_code: 'Code unique saisi par le client à la commande.',
    tip_valid_start: 'Date à partir de laquelle le coupon est utilisable.',
    tip_valid_end: 'Date après laquelle le coupon expire.',
    tip_assign_clients: 'Limiter ce coupon à des comptes clients spécifiques.',
    tip_assign_products: 'Limiter ce coupon à des produits spécifiques.',
    tip_percentage: 'Réduction en pourcentage du montant de la commande.',
    tip_discount_value: 'Réduction en montant fixe.',
    tip_current_use: "Nombre de fois où ce coupon a déjà été utilisé.",
    tip_max_use: "Nombre maximum d'utilisations autorisées.",
    err_code_required: 'Le code est obligatoire.', err_discount_required: 'Renseignez un pourcentage ou un montant de réduction.',
    assign_clients_title: 'Clients assignés', assign_clients_add: 'Assigner un client', assign_clients_empty: 'Aucun client assigné.',
    assign_products_title: 'Produits assignés', assign_products_add: 'Assigner un produit', assign_products_empty: 'Aucun produit assigné.',
    client_list_title: 'Liste des clients', product_list_title: 'Liste des produits',
    pick_client: '— Choisir un client —', pick_product: '— Choisir un produit —',
    orders_empty: 'Ce coupon n\'a pas encore été utilisé.',
    orders_col_order: 'Commande', orders_col_qty: 'Quantité utilisée', orders_col_date: 'Date',
    save_first: 'Enregistrez le coupon pour gérer cette section.',
    lt_show: 'Afficher', lt_search: 'Rechercher :', lt_action: 'Action',
    lt_showing: 'Affichage de {a} à {b} sur {n} entrées', lt_previous: 'Précédent', lt_next: 'Suivant',
    col_client_id: 'ID', col_account_name: 'Nom du compte', col_company: 'Société',
    col_product_ref: 'Référence', col_product_name: 'Nom',
    orders_col_status: 'Statut', orders_col_products: 'Produits', orders_col_price: 'Prix',
    orders_col_civility: 'Civilité', orders_col_firstname: 'Prénom', orders_col_lastname: 'Nom',
    orders_filter_status: 'Non sélectionné', orders_search_ph: 'Rechercher…',
  },
  en: {
    title: 'Coupons', subtitle: 'MelisCommerce discount codes.',
    new: 'New coupon', search_placeholder: 'Search a code…',
    filter_status: 'All statuses',
    btn_export: 'Export', btn_col_manager: 'Columns',
    exp_title: 'Export coupons', exp_subtitle: '{n} coupons will be exported', exp_filename: 'coupons',
    del_title: 'Delete coupon', del_confirm: 'Delete coupon "{u}"? This action cannot be undone.',
    kpi_total: 'Total', kpi_active: 'Active', kpi_uses: 'Uses',
    col_id: 'ID', col_code: 'Code', col_status: 'Status', col_discount: 'Discount',
    col_uses: 'Uses', col_valid: 'Validity', col_action: 'Action',
    no_items: 'No coupon found.', count: '{n} coupons — end of list',
    tab_information: 'Information', tab_clients: 'Assigned clients', tab_products: 'Assigned products', tab_orders: 'Orders',
    status_label: 'STATUS', yes: 'Yes', no: 'No',
    section_properties: 'Properties', section_general_data: 'General Data', section_values: 'Values',
    field_code: 'Code',
    field_percentage: 'Percentage', field_discount_value: 'Amount',
    field_max_use: 'Max use limit', field_current_use: 'Uses',
    field_valid_start: 'Start date', field_valid_end: 'End date',
    field_assign_clients: 'Assign to accounts', field_assign_products: 'Assign to products',
    tip_code: 'Unique code entered by the client at checkout.',
    tip_valid_start: 'Date from which the coupon becomes usable.',
    tip_valid_end: 'Date after which the coupon expires.',
    tip_assign_clients: 'Restrict this coupon to specific client accounts.',
    tip_assign_products: 'Restrict this coupon to specific products.',
    tip_percentage: 'Discount as a percentage of the order amount.',
    tip_discount_value: 'Discount as a fixed amount.',
    tip_current_use: 'Number of times this coupon has already been used.',
    tip_max_use: 'Maximum number of allowed uses.',
    err_code_required: 'Code is required.', err_discount_required: 'Set a percentage or a discount amount.',
    assign_clients_title: 'Assigned clients', assign_clients_add: 'Assign a client', assign_clients_empty: 'No client assigned.',
    assign_products_title: 'Assigned products', assign_products_add: 'Assign a product', assign_products_empty: 'No product assigned.',
    client_list_title: 'Client list', product_list_title: 'Product list',
    pick_client: '— Pick a client —', pick_product: '— Pick a product —',
    orders_empty: 'This coupon has not been used yet.',
    orders_col_order: 'Order', orders_col_qty: 'Quantity used', orders_col_date: 'Date',
    save_first: 'Save the coupon first to manage this section.',
    lt_show: 'Show', lt_search: 'Search:', lt_action: 'Action',
    lt_showing: 'Showing {a} to {b} of {n} entries', lt_previous: 'Previous', lt_next: 'Next',
    col_client_id: 'ID', col_account_name: 'Account Name', col_company: 'Company',
    col_product_ref: 'Reference', col_product_name: 'Name',
    orders_col_status: 'Status', orders_col_products: 'Products', orders_col_price: 'Price',
    orders_col_civility: 'Civility', orders_col_firstname: 'First name', orders_col_lastname: 'Last name',
    orders_filter_status: 'Not selected', orders_search_ph: 'Search…',
  },
})
