<?php $this->urlQryStr = !empty($this->urlQryStr) ? $this->urlQryStr : array()?>
<div class="text-center">
    <?php if ($this->pageCount): ?>
        <nav aria-label="Page navigation center">
            <ul class="pagination">
            	
            	<!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                    	<a href="<?php echo $this->MelisLink($this->idPage, true).'?'.http_build_query(array_merge($this->urlQryStr, array($this->currentUrlVar => $this->previous))); ?>" class="previous page-numbers">
                			<span aria-hidden="true">&laquo;</span>
            			</a>
        			</li>
                <?php else: ?>
                    <li class="disabled">
                    	<a href="#">
                			<span aria-hidden="true">&laquo;</span>
            			</a>
        			</li>
                <?php endif; ?>
                
                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                	<?php 
                	    // To limit the number of pagination before and after the current page
                	    if ($page >= ($this->current - $this->nbPageBeforeAfter) && $page <= ($this->current + $this->nbPageBeforeAfter)):
            	    ?>
                        <?php if ($page != $this->current): ?>
                            <li>
                            	<a href="<?php echo $this->MelisLink($this->idPage, true).'?'.http_build_query($this->urlQryStr); ?>">
                            		<?php echo $page; ?>
                            	</a>
                        	</li>
                        <?php else: ?>
                            <li class="active"><span ><?php echo $page; ?></span></li>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                
                <!-- Previous page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                    	<a href="<?php echo $this->MelisLink($this->idPage, true).'?'.http_build_query(array_merge($this->urlQryStr, array($this->currentUrlVar => $this->next))); ?>">
                			<span aria-hidden="true">&raquo;</span>
            			</a>
        			</li>
                <?php else: ?>
                    <li class="disabled">
                    	<a href="#">
                			<span aria-hidden="true">&raquo;</span>
            			</a>
        			</li>
                <?php endif; ?>
            </ul>
        </nav>
    <?php endif; ?>
</div>