<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><?= $this->translate('tr_meliscommerce_plugin_account_profile_info'); ?></a></li>
        <li role="presentation"><a href="#deliver-address" aria-controls="deliver-address" role="tab" data-toggle="tab"><?= $this->translate('tr_meliscommerce_plugin_account_delivery_address'); ?></a></li>
        <li role="presentation"><a href="#billing-address" aria-controls="billing-address" role="tab" data-toggle="tab"><?= $this->translate('tr_meliscommerce_plugin_account_billing_address'); ?></a></li>
        <li role="presentation"><a href="#cart" aria-controls="cart" role="tab" data-toggle="tab"><?= $this->translate('tr_meliscommerce_plugin_account_my_cart'); ?></a></li>
        <li role="presentation"><a href="#order-list" aria-controls="order-list" role="tab" data-toggle="tab"><?= $this->translate('tr_meliscommerce_plugin_account_order_history'); ?></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
    	<br>
    	<br>
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            <?php echo $this->profile ?>
        </div>
        <div role="tabpanel" class="tab-pane fade in" id="deliver-address">
            <?php echo $this->deliveryAddress ?>
        </div>
        <div role="tabpanel" class="tab-pane fade in" id="billing-address">
            <?php echo $this->billingAddress ?>
        </div>
        <div role="tabpanel" class="tab-pane fade in" id="cart">
            <?php echo $this->cart ?>
        </div>
        <div role="tabpanel" class="tab-pane fade in" id="order-list">
            <?php echo $this->orderHistory ?>
        </div>
    </div>
</div>

