<style>
.default-form-err-msg-plugin li{
    display: inherit;
}
</style>
<?php if ($this->message):?>
	<h2><?php echo $this->message?></h2>
<?php endif;?>

<?php
    /**
     * Select Delivery addresses form
     */
    if (!is_null($this->selectDeliveryAddress))
    {
        $form = $this->selectDeliveryAddress;
        $form->prepare();
        echo $this->form()->openTag($form);
        
        foreach ($form->getElements() As $key => $val)
        {
            echo '<div class="form-group">';
            if ($val->getLabel())
            {
                echo $this->formLabel($val);
            }
            echo $this->formElement($val);
            echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
            echo '</div>';
        }
        
        echo $this->form()->closeTag(); 
    }
    
    /**
     * Delivery address form
     */
    $form = $this->deliveryAddress;
	$form->prepare();
	echo $this->form()->openTag($form); 
	
	foreach ($form->getElements() As $key => $val)
	{
	    echo '<div class="form-group">';
	    if ($val->getLabel())
	    {
	        echo $this->formLabel($val);
	    }
	    echo $this->formElement($val);
	    echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
	    echo '</div>';
	}
    
	if ($this->showDeleteButton)
	{
	    echo '<button type="submit" name="delivery_address_delete_submit" class="btn btn-danger" value="1">'.$this->translate('tr_meliscommerce_general_common_delete').'</button>';
	}
	
    echo '<button type="submit" class="btn btn-default">'.$this->translate('tr_meliscommerce_general_common_save').'</button>';
	echo $this->form()->closeTag(); 
?>