<style>
.default-form-err-msg-plugin li{
    display: inherit;
}
</style>
<?php
	$form = $this->login;
	$form->prepare();
	echo $this->form()->openTag($form); 
	
	foreach ($form->getElements() As $key => $val)
	{
	    echo '<div class="form-group">';
	    if ($val->getLabel())
	    {
	        echo $this->formLabel($val);
	    }
	    echo $this->formElement($val);
	    echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
	    echo '</div>';
	}
    
    echo '<button type="submit" class="btn btn-default">'.$this->translate('tr_meliscommerce_plugin_login_login').'</button>';
	echo $this->form()->closeTag(); 
?>