<style>
.default-form-err-msg-plugin li{
    display: inherit;
}
</style>
<h4 align="center"><?php echo $this->title?></h4>
<p><?php echo $this->message ?></p>
<?php
    $form = $this->lostPassword;
	$form->prepare();
	echo $this->form()->openTag($form); 
	
	foreach ($form->getElements() As $key => $val)
	{
	    echo '<div class="form-group">';
	    if ($val->getLabel())
	    {
	        echo $this->formLabel($val);
	    }
	    echo $this->formElement($val);
	    echo $this->formElementErrors($val, array('class' => 'default-form-err-msg-plugin text-danger'));
	    echo '</div>';
	}
    
    echo '<button type="submit" class="btn btn-default">'.$this->translate('tr_meliscommerce_general_common_submit').'</button>';
	echo $this->form()->closeTag(); 
?>