<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])){
    $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
}
$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<div <?php echo $id. ' '.$data_melisKey?>>
    <?php if($this->canAccess) { ?>
        <div class="link-account float-right">
            <div class="row">
                <div class="col-md-5">
                    <div class="input-autosuggest">
                        <input placeholder="<?= $this->translate('tr_meliscommerce_contact_account_name');?>" data-contactid="<?= $this->contactId;?>" data-accountid="" class="form-control link-account-data" type="text"/>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="linkAccountBtn">
                        <button disabled class="btn btn-success contactAccountLink"><i class="fa fa-link"></i> <?= $this->translate('tr_meliscommerce_contact_link_account_button');?></button>
                    </div>
                </div>
            </div>
            <script type="application/javascript">
                $(document).ready(function(){
                    var element = "#"+activeTabId+" input.link-account-data";
                    initAccountAutoSuggest(element);
                    $(element).closest(".easy-autocomplete").width("150");

                    //check if field is cleared
                    $(element).blur(function()
                    {
                        if( $(this).val().length === 0 ) {
                            $("#"+activeTabId+" button.contactAccountLink").attr("disabled", true);
                        }
                    });
                });
            </script>
        </div>
    <?php } ?>
</div>