<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])){
    $id = 'id="'.$this->contactId.'_'.$this->zoneconfig['conf']['id'] .'"';
}
$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';

?>
<div <?php echo $id. ' '.$data_melisKey?>>
    <div class="make-switch commerce-switch" id="<?php echo $this->contactId ?>_cper_status" data-on-label="<?php echo $this->translate('tr_meliscommerce_client_status_active')?>" data-off-label="<?php echo $this->translate('tr_meliscommerce_client_status_inactive')?>" data-text-label="<?php echo $this->translate('tr_meliscommerce_clients_common_label_status')?>">
        <input type="checkbox" name="<?php echo $this->clientId ?>_cper_status" id="<?php echo $this->contactId ?>_cper_status" <?php echo $this->status?>>
    </div>
</div>
<script>
    $('#'+<?php echo $this->contactId ?>+'_cper_status').bootstrapSwitch();
</script>