<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])){
    $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
}
$data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?> class="spacing-x2 innerAll">
    <?php
    $this->melisGenericTable()->setTable(array(
        'id' => $this->clientId.'_contactList',
        'class' => 'table table-striped table-primary dt-responsive nowrap',
        'cellspacing' => '0',
        'width' => '100%'
    ));

    $columns = array();
    $columnStyle = array();
    foreach($this->tableColumns as $columnText){
        $columns[] = $columnText['text'];
    }

    $this->melisGenericTable()->setColumns($columns);

    echo $this->melisGenericTable()->renderTable();
    ?>

    <script type="text/javascript">
        $(document).ready(function() {
            <?php echo $this->getToolDataTableConfig; ?>
        });
    </script>
</div>