<?php
	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="nav-item active">
							<a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons plus" data-bs-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate('tr_meliscommerce_clients_add_contact_address') ?></a>
						</li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" <?php echo $id ?>>
                            <div class="row">
                            	<div class="col-md-12">
                                    <?php
                                    	$form = $this->meliscommerce_clients_addresses_form;
                                    	$form->setAttribute('id', 'melisCommerceClientContactAddressFormModal');
                                    	$form->prepare();
                                    	echo $this->form()->openTag($form);
                                    	echo $this->melisFieldCollection($form);
                                    	echo $this->form()->closeTag(); 
                                    ?>
                                 	<div class="footer-modal d-flex flex-row justify-content-between">
                                 		<button data-bs-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                                 		<button class="btn btn-success" id="saveClientContactAddress" data-tabid="<?php echo $this->tabId ?>" data-contactId="<?php echo $this->contactId ?>" data-loading-text="<?php echo $this->translate('tr_meliscommerce_clients_common_label_loading') ?>"><i class="fa fa-plus"></i>  <?php echo $this->translate('tr_meliscommerce_clients_add_contact_address'); ?></button>
                                 	</div>
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
