<?php 
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
?>

<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons notes" data-bs-toggle="tab" aria-expanded="true"><i></i> 
                		<?= $this->translate('tr_meliscommerce_contact_common_import')?></a></li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" <?php echo $id ?>>
                            <div class="row">
                            	<div class="col-md-12">
                                    <div class="sample_import_format">
                                        <div class="file-content-format">
                                            <div>
                                                <span class="span-10"><?= $this->translate('tr_meliscommerce_contact_import_file_content_format');?></span>
                                                <br/>
                                                <br/>
                                                <span class="span-10 format"><?= $this->translate('tr_meliscommerce_contact_import_file_content_format_header');?></span>
                                            </div>
                                            <div>
                                                <br/>
                                                <span class="span-10 format-content"><a id="downloadImportTemplate" href="#"><?= $this->translate('tr_meliscommerce_contact_import_file_content_format_content');?></a></span>
                                            </div>
                                        </div>
                                    </div>

                                    <?php
                                    $form = $this->meliscommerce_contact_list_import_contacts_form;
                                    $form->prepare();
                                    echo $this->form()->openTag($form);
                                    foreach($form->getElements() as $key => $val)  {
                                        echo '<div class="form-group">';
                                        if ($val->getLabel())
                                        {
                                            $required = '';
                                            if(!empty($val->getAttribute('required'))){
                                                $required = ' <sup>*</sup>';
                                            }
                                            echo $this->formLabel()->openTag($val);
                                            echo $val->getLabel();
                                            echo $required;
                                            echo $this->formLabel()->closeTag();
                                        }
                                        echo $this->formElement($val, array('class' => 'form-control'));
                                        echo '</div>';
                                    }
                                    echo $this->form()->closeTag($form);
                                    ?>

                                    <div class="test-results hidden">
                                        <div class="contacts-import-progress">
                                            <span><?= $this->translate('tr_meliscommerce_contact_import_progress')?> (<prog_percent></prog_percent>%)</span>
                                            <div class="progress">
                                                <div id="contactsImportProgressBar" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="results">
                                            <p></p>
                                            <ul></ul>
                                        </div>
                                    </div>

                                 	<div class="footer-modal d-flex flex-row justify-content-between">
                                        <div class="btnCloseBlock">
                                            <button data-bs-dismiss="modal" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscommerce_clients_common_btn_close')?></button>
                                        </div>
                                 		<div class="btnImportBlock">
                                            <button class="btn btn-info" id="testImportContacts" data-action="test"><i class="fa fa-search"></i>  <?php echo $this->translate('tr_meliscommerce_contact_common_test_import') ?></button>
                                            <button disabled class="btn btn-success" id="importContacts" data-action="import"><i class="fa fa-arrow-circle-down"></i>  <?php echo $this->translate('tr_meliscommerce_contact_common_import') ?></button>
                                        </div>
                                 	</div>
                            	</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $('#contact_file').filestyle({
                buttonBefore: true,
                buttonText: "<?= $this->translate('tr_meliscommerce_contact_import_choose_file')?>",
            });
        </script>
    </div>
</div>